clean up gitaction yml
ufs-community/ufs-weather-model pull request #1552
Opened 2022-12-30 14:39 UTC by jkbk2004

## Description

### Top of commit queue on: TBD

### Input data additions/changes
- [ ] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

2023-01-02 16:03 UTC, jkbk2004 commented
@BrianCurtis-NOAA @zach1221 I created this pr to fix the issue of gitaction failures. The issue seems to be originated somewhere from pre job step in aux.yml. Once pre runs ok, it will create id_file w/o problem. I tested ok the cleanup of aux.yml with my personal git setup. No impact on other tests at all. so we can try to merge in tomorrow as a hot fix.

2023-01-02 16:05 UTC, jkbk2004 commented
The key point is to clean up some of outdated lines like deleting run-ci labels in aux.yml

2023-01-02 16:06 UTC, zach1221 approved these changes

2023-01-03 13:27 UTC, BrianCurtis-NOAA requested changes
@jkbk2004 Is the github repo check only checking fv3 submodule now? If so, we want to check all sub component repos. Maybe this is being worked on though?

Also I don't see a reason to overwrite the previous UFS RT logs. Please remove those.

2023-01-03 13:53 UTC, BrianCurtis-NOAA approved these changes

2023-01-03 13:56 UTC, merged