- Add FAQ chapter with the following questions:
ufs-community/ufs-weather-model pull request #157
Opened 2020-06-30 21:42 UTC by JulieSchramm

- How do I build and run a single test of the UFS Weather Model?
   - How do I change the length of the model run?
   - How do I change the model output to netcdf or nemsio?

- Add FAQ chapter to index.rst
- Add references to sections in other chapters
- Add FAQ chapter to introduction

Both html and latex builds succeed.

2020-07-01 21:00 UTC, llpcarson commented
Good info to add, Julie!

2020-07-02 02:47 UTC, ligiabernardet requested changes

2020-07-02 02:47 UTC, ligiabernardet commented on doc/UsersGuide/source/FAQ.rst
> +- You can bypass the workflow, pre- and post-processing steps.
I suggest changing the language here. The UFS WM does not have a workflow with pre- and post- that needs to be bypassed (the App does, but this documentation is for the model).
```suggestion
- It does not require a workflow, pre- or post-processing steps.
```

2020-07-02 02:47 UTC, ligiabernardet commented on doc/UsersGuide/source/FAQ.rst
> +How do I change the model output to netcdf or nemsio?
```suggestion
How do I select the file format for the model output (NetCDF or NEMSIO)?
```

2020-07-15 20:41 UTC, ligiabernardet approved these changes
Looks good to me. Thanks.

2020-07-15 21:21 UTC, llpcarson approved these changes
approved

2020-07-15 21:34 UTC, ligiabernardet commented
@junwang-noaa What is the process for having these documentation updates merged into the release branch? Note that we have a few more updates coming.

2020-07-15 21:58 UTC, merged

2020-07-15 21:59 UTC, junwang-noaa commented
> @junwang-noaa What is the process for having these documentation updates merged into the release branch? Note that we have a few more updates coming.

Please submit PR to the release branch and it will be committed after reviewers' approval.

2020-07-15 22:03 UTC, ligiabernardet commented
Thanks @junwang-noaa The PR has been submitted and the assigned reviewers have approved it. If necessary, you can assign additional reviewers. Thanks.