Feature/add faqs Document input.nml sections fms_io_nml, interpolator_nml and namsfc
ufs-community/ufs-weather-model pull request #175
Opened 2020-07-23 21:01 UTC by JulieSchramm

## Description
- Add description of namelist sections fms_io_nml, interpolator_nml and namsfc in input.nml
- Moved documentation of input.nml into a new file InputNML.inc since InputsOutputs.rst was getting too big.

### Issue(s) addressed
Sections of input.nml need to be documented.

## Testing
- Both html and latex builds succeed.
- Non-answer changing.

## Dependencies
None.

2020-08-07 13:13 UTC, climbfuji commented
@ligiabernardet if you can review and approve this PR, I will make sure that it gets merged into the ufs-weather-model public release branch. Thanks!

2020-08-07 15:29 UTC, ligiabernardet requested changes
Thank you @JulieSchramm, this added documentation is very helpful.

2020-08-07 15:29 UTC, ligiabernardet commented on doc/UsersGuide/source/FAQ.rst
> +How do I change the model output to netcdf or nemsio?
```suggestion
How do I change the model output to netCDF or NEMSIO?
```

2020-08-07 15:29 UTC, ligiabernardet commented on doc/UsersGuide/source/FAQ.rst
> +How do I change the model output to netcdf or nemsio?
Is this only valid if the write component is being used?

2020-08-11 20:18 UTC, ligiabernardet approved these changes

2020-08-11 20:21 UTC, merged