Add section with description of atmos_model_nml.
ufs-community/ufs-weather-model pull request #200
Opened 2020-09-08 19:27 UTC by JulieSchramm

## Description

Add a description of the variables in atmos_model_nml to the Users Guide.

## Testing

html and latex builds succeed

## Dependencies

None

2020-09-08 20:08 UTC, ligiabernardet commented on doc/UsersGuide/source/InputNML.inc
> +     - Output frequency during forecast time from 0 to ``fhmax``, or from ``fhmaxhf`` to ``fhmaxhf`` if ``fhmaxf>0``.
I am not understanding this definition. Does this make sense: from fhmaxhf to fhmaxhf???
Should it be (...) or from fhmaxhf to fxmax if fhmaxhf>0?

2020-09-08 20:11 UTC, junwang-noaa commented
It should be   fhmaxhf to fhmax

On Tue, Sep 8, 2020 at 4:09 PM ligiabernardet <notifications@github.com>
wrote:

> *@ligiabernardet* commented on this pull request.
> ------------------------------
>
> In doc/UsersGuide/source/InputNML.inc
> <https://github.com/ufs-community/ufs-weather-model/pull/200#discussion_r485167941>
> :
>
> > +   * - fdiag
> +     - Array with dimension ``maxhr`` = 4096 listing the diagnostic output times (in hours) for the GFS physics.
> +       This can either be a list of times after initialization, or an interval if only the first entry is
> +       nonzero. The default setting of 0 will result in no outputs.
> +     - real
> +     - 0.
> +   * - fhmax
> +     - The maximal forecast time for output.
> +     - real
> +     - 384.0
> +   * - fhmaxhf
> +     - The maximal forecast hour for high frequency output.
> +     - real
> +     - 120.0
> +   * - fhout
> +     - Output frequency during forecast time from 0 to ``fhmax``, or from ``fhmaxhf`` to ``fhmaxhf`` if ``fhmaxf>0``.
>
> I am not understanding this definition. Does this make sense: from fhmaxhf
> to fhmaxhf???
> Should it be (...) or from fhmaxhf to fxmax if fhmaxhf>0?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/200#pullrequestreview-484457484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI7D6TJOBL3UDTZP57WCGG3SE2FONANCNFSM4RAMZJIA>
> .
>

2020-09-10 17:31 UTC, ligiabernardet requested changes
Tks for fixing nmelist description.
In introduction and in Chapter 5, https://stochastic-physics.readthedocs.io/en/release-ufs-v1.1.0/ is a broken link. Should be https://stochastic-physics.readthedocs.io/en/ufs-v1.1.0/.
Please review all links. They all should work EXCEPT for those that refer to the ufs-weather-model tag for this release, which has not been created yet.

2020-09-10 17:42 UTC, JulieSchramm commented
This doesn't work:

https://dtcenter.org/GMTB/v4.1.0/sci_doc/CCPPsuite_nml_desp.html

On Thu, Sep 10, 2020 at 11:31 AM ligiabernardet <notifications@github.com>
wrote:

> *@ligiabernardet* requested changes on this pull request.
>
> Tks for fixing nmelist description.
> In introduction and in Chapter 5,
> https://stochastic-physics.readthedocs.io/en/release-ufs-v1.1.0/ is a
> broken link. Should be
> https://stochastic-physics.readthedocs.io/en/ufs-v1.1.0/.
> Please review all links. They all should work EXCEPT for those that refer
> to the ufs-weather-model tag for this release, which has not been created
> yet.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/200#pullrequestreview-486158785>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3WNUZ4BDZRE6JAIG4QTTLSFEEPLANCNFSM4RAMZJIA>
> .
>

2020-09-10 17:44 UTC, JulieSchramm commented
Maybe this:

https://dtcenter.ucar.edu/GMTB/v4.1.0/sci_doc/CCPPsuite_nml_desp.html

On Thu, Sep 10, 2020 at 11:42 AM Julie Schramm <schramm@ucar.edu> wrote:

> This doesn't work:
>
> https://dtcenter.org/GMTB/v4.1.0/sci_doc/CCPPsuite_nml_desp.html
>
> On Thu, Sep 10, 2020 at 11:31 AM ligiabernardet <notifications@github.com>
> wrote:
>
>> *@ligiabernardet* requested changes on this pull request.
>>
>> Tks for fixing nmelist description.
>> In introduction and in Chapter 5,
>> https://stochastic-physics.readthedocs.io/en/release-ufs-v1.1.0/ is a
>> broken link. Should be
>> https://stochastic-physics.readthedocs.io/en/ufs-v1.1.0/.
>> Please review all links. They all should work EXCEPT for those that refer
>> to the ufs-weather-model tag for this release, which has not been created
>> yet.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ufs-community/ufs-weather-model/pull/200#pullrequestreview-486158785>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AA3WNUZ4BDZRE6JAIG4QTTLSFEEPLANCNFSM4RAMZJIA>
>> .
>>
>

2020-09-10 17:57 UTC, ligiabernardet commented
@Laurie Carson <carson@ucar.edu> My understanding is that we should not
give the users any link to dtcenter.ucar.edu, only dtcenter.org.
The main link for the SciDoc (https://dtcenter.org/GMTB/v4.1.0/sci_doc/)
works but redirected to ucar.edu.
The links underneath (e.g., to namelist description) are only working on
ucar.edu.
Can you please advise?


On Thu, Sep 10, 2020 at 11:44 AM JulieSchramm <notifications@github.com>
wrote:

> Maybe this:
>
> https://dtcenter.ucar.edu/GMTB/v4.1.0/sci_doc/CCPPsuite_nml_desp.html
>
> On Thu, Sep 10, 2020 at 11:42 AM Julie Schramm <schramm@ucar.edu> wrote:
>
> > This doesn't work:
> >
> > https://dtcenter.org/GMTB/v4.1.0/sci_doc/CCPPsuite_nml_desp.html
> >
> > On Thu, Sep 10, 2020 at 11:31 AM ligiabernardet <
> notifications@github.com>
> > wrote:
> >
> >> *@ligiabernardet* requested changes on this pull request.
> >>
> >> Tks for fixing nmelist description.
> >> In introduction and in Chapter 5,
> >> https://stochastic-physics.readthedocs.io/en/release-ufs-v1.1.0/ is a
> >> broken link. Should be
> >> https://stochastic-physics.readthedocs.io/en/ufs-v1.1.0/.
> >> Please review all links. They all should work EXCEPT for those that
> refer
> >> to the ufs-weather-model tag for this release, which has not been
> created
> >> yet.
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/ufs-community/ufs-weather-model/pull/200#pullrequestreview-486158785
> >,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/AA3WNUZ4BDZRE6JAIG4QTTLSFEEPLANCNFSM4RAMZJIA
> >
> >> .
> >>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/200#issuecomment-690564280>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7WQAV5ID6PBKLCQU27WGTSFEF75ANCNFSM4RAMZJIA>
> .
>

2020-09-10 23:10 UTC, ligiabernardet approved these changes

2020-09-10 23:18 UTC, climbfuji approved these changes
Looks good. @junwang-noaa @DusanJovic-NOAA this is the last missing documentation update to merge into release/public-v1 of the ufs-weather-model before it can be tagged as ufs-v1.1.0.

2020-09-11 00:30 UTC, merged