WW3 feature:  Langmuir turbulence parameterization
ufs-community/ufs-weather-model pull request #2195
Opened 2024-03-15 18:52 UTC by MatthewMasarik-NOAA

## Commit Queue Requirements:
- [ ] Fill out all sections of this template.
- [X] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:
Adds Langmuir turbulence parameterization developed by ESCOMP () to allow computing Stokes drift diagnostics within the WW3 sub-component.

### Commit Message:
Add Langmuir turbulence parameterization for computing Stokes drift diagnostics.  Authors: @qingli411, @alperaltuntas
```
  * WW3 - Langmuir turbulence parameterization
```

### Priority:
* Normal.

## Git Tracking
### UFSWM:
* Closes #2187

### Sub component Pull Requests:
* WW3:  needed by noaa-emc/ww3/pull/1034

### UFSWM Blocking Dependencies:
* None

---
## Changes
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

[2024-03-13.RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/14619315/2024-03-13.RegressionTests_hera.log.txt), test_changes.list commited:  517e05d

### Input data Changes:
* Updated input data.  

New `mod_def`'s for all RTs are the updates to the input data.  Directory location containing new `mod_def`s:  `/scratch1/NCEPDEV/climate/Matthew.Masarik/waves/share/ufs/moddefs/WW3_input_data_20240214`.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

2024-03-27 21:20 UTC, jkbk2004 commented
@MatthewMasarik-NOAA can you sync up branch?

2024-03-27 21:26 UTC, MatthewMasarik-NOAA commented
Hi @jkbk2004, looks like theres a merge conflict.  Let me look into it

2024-03-27 22:20 UTC, MatthewMasarik-NOAA commented
Hi @jkbk2004, the conflict is just in rt.sh. The difference is INPUTDATA_ROOT_WW3 which I set to the directory with the updated mod_defs.  @JessicaMeixner-NOAA had advised this.  Should I resolve this by committing my version of rt.sh, or revert it to the normal state?

2024-03-27 22:46 UTC, jkbk2004 commented
@MatthewMasarik-NOAA I rsynced up to WW3_input_data_20220624 on hera. Do you like to have WW3_input_data_20240214 in baseline input directory? I backed up WW3_input_data_20220624. So no problem to go with WW3_input_data_20240214.

2024-03-27 22:54 UTC, MatthewMasarik-NOAA commented
@jkbk2004, yes that sounds great.  please add WW3_input_data_20240214 to the baseline input directory.

So for my side, I should set `INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20240214` in `rt.sh` to resolve the conflict, is that correct?

2024-03-27 23:00 UTC, DeniseWorthen commented
@jkbk2004 Do not over-write the existing  WW3_input_data_20220624. You need to create a new dated WW3_input_data inside of input-data for the new mod_def files.

2024-03-27 23:00 UTC, jkbk2004 commented
> @jkbk2004, yes that sounds great. please add WW3_input_data_20240214 to the baseline input directory.
> 
> So for my side, I should set `INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20240214` in `rt.sh` to resolve the conflict, is that correct?

@MatthewMasarik-NOAA /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/WW3_input_data_20240214 is there now. Go ahead to set as INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20240214. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI

2024-03-27 23:01 UTC, jkbk2004 commented
> WW3_input_data_20220624

WW3_input_data_20220624 is intact on hera.

2024-03-27 23:03 UTC, DeniseWorthen commented
Please make sure that the original WW3_input_data_20220624/ is in place. If I look on Hera, those files have the current day's timestamp.

2024-03-27 23:04 UTC, MatthewMasarik-NOAA commented
> @MatthewMasarik-NOAA /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/WW3_input_data_20240214 is there now. Go ahead to set as INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20240214.

@jkbk2004, I'll go ahead with that

2024-03-28 00:08 UTC, MatthewMasarik-NOAA commented
@jkbk2004, I just resolved the conflict and updated my branch.  I'm not completely sure if the FV3,MOM6 updates come in OK.  please let me know if not

2024-03-28 00:25 UTC, jkbk2004 commented
> @jkbk2004, I just resolved the conflict and updated my branch. I'm not completely sure if the FV3,MOM6 updates come in OK. please let me know if not

looks good now.

2024-03-28 13:57 UTC, jkbk2004 commented
hera is slow today. But I submitted jobs. @zach1221 @FernandoAndrade-NOAA please, pick up other machines. @BrianCurtis-NOAA FYI: this pr is ready.

2024-03-28 14:01 UTC, jkbk2004 commented
@FernandoAndrade-NOAA can you reflect to this pr for the STMP/PTMP gaea line update needed to cover https://github.com/ufs-community/ufs-weather-model/issues/2198 ? We need to update the ecflow version number for hera as well.

2024-03-28 15:36 UTC, jkbk2004 commented
looks like we need to resolve conflicts on rt.sh in this pr. @MatthewMasarik-NOAA we don't need to update rt.sh except https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/feature/langmuir-parameterization/tests/rt.sh#L938, right?

2024-03-28 15:41 UTC, FernandoAndrade-NOAA commented
> looks like we need to resolve conflicts on rt.sh in this pr. @MatthewMasarik-NOAA we don't need to update rt.sh except https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/feature/langmuir-parameterization/tests/rt.sh#L938, right?

the conditionals and load for rocoto and ecflow were removed with this PRs rt.sh changes as well

2024-03-28 15:57 UTC, BrianCurtis-NOAA requested changes

2024-03-28 15:57 UTC, BrianCurtis-NOAA commented on tests/2024-03-13.test_changes.list.txt
This file should be renamed "test_changes.list"

2024-03-28 16:01 UTC, DeniseWorthen commented on tests/2024-03-13.test_changes.list.txt
And can someone do white-space clean up on rt.sh?

2024-03-28 16:02 UTC, FernandoAndrade-NOAA commented
> looks like we need to resolve conflicts on rt.sh in this pr. @MatthewMasarik-NOAA we don't need to update rt.sh except https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/feature/langmuir-parameterization/tests/rt.sh#L938, right?

I restored rt.sh, updated the WW3 input date and added the Gaea paths update for stmp and ptmp for users outside of the epic group.

2024-03-28 16:05 UTC, MatthewMasarik-NOAA commented
> looks like we need to resolve conflicts on rt.sh in this pr. @MatthewMasarik-NOAA we don't need to update rt.sh except https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/feature/langmuir-parameterization/tests/rt.sh#L938, right?

@jkbk2004 
this was the only line I thought needed to be updated: https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/055b13ffbe0e49abbcf8d4e503ee617a8e78e5be/tests/rt.sh#L990

2024-03-28 16:09 UTC, MatthewMasarik-NOAA commented
Regarding rt.sh, test_changes.list, and whitespace -- 
please let me know if I should make these updates to the branch, or if these comments are for CMs

2024-03-28 16:10 UTC, FernandoAndrade-NOAA commented
> > looks like we need to resolve conflicts on rt.sh in this pr. @MatthewMasarik-NOAA we don't need to update rt.sh except https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/feature/langmuir-parameterization/tests/rt.sh#L938, right?
> 
> @jkbk2004 this was the only line I thought needed to be updated: https://github.com/MatthewMasarik-NOAA/ufs-weather-model/blob/055b13ffbe0e49abbcf8d4e503ee617a8e78e5be/tests/rt.sh#L990

That's the line he was pointing to before I restored and resynced rt.sh, sorry about that confusion.

2024-03-28 16:16 UTC, DeniseWorthen commented on tests/2024-03-13.test_changes.list.txt
Whitespace looks OK now. I'm not sure what had happened to it.

2024-03-29 16:34 UTC, zach1221 commented
Ok let's start the merge process.

2024-03-29 16:43 UTC, JessicaMeixner-NOAA commented
WW3 is merged: https://github.com/NOAA-EMC/WW3/commit/d9b3172f4197c65d471662c6952a668152d71230

2024-03-29 18:51 UTC, jkbk2004 approved these changes

2024-03-29 19:18 UTC, BrianCurtis-NOAA approved these changes

2024-03-29 19:23 UTC, merged