add a model_configure template for global nest
ufs-community/ufs-weather-model pull request #2252
Opened 2024-04-26 03:34 UTC by guoqing-noaa

## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:
add a model_configure template for global nest

### Commit Message:
add a model_configure template for global nest
`tests/parm/model_configure_nest.IN`

### Priority:
* High: Need this template file to run the global-nest workflow 

## Git Tracking
### UFSWM:

* None

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
## Changes
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.
* Just add a model_configure template under tests/parm, no need to run RT suite and commit test_changes.list.

### Input data Changes:

* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

2024-05-07 14:05 UTC, DeniseWorthen commented
@jkbk2004 This PR is requesting high priority.

2024-05-07 14:08 UTC, DusanJovic-NOAA commented
Which regression test is using (testing) this template?

2024-05-07 16:23 UTC, guoqing-noaa commented
> Which regression test is using (testing) this template?

This is a new template for the global nest applications. No existing regression tests for it.
@SamuelTrahanNOAA is trying to add a global nest regression test to this repo. Could you convert this PR to a draft PR at this moment? Thanks!

2024-05-07 16:59 UTC, SamuelTrahanNOAA commented
There are regression tests in the repository already. I'm replacing one of them.

These are the tests:

1. `gnv1_c96_no_nest_debug` - unnested uncoupled C96 GFS with global_nest_v1 physics suite. Code is compiled in debug mode. Run for GNU and Intel compilers.  It uses the exact same C96 input as dozens of other ufs-weather-model regression tests.
2. `gnv1_nested` - HAFS North Atlantic global nested test case with global_nest_v1 physics. This is the same input used for other HAFS global cases. Compiled optimized; intel only.

I'm replacing the second one (`gnv1_nested`). It'll use the Water in the West domain instead of the HAFS North Atlantic domain. Also, it'll be based on the GFS-like regression tests (using control_run.IN) so it'll be more compatible with your workflow.

2024-05-07 22:28 UTC, SamuelTrahanNOAA requested changes

2024-05-07 22:28 UTC, SamuelTrahanNOAA commented on tests/parm/model_configure_nest.IN
> +</output_grid_02>
These are the variables currently used in the regression tests:

```suggestion
<output_grid_02>
output_grid:             @[OUTPUT_GRID_2]
imo:                     @[IMO_2]
jmo:                     @[JMO_2]
cen_lon:                 @[CEN_LON_2]
cen_lat:                 @[CEN_LAT_2]
lon1:                    @[LON1_2]
lat1:                    @[LAT1_2]
lon2:                    @[LON2_2]
lat2:                    @[LAT2_2]
dlon:                    @[DLON_2]
dlat:                    @[DLAT_2]
</output_grid_02>
```

2024-05-07 22:47 UTC, SamuelTrahanNOAA commented
I'm unclear on what is gained by merging this PR. The reason it is high priority is that a global-workflow PR needs a model_configure for the global_nest_v1 suite. However, the global-workflow PR generates an incorrect input.nml. Its namelist settings don't match the ccpp suite. The new file isn't used by any regression test yet.

Also, the `NEST_` and `_NEST` variables won't work long-term. What if there is more than one nest?

I'll have another PR soon with a regression test that has a correct namelist.

2024-05-07 22:53 UTC, guoqing-noaa commented
> I'm unclear on what is gained by merging this PR. The reason it is high priority is that a global-workflow PR needs a model_configure for the global_nest_v1 suite. However, the global-workflow PR generates an incorrect input.nml. Its namelist settings don't match the ccpp suite. The new file isn't used by any regression test yet.
> 
> Also, the `NEST_` variables won't work long-term. What if there is more than one nest?
> 
> I'll have another PR soon with a regression test that has a correct namelist.

@SamuelTrahanNOAA If you will create another PR,  I will close this PR. Thanks!

2024-05-15 20:17 UTC, SamuelTrahanNOAA commented
My replacement PR is #2284. Unfortunately, the model isn't stable for the C96 case, and I have no fix for that yet. Please see that PR for details.

2024-05-30 20:33 UTC, guoqing-noaa commented
Close this PR. The issue is addressed at PR https://github.com/ufs-community/ufs-weather-model/pull/2284

2024-05-30 20:33 UTC, closed without merging