GW-RT global_control.nml modifications
ufs-community/ufs-weather-model pull request #2425
Opened 2024-09-03 14:54 UTC by dpsarmie

## Commit Queue Requirements:
- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:
This PR will modify the global_control.nml to add variables that are present in the Global Workflow scripts but not currently present in the RTs. Some variables will also be changed from constants to variable placeholders. This will allow Global Workflow to use the global_control.nml as a template for their operations. 
This commit will be done in such a way to not change any of the RT baselines.

### Commit Message:
```
* UFSWM - Modify global_control.nml to add compatibility with Global Workflow
```

### Priority:
* Normal

## Git Tracking
### UFSWM:
* Closes #2424 

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
## Changes
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

2024-09-06 22:52 UTC, BrianCurtis-NOAA submitted a review, later dismissed

2024-09-09 20:08 UTC, NeilBarton-NOAA commented on tests/tests/cpld_control_sfs
Please add the update damping parameters for C96 SFS test to the same as g-w

 export K_SPLIT=1
 export N_SPLIT=4
 export TAU=8.0
 export NUDGE_QV=.false.
 export RF_CUTOFF=100
 export FV_SG_ADJ=1800
 export VTDM4=0.05

see https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.ufs

2024-09-09 21:39 UTC, dpsarmie commented on tests/tests/cpld_control_sfs
Hey Neil,

Most of those changes are going to be a part of this PR: https://github.com/ufs-community/ufs-weather-model/pull/2363

I'll switch the NUDGE_QV to false and I'll have to change the VTDM4 value for the sfs case. The other values will be imported under the new export_ugwpv1 function.

For the RT themselves, I did have to change some of the timesteps and/or remappings for certain tests to get them under the preset time limit. All tests were checked with the updated parameter values on Hera and worked, but some tests were taking anywhere from 45 mins - 2 hours of run-time.

Extending the time limits would put more demand on the RTs, so that's the solution I went with.

If there's an issue with that solution, let me know and we can think of others ways around the problem.

Thanks.

2024-09-10 12:31 UTC, NeilBarton-NOAA commented on tests/tests/cpld_control_sfs
Thanks @dpsarmie I see the updates in the other PR

2024-09-16 20:26 UTC, dpsarmie commented on tests/tests/cpld_control_sfs
These sfs specific changes will be officially rolled into this PR (nudge_qv and vtdm4).

2024-09-21 06:39 UTC, NickSzapiro-NOAA commented
@dpsarmie I also hit a problem with DT_ATMOS. For gfsv17 tests for example:
1. export_fv3 sets a default DT_ATMOS
2. export_cpl sets a different default DT_ATMOS that is used in export_{cice,cmeps,...} for DT_CICE, coupling_interval_fast_sec,.. 
3. Then export_ugwpv1 sets a different DT_ATMOS based on ATMRES
4. But cice, cmeps,... never see changes from step 3

Maybe export_cpl should not touch DT_ATMOS either. 

It may also be better in these tests to call export_fv3, then export_ugwpv1, then export_cpl so atmosphere is configured properly before setting other components

2024-09-23 13:37 UTC, dpsarmie commented
Thanks @NickSzapiro-NOAA for bringing that up. I'll have to do some more testing to see what makes sense. I think the simplest solution would be to make the atm only and cpld default DT_ATMOS the same, but I want to make sure that the runtime isn't greatly affected for the atm only cases. 
If not, then there needs to be a straightforward way to differentiate between the possible combinations and what needs to be defined. 
Although I agree that the ugwpv1 call should come before the cpld call to resolve #4.

2024-09-23 15:25 UTC, NickSzapiro-NOAA commented
I think it is better if DT_ATMOS is thought of as input to export_cpl (and not modified in export_cpl). The issue I'm focusing on is (coupling) timesteps for gfsv17 test, where ufs.configure is the same before and after 2363:
```
# CMEPS warm run sequence
runSeq::
@3600
   MED med_phases_prep_wav_avg
   MED med_phases_prep_ocn_avg
   MED -> WAV :remapMethod=redist
   MED -> OCN :remapMethod=redist
   WAV
   OCN
   @720
     MED med_phases_prep_atm
     MED med_phases_prep_ice
     MED -> ATM :remapMethod=redist
     MED -> ICE :remapMethod=redist
     ATM
     ICE
     ATM -> MED :remapMethod=redist
     MED med_phases_post_atm
     ICE -> MED :remapMethod=redist
     MED med_phases_post_ice
     MED med_phases_ocnalb_run
     MED med_phases_prep_ocn_accum
     MED med_phases_prep_wav_accum
   @
   OCN -> MED :remapMethod=redist
   WAV -> MED :remapMethod=redist
   MED med_phases_post_ocn
   MED med_phases_post_wav
   MED med_phases_restart_write
@
::
```

But, dt_atmos in model_configure is 360s in current develop vs 720s before 2363. Was it intended for 2363 to reduce timestep for this test? Either way, now FV3<-->CMEPS no longer couple every ATM timestep, ATM timestep is different than ICE timestep,... I'm not sure this is intentional and may need hot fix if not intended.

2024-09-23 15:55 UTC, dpsarmie commented
Ok I see what you mean. 

#2363 was intended to change the timesteps to have the more optimized set of parameter values to allow for more stability at longer timesteps: https://github.com/NOAA-EMC/global-workflow/issues/2574

I'm going to move forward with your idea of having DT_ATMOS set in export_fv3 and changed in export_ugwpv1 (if needed) before calling export_cpl.

That should allow DT_CICE and coupling_interval_fast_sec to be set correctly when the other export calls are run from within export_cpl.

Line 1302 will also be removed in default_vars.sh since DT_INNER will have been set by then. 

Let me know if that logic makes sense. That should resolve the issues of not having the timing in sync between the models, correct?

2024-09-23 16:07 UTC, NickSzapiro-NOAA commented
That makes sense to me. Maybe can ask Denise to review solution too

2024-10-08 12:48 UTC, dpsarmie commented
Lastest changes do the following:

To fix the timing issue it CMEPS, default_vars.sh has been reworked. If you export DT_ATMOS and/or ATMRES before the export_fv3 (and other export functions), then all dependent variables will be auto-populated. If these variables are not set, then defaults will be set. You can still manually set these parameters after the function calls but you need to make sure that all variables that depend on DT_ATMOS and ATMRES are also set unless you intended to do so otherwise. 

Either way, the timing with CMEPS should be functioning as intended.

2024-10-08 18:14 UTC, NickSzapiro-NOAA commented
@dpsarmie In the PR description, can you add how the logic/flow in default_vars works and should be used?

2024-10-08 18:39 UTC, dpsarmie commented
@NickSzapiro-NOAA I added a snippet to the description on how it should be used. I'm actually currently working on a more detailed document for how to use the new features, so let me know if anything is unclear or if anything else should be added to the description for the PR.

2024-10-15 16:29 UTC, DeniseWorthen commented
@dpsarmie I'm getting confused about where the B4B differences are arising. It seems you're combining what is a bug-fix (the issue w/ dt_atmos), with updates of various namelist settings to match GW. Both of these tasks create non-B4B changes, is that right? Should we really be combining a bug fix w/ what is actually a new feature (consistency w/ G-W)?

2024-10-15 17:15 UTC, dpsarmie commented
@DeniseWorthen Yes, the changes to the namelist and the associated changes to default_vars (just adding variables) were changes that were still B4B comparable. 
There was a discussion a few weeks ago with EPIC to roll these other bug fixes into the PR since they are touching related files.

I've opened individual issues for documentation purposes since it is getting a bit complex. I'll add something to the description to try and detail the changes and which issue was addressed by which change in the code.  There won't be anything else added to this PR.

2024-10-15 18:20 UTC, DeniseWorthen commented
@dpsarmie Thanks for adding the information. Did either 


_Variable values that were hard-coded in global_control.nml.IN were replaced with an @ tag and the values were moved to default_vars.sh.
Another issue will also be merged into this PR. The cpld_control_sfs configuration will be changed to bring it in-line with the GW configuration. cpld_control_sfs settings were changed in the test configuration file._

change baselines?

I'm confused because the next change is described with _This will add **additional** baseline changes_. (emphasis added).

If either of the first two items changed baselines, then I believe it is poor CM practice to combine issues which both change a set of tests. Rolling them together makes it much harder to un-roll/debug in the future, if required.

2024-10-15 20:36 UTC, dpsarmie commented
@DeniseWorthen Yes, the cpld_control_sfs test underwent two baseline changes. The GW settings change (second item under **Description**) and the DT_ATMOS fix (third item) had two distinct changes in that baseline.

I can untangle those easily and create an independent PR so there's only one baseline change per PR.

2024-10-22 17:09 UTC, NickSzapiro-NOAA requested changes

2024-10-22 17:09 UTC, NickSzapiro-NOAA commented on tests/default_vars.sh
> +export ISEED_EPBL=20210325000113,20210325000114,20210325000115,20210325000116,20210325000117
I think SKEB, SPPT, SHUM are missing default values (like EPBL).

If I understand, are you wanting these to default to what is being used in GEFS prototype? Maybe @pjpegion can confirm?

2024-10-22 17:09 UTC, NickSzapiro-NOAA commented on tests/default_vars.sh
> +export ISEED_EPBL=20210325000113,20210325000114,20210325000115,20210325000116,20210325000117
Maybe we default to what's in global workflow (?):
https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.efcs

2024-10-22 17:09 UTC, NickSzapiro-NOAA commented on tests/tests/atm_ds2s_docn_dice
> +export KNOB_UGWP_VERSION=0
Why is this different than the cpld_control_nowave_noaero_p8 test it depends on?

2024-10-22 17:09 UTC, NickSzapiro-NOAA commented on tests/default_vars.sh
> +  export default_dt_atmos=0
Is DT_INNER always equal to DT_ATMOS?

Why is the value of default_dt_atmos changing here? Is it used somewhere else?

2024-10-22 17:12 UTC, dpsarmie commented
> @dpsarmie I also hit a problem with DT_ATMOS. For gfsv17 tests for example:
> 
> 1. export_fv3 sets a default DT_ATMOS
> 2. export_cpl sets a different default DT_ATMOS that is used in export_{cice,cmeps,...} for DT_CICE, coupling_interval_fast_sec,..
> 3. Then export_ugwpv1 sets a different DT_ATMOS based on ATMRES
> 4. But cice, cmeps,... never see changes from step 3
> 
> Maybe export_cpl should not touch DT_ATMOS either.
> 
> It may also be better in these tests to call `export_fv3`, then `export_ugwpv1`, then `export_cpl` so atmosphere is configured properly before setting other components

This was resolved by adding a **default_dt_atmos** variable. If **DT_ATMOS** is not defined before the `export_fv3` is called, then it will be set to its default value. Since the coupled cases and the ugwpv1 cases all have their unique **DT_ATMOS** settings, they will also change **DT_ATMOS** if it was set to default.

The new ordering of the function calls should be `export_fv3`, `export_ugwpv1`, `export_cpl`.  If **default_dt_atmos** is 1, `export_fv3` will set **DT_ATMOS** to the default value (default for uncoupled cases), `export_ugwpv1` will then set **DT_ATMOS** to the compatible value for gwpv1 based on grid resolution. The final `export_cpl` call will not change **DT_ATMOS** and then cice and cmeps will get the final **DT_ATMOS** value.

All other model configuration combinations should also work. ATM only (export_fv3), coupled using gwpv0 (export_fv3, export_cpl), ATM gwpv1 only, (export_fv3, export_ugwpv1), and coupled gwpv1 (export_fv3, export_ugwpv1, export_cpl) are all working as intended.

2024-10-22 17:27 UTC, dpsarmie commented on tests/default_vars.sh
> +  export default_dt_atmos=0
If the test is running the ugwpv1, then yes DT_INNER will be set to DT_ATMOS. If we set DT_INNER to half of DT_ATMOS (which is what GW is doing), then a handful of tests run over the allotted wall clock time. I did this to keep the RTs under the wall clock, but I did test the RTs using the GW parameters that were discussed here: https://github.com/ufs-community/ufs-weather-model/pull/2363 to make sure that they were stable on our end. 

default_dt_atmos changes here to make sure that it does not change in export_cpl(). I'm allowing export_cpl() to change DT_ATMOS for now to keep functionality with ugwpv0. When the time comes to deprecate version 0, then L1403 - 1407 should be removed.

2024-10-22 17:36 UTC, dpsarmie commented on tests/default_vars.sh
> +export ISEED_EPBL=20210325000113,20210325000114,20210325000115,20210325000116,20210325000117
Yes, I'm was setting defaults based off of GW. There are some missing entries that are not here that will be added.
I'm scheduling a meeting soon with GW to talk about some discrepancies in the RT and GW namelist and what they would prefer.
The missing defaults are here on a branch I created for the GW PR: https://github.com/dpsarmie/global-workflow/blob/feature/GW-RT_GlobalNML/global_control.nml.IN#L393

2024-10-25 11:40 UTC, dpsarmie commented on tests/tests/atm_ds2s_docn_dice
> +export KNOB_UGWP_VERSION=0
atm_ds2s_docn_dice settings should now reflect the cpld_control_nowave_noaero_p8 settings.

2024-10-25 14:26 UTC, NickSzapiro-NOAA approved these changes

2024-10-28 18:15 UTC, jkbk2004 commented
@dpsarmie I am updating bl_date: 20241028.

2024-10-29 17:27 UTC, jkbk2004 commented
@dpsarmie I pushed hera log. But I noticed computational time increases for quite some cases. Can you review and confirm? @NickSzapiro-NOAA @junwang-noaa @BrianCurtis-NOAA FYI

2024-10-29 17:33 UTC, junwang-noaa submitted a review, later dismissed

2024-10-29 20:56 UTC, dpsarmie commented
Yes I see. I'm going to go through the tests and see if we can get them all back down (future PR). Most of the increases were from ugwpv1 and fixing the CICE/coupling timestep, I believe.

2024-10-31 20:18 UTC, jkbk2004 commented
OK! we can merge this pr. any final comment?

2024-10-31 20:19 UTC, jkbk2004 approved these changes

2024-10-31 20:38 UTC, zach1221 approved these changes

2024-10-31 21:53 UTC, merged