Port UFS-WM to Ursa
ufs-community/ufs-weather-model pull request #2471
Opened 2024-10-15 19:11 UTC by ulmononian

## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:
Enable the UFS-WM to run on Ursa (Hera's follow-on machine). Currently, just using the pre-TDS via Niagara, so configurations with likely need to be updated as the machine comes closer to full implementation. 

spack-stack installation to support UFS applications using Intel LLVM compilers is in progress; see https://github.com/JCSDA/spack-stack/issues/1297. 

UFS-WM_RT data will be staged on shared Niagara/Ursa disk space for now, until dedicated Ursa filesystem is made available; once the stack installation is finished, RTs will be run using 8 available nodes (1 service, 7 compute). 

### Commit Message:
```
* UFSWM - Port UFS-WM to Ursa
```

### Priority:
* Normal

## Git Tracking
### UFSWM:
* Closes  #2435

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
## Changes
### Regression Test Changes (Please commit test_changes.list):
* PR Adds New Tests/Baselines.

### Input data Changes:
* None (just staging on Ursa)

### Library Changes/Upgrades:
* Required
  * Library names w/versions: libs. should be the same as spack-stack/1.6.0 or 1.8.0, but stacks will be built using Intel LLVM compilers
  * [Git Stack Issue (JCSDA/spack-stack#)](https://github.com/JCSDA/spack-stack/issues/1297)
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

2024-11-05 23:42 UTC, ulmononian commented
quick update: this work is on hold while we wait for ursa's `oso` system, which will have internet connectivity and allow the spack-stack/1.8.0 installation to proceed.

2024-12-16 19:20 UTC, ulmononian commented
we are still waiting for internet connectivity to be enabled on ursa so that the spack-stack build can be completed. @RaghuReddy-NOAA do you have any update on this?

2024-12-17 17:32 UTC, RaghuReddy-NOAA commented
@ulmononian The login node nfe91 is now able to access the external network.  Please note that it is still behind a firewall, and any site that is reachable by Hera/Niagara should be reachable from nfe91 too.

2025-01-16 23:54 UTC, ulmononian commented
currently testing ufs-wm w/ spack-stack/1.8.0 on ursa.

some issues with cmake and locating mpi libs right now, i.e., when trying to run cmake for the atm-only model

```
cmake -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_flake,FV3_GFS_v17_p8,FV3_GFS_v17_p8_rrtmgp,FV3_GFS_v15_thompson_mynn_lam3km,FV3_WoFS_v0,FV3_GFS_v17_p8_mynn,FV3_GFS_v17_p8_ugwpv1 -D32BIT=ON ..

```

i get:

```
-- Could NOT find MPI_C (missing: MPI_C_WORKS)
CMake Error at /contrib/spack-stack/envs/1.8.0/ue-oneapi-ifort-2024.2.1/install/oneapi/2024.2.1/cmake-3.27.9-zfrh7no/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /contrib/spack-stack/envs/1.8.0/ue-oneapi-ifort-2024.2.1/install/oneapi/2024.2.1/cmake-3.27.9-zfrh7no/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /contrib/spack-stack/envs/1.8.0/ue-oneapi-ifort-2024.2.1/install/oneapi/2024.2.1/cmake-3.27.9-zfrh7no/share/cmake-3.27/Modules/FindMPI.cmake:1837 (find_package_handle_standard_args)
  CMakeLists.txt:148 (find_package)
```

this corresponds to an error generated during the find MPI section of the top-level ufs-wm `CMakeLists.txt`. below is the `module show` for the `stack-intel-oneapi-mpi/2021.13` modulefile that is loaded at compile time:

```
[Cameron.Book@nfe91 build]$ module show  stack-intel-oneapi-mpi/2021.13
--------------------------------------------------------------------------------------------------------------------------------------------------------
   /contrib/spack-stack/envs/1.8.0/ue-oneapi-ifort-2024.2.1/install/modulefiles/oneapi/2024.2.1/stack-intel-oneapi-mpi/2021.13.lua:
--------------------------------------------------------------------------------------------------------------------------------------------------------
help([[]])
family("MetaMPI")
conflict("stack-intel-mpi")
conflict("stack-intel-oneapi-mpi")
conflict("stack-cray-mpich")
conflict("stack-mpich")
conflict("stack-mpt")
load("intel-oneapi-mpi/2021.13.1")
prereq("intel-oneapi-mpi/2021.13.1")
prepend_path("MODULEPATH","/contrib/spack-stack/envs/1.8.0/ue-oneapi-ifort-2024.2.1/install/modulefiles/intel-oneapi-mpi/2021.13-eaajhcw/oneapi/2024.2.1")
setenv("MPICC","mpiicx")
setenv("MPICXX","mpiicpx")
setenv("MPIF77","mpiifort")
setenv("MPIF90","mpiifort")
setenv("MPI_CC","mpiicx")
setenv("MPI_CXX","mpiicpx")
setenv("MPI_F77","mpiifort")
setenv("MPI_F90","mpiifort")
setenv("I_MPI_CC","mpiicc")
setenv("I_MPI_CXX","mpiicpc")
setenv("I_MPI_F77","/apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2024.2.1-oqhstbmawnrsdw472p4pjsopj547o6xs/compiler/2024.2/bin/ifort")
setenv("I_MPI_F90","mpiifort")
setenv("I_MPI_FC","mpiifort")
setenv("intel_oneapi_mpi_ROOT","/apps/spack-2024-12/linux-rocky9-x86_64/oneapi-2024.2.1/intel-oneapi-mpi-2021.13.1-ss72gbndvat3oz22sa6lhmlbjkeabrn4")
whatis("Name: stack-intel-oneapi-mpi")
whatis("Version: 2021.13")
whatis("Category: library")
whatis("Description: stack-intel-oneapi-mpi mpi library and module access")
```

i've also tried changing the envvars set in the ufs_ursa modulefile (mirroring some of the approaches in the hercules/hera/gaeac6 llvm lua files), to no avail so far. i've also tried w/ system cmake, but no difference.

2025-01-24 19:14 UTC, ulmononian commented
update: testing w/ newly built  `spack-stack/1.6.0/fms-2024.01`

`control_c48` ran successfully w/ icx,icpx,ifx: ` /collab1/data/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_1260965`

2025-01-24 21:31 UTC, ulmononian commented
i tried to build the WM in `S2SWA` mode using the same spack-stack/1.6.0/fms-2024.01 env as in my previous comment. at first, doing this via rt.sh, it failed in the cmake step for MOM6 `/collab1/data/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_1265768`):

```
CMake Error at MOM6-interface/CMakeLists.txt:35 (add_library):
  Cannot find source file:

    MOM6/src/diagnostics/MOM_diagnose_MLD.F90
```
i checked some things, purged modules and ran again, only to see that same `MPI_C` error we hit using spack-stack/1.8.0 for the ATM-only model (`/collab1/data/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_1270036`; see https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2597144299):

```
CMake Error at /contrib/spack-stack/envs/1.6.0/ue-intel-2023.2.0/install/intel/2021.10.0/cmake-3.23.1-zjdo26m/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /contrib/spack-stack/envs/1.6.0/ue-intel-2023.2.0/install/intel/2021.10.0/cmake-3.23.1-zjdo26m/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /contrib/spack-stack/envs/1.6.0/ue-intel-2023.2.0/install/intel/2021.10.0/cmake-3.23.1-zjdo26m/share/cmake-3.23/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
```

we are testing different stacks & different compilers, hitting the same cmake error, once in an ATM build and once in a coupled build. i am not sure what is going on.

@rickgrubin-noaa @RatkoVasic-NOAA @RaghuReddy-NOAA @DusanJovic-NOAA @climbfuji  fyi

2025-01-27 19:45 UTC, ulmononian commented
now seeing this when trying to compile S2SWA (it finds MPI_C, but i'm not sure it is finding these correctly:

```
-- Found MPI_C: /apps/spack-2024-12/linux-rocky9-x86_64/oneapi-2023.2.0/intel-oneapi-mpi-2021.13.1-66y2dsdqzran6wjlk7oglxlr5za3dbh6/mpi/2021.13/lib/libmpifort.so (found version "3.1")
-- Found MPI_CXX: /apps/spack-2024-12/linux-rocky9-x86_64/oneapi-2023.2.0/intel-oneapi-mpi-2021.13.1-66y2dsdqzran6wjlk7oglxlr5za3dbh6/mpi/2021.13/lib/libmpicxx.so (found version "3.1")
-- Found MPI_Fortran: /apps/spack-2024-12/linux-rocky9-x86_64/oneapi-2023.2.0/intel-oneapi-mpi-2021.13.1-66y2dsdqzran6wjlk7oglxlr5za3dbh6/mpi/2021.13/lib/libmpifort.so (found version "3.1")
```

cmake fails now in 

```
Found Python: /contrib/spack-stack/envs/1.6.0/ue-intel-2023.2.0/install/intel/2021.10.0/python-3.10.13-vbszmcu/bin/python3.10
-- Compile stochastic_physics with 64-bit precision to match CCPP slow physics.
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_GFS_v17_coupled_p8,FV3_GFS_v17_coupled_p8_ugwpv ...
CMake Error at FV3/ccpp/CMakeLists.txt:40 (message):
  An error occured while running ccpp_prebuild.py, check
  /collab1/data/Cameron.Book/port_wm/build/cpl/FV3/ccpp/ccpp_prebuild.{out,err}


-- Configuring incomplete, errors occurred!
```

seems like something weird is going on here...

2025-01-27 19:56 UTC, climbfuji commented
From the log:
```
  An error occured while running ccpp_prebuild.py, check
  /collab1/data/Cameron.Book/port_wm/build/cpl/FV3/ccpp/ccpp_prebuild.{out,err}
```

2025-01-27 20:07 UTC, ulmononian commented
> From the log:
> 
> ```
>   An error occured while running ccpp_prebuild.py, check
>   /collab1/data/Cameron.Book/port_wm/build/cpl/FV3/ccpp/ccpp_prebuild.{out,err}
> ```

lol, i was wondering why it was trying to parse a suite that did not exist / was not being used in my cmake commdand. classic case of typo (i had entered `FV3_GFS_v17_coupled_p8_ugwpv` instead of `V3_GFS_v17_coupled_p8_ugwpv1`).

now just back to the same MOM6 issue: 

```
CMake Error at MOM6-interface/CMakeLists.txt:35 (add_library):
  Cannot find source file:

    MOM6/src/diagnostics/MOM_diagnose_MLD.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at MOM6-interface/CMakeLists.txt:55 (add_library):
  Cannot find source file:

    MOM6/config_src/drivers/unit_tests/test_MOM_remapping.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at MOM6-interface/CMakeLists.txt:35 (add_library):
  No SOURCES given to target: mom6_obj


CMake Error at MOM6-interface/CMakeLists.txt:55 (add_library):
  No SOURCES given to target: mom6_nuopc_obj


CMake Error at MOM6-interface/CMakeLists.txt:75 (add_library):
  No SOURCES given to target: mom6


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

2025-01-27 20:09 UTC, BrianCurtis-NOAA commented
have you recursed all submodules in your git clone?

2025-01-27 20:20 UTC, ulmononian commented
> have you recursed all submodules in your git clone?

seems like my recent pull from develop was not successful and messed up the MOM6 src...

cloned fresh and it gets past this. thanks @BrianCurtis-NOAA.

2025-01-27 20:26 UTC, ulmononian commented
using `ifx`, `make` fails in ww3:

```
[ 42%] Building Fortran object WW3/model/src/CMakeFiles/ww3_lib.dir/w3wavemd.F90.o
/collab1/data/Cameron.Book/0127/WW3/model/src/w3wavemd.F90(414): remark #6536: All symbols from this module are already visible due to another USE; the ONLY clause will have no effect. Rename clauses, if any, will be honored.   [W3ODATMD]
    USE W3ODATMD
--------^
/collab1/data/Cameron.Book/0127/WW3/model/src/w3wavemd.F90(458): remark #6536: All symbols from this module are already visible due to another USE; the ONLY clause will have no effect. Rename clauses, if any, will be honored.   [W3TIMEMD]
    USE W3TIMEMD
--------^
[ 42%] Building Fortran object WW3/model/src/CMakeFiles/ww3_lib.dir/wmwavemd.F90.o
[ 42%] Building Fortran object WW3/model/src/CMakeFiles/ww3_lib.dir/wav_comp_nuopc.F90.o
[ 43%] Linking Fortran static library ../../../lib/libww3.a
[ 43%] Built target ww3_lib
make: *** [Makefile:136: all] Error 2
```

2025-01-27 20:29 UTC, BrianCurtis-NOAA commented
Those are remarks and I don't believe cause the make to fail. Look earlier for errors.

2025-01-27 23:19 UTC, ulmononian commented
> Those are remarks and I don't believe cause the make to fail. Look earlier for errors.

you're right. it was some issue in cmeps. this was with ifx...which i'm going to bypass for 1.6.0 testing for now.

2025-01-27 23:23 UTC, ulmononian commented
update on the `MPI_C issue`: `ATM` and `S2SWA` compile successfully using spack-stack/1.6.0 and intel classic compilers (icc/icpc/ifort) with the inclusion of the following envars set in the `ufs_ursa.intel.lua` modulefile:

```
setenv("CC", "icc")
setenv("CXX", "icpc")
setenv("FC", "ifort")

setenv("CC", "mpiicc")
setenv("CXX", "mpiicpc")
setenv("FC", "mpiifort")

setenv("I_MPI_CC", "icc")
setenv("I_MPI_CXX", "icpc")
setenv("I_MPI_F90", "ifort"
```

successful compile of ATM i mentioned earlier were w/ oneapi compilers (icx/icpx/ifx) & spack-stack/1.6.0. trying the combination of (icx/icpx/ifort) continued to lead to the missing MPI_C issue.

2025-01-27 23:26 UTC, DeniseWorthen commented
> > Those are remarks and I don't believe cause the make to fail. Look earlier for errors.
> 
> you're right. it was some issue in cmeps. this was with ifx...which i'm going to bypass for 1.6.0 testing for now.

What was "the issue with cmeps"?

2025-01-27 23:30 UTC, ulmononian commented
> > > Those are remarks and I don't believe cause the make to fail. Look earlier for errors.
> > 
> > 
> > you're right. it was some issue in cmeps. this was with ifx...which i'm going to bypass for 1.6.0 testing for now.
> 
> What was "the issue with cmeps"?

```
                                                                                                                                                         63,1          12%
/collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90(37): error #6580: Name in only-list does not exist or is not accessible.   [MPI_ERROR_STRING]
    use mpi , only : MPI_ERROR_STRING, MPI_MAX_ERROR_STRING, MPI_SUCCESS
---------------------^
/collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90(54): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [MPI_MAX_ERROR_STRING]
    character(MPI_MAX_ERROR_STRING) :: lstring
--------------^
/collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90(37): error #6580: Name in only-list does not exist or is not accessible.   [MPI_MAX_ERROR_STRING]
    use mpi , only : MPI_ERROR_STRING, MPI_MAX_ERROR_STRING, MPI_SUCCESS
---------------------------------------^
/collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90(37): error #6580: Name in only-list does not exist or is not accessible.   [MPI_SUCCESS]
    use mpi , only : MPI_ERROR_STRING, MPI_MAX_ERROR_STRING, MPI_SUCCESS
-------------------------------------------------------------^
/collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90(54): error #6404: This name does not have a type, and must have an explicit type.   [MPI_MAX_ERROR_STRING]
    character(MPI_MAX_ERROR_STRING) :: lstring
--------------^
compilation aborted for /collab1/data/Cameron.Book/0127/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90 (code 1)
make[2]: *** [CMEPS-interface/CMakeFiles/cmeps.dir/build.make:569: CMEPS-interface/CMakeFiles/cmeps.dir/CMEPS/mediator/med_utils_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2455: CMEPS-interface/CMakeFiles/cmeps.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

idk but i was wondering if it is an issue with the ifx compiler configuration/settings/vars between sys-install/spack-stack/cmake/cmeps. i know @DusanJovic-NOAA was able to compile on other machines w/ LLVM + ifx, so maybe i am not setting something properly.

2025-01-27 23:55 UTC, DeniseWorthen commented
@ulmononian Actually, this is the exact error we get on Derecho if we try to compile w/ GNU.

2025-01-28 00:08 UTC, ulmononian commented
> @ulmononian Actually, this is the exact error we get on Derecho if we try to compile w/ GNU.

very odd. something is up!

2025-01-28 01:57 UTC, ulmononian commented
successful run of `cpld_control_p8` here: `/collab1/data/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3714619`

spack-stack/1.6.0 w/ intel classic compilers

will run full intel rt suite next

2025-01-28 18:05 UTC, jkbk2004 commented
@ulmononian @FernandoAndrade-NOAA should we start baseline migration to Ursa space?

2025-01-28 18:43 UTC, ulmononian commented
> @ulmononian @FernandoAndrade-NOAA should we start baseline migration to Ursa space?

@jkbk2004 we still do not have an epic role space there. rdhpcs has indicated that we will get a role account/space there once Oso (the actual TDS) comes online.

@RaghuReddy-NOAA any timeline on oso and/or role account issuance by chance?

2025-02-03 19:44 UTC, ulmononian commented
all but four intel tests pass on ursa. the failing tests were:

`cpld_control_p8_lnd_intel`, `control_p8_atmlnd_intel`, `control_p8_atmlnd_debug_intel`, `regional_atmaq_debug_intel`.

all failed due to time limit, so will increase and test again.

2025-02-03 20:19 UTC, DeniseWorthen commented
These tests seem to be timing out on multiple platforms. Regression tests should always run in less than 30mins. If the tests are timing out, then the fhmax and/or task resources should be increased, not the wall clock time.

@uturuncoglu Could you take a look at these new tests?

2025-02-03 20:32 UTC, uturuncoglu commented
@DeniseWorthen I have no access to that platform. If you want I could run cpld_control_p8_lnd_intel vs cpld_control_p8_intel and check the timings to see the extra overhead from land component.

2025-02-03 20:36 UTC, DeniseWorthen commented
@uturuncoglu Sorry for not being clear. It seems we're having this same issue on other platforms. I brought it up here because extending wall clock is not the solution to this sort of problem. 

Could you maybe derecho and/or hercules? Are they running close to wall-clock there?

2025-02-03 20:45 UTC, uturuncoglu commented
@DeniseWorthen Okay. Let me check on Hercules. I'll update you soon.

2025-02-03 20:49 UTC, uturuncoglu commented
@DeniseWorthen If I remember correctly. I did couple of test before and reducing the output interval of the land component was improving its performance. So, here is the result of my previous tests that I did for land DA,

```
ESMF_Profile.summary.r01 - 44/47/42 = ~ 44 sec
  original configuration
  12 hours of simulation 
  144+144 core (mediator is on first 144)

ESMF_Profile.summary.r02 - 35/30/30 = ~ 31 sec (%25 gain rt r01)
  change restart_n (in ufs.configure) from 1 to 12 since mediator/cdeps was spending time in outputting restart files. BTW, it will only write single restart at the end of the simulation.

ESMF_Profile.summary.r03 - 16/11/15 = ~ 14 sec (%50 gain rt r02)
  change output_freq (in ufs.configure) from 3600 (hourly) to 86400 (daily). So, land component will not have any output.

ESMF_Profile.summary.r04 - 17/17/15 = ~ 16 sec (no improvement)
  24+24 core for atm and land (mediator on all 48)
  Land C96 layout = 2:2
```

Of course this is for the configuration coupled with DATM. I'll do a similar test with the `control_p8_atmlnd_intel` and `cpld_control_p8_lnd_intel`.

2025-02-04 04:49 UTC, uturuncoglu commented
@DeniseWorthen I run the control_p8 with and without land component. The standalone atmosphere case (original control_p8) took 223 sec in total and one with the external land component took 286 sec. Both flactuates little bit but not too much due to load in the system. In the land coupled case, FV3 writing every hour but this is not the case for standalone. So, probably I/O plays role in here in terms of timing difference. In any case, the run finish around 5 min. So, I am not sure why it's timing out. Maybe comparing files is taking time. Not sure. Anyway, I think the best way to speed up the case (if you want more performance) is to use same output interval with control_p8. So, I did following modification in the test.

```
diff --git a/tests/parm/ufs.configure.atm_lnd.IN b/tests/parm/ufs.configure.atm_lnd.IN
index c00fd9ea..b3c3c1d8 100644
--- a/tests/parm/ufs.configure.atm_lnd.IN
+++ b/tests/parm/ufs.configure.atm_lnd.IN
@@ -69,7 +69,7 @@ LND_attributes::
   surface_evap_resistance_option = 1 # not used, it is fixed to 4 in sfc_noahmp_drv.F90
   glacier_option = 1
   surface_thermal_roughness_option = 2
-  output_freq = 3600
+  output_freq = 21600
   restart_freq = -1
   calc_snet = @[CALC_SNET]
   initial_albedo = @[initial_albedo]
```

```
diff --git a/tests/tests/control_p8_atmlnd b/tests/tests/control_p8_atmlnd
index e9bc04d2..a7714b01 100644
--- a/tests/tests/control_p8_atmlnd
+++ b/tests/tests/control_p8_atmlnd
@@ -127,7 +127,7 @@ export precip_partition_option=4
 export initial_albedo=0.2
 export WRITE_DOPOST=.false.
 export OUTPUT_GRID=cubed_sphere_grid
-export OUTPUT_FH="1 -1"
+export OUTPUT_FH="0 12 24"
 if [[ "$ATMRES" = "$LNDRES" ]]; then
   export lnd_input_dir="INPUT/"
   export mosaic_file="INPUT/${LNDRES}_mosaic.nc"
```

So, this minimize the I/O footprint of the `control_p8_atmlnd` and also ensure the required files are generated. I am not sure the changes in `ufs.configure.atm_lnd.IN` affect other tests at this point. I also try to disable mediator restart and history for this run and it finished in 238 sec. which is very close to standalone atmosphere. At this point I am not seeing any performance issue at least in this case. Anyway, I could also do same for `cpld_control_p8` and `cpld_control_p8_lnd`. Let me know what you think.

2025-02-04 17:43 UTC, ulmononian commented
thanks for this testing @uturuncoglu! @DeniseWorthen @jkbk2004 preference here for these lands tests on ursa?

2025-02-04 18:31 UTC, ulmononian commented
just to note: `control_p8_atmlnd_intel` passes if i change `TPN` to 128 instead if 192 in the test file (forcing run job to use 3 nodes on ursa). @uturuncoglu @DeniseWorthen

2025-02-04 18:34 UTC, BrianCurtis-NOAA commented
> just to note: `control_p8_atmlnd_intel` passes if i change `TPN` to 128 instead if 192 in the test file (forcing run job to use 3 nodes on ursa). @uturuncoglu @DeniseWorthen

is there some memory issue? Does a TPN of 192 make sense for Ursa's hardware?

2025-02-04 18:34 UTC, DeniseWorthen commented
@uturuncoglu Thanks for your testing. I don't see there should be any issue w/ that sort of timing (~300s) so I don't think there is any cause to change your tests.

2025-02-04 18:36 UTC, uturuncoglu commented
@DeniseWorthen Okay. Let me know if you need help. We could make them more efficient in the future. I am not sure at this point who will maintain land coupling related issues since we are in a process of finalizing JTTI project.

2025-02-04 18:43 UTC, ulmononian commented
> > just to note: `control_p8_atmlnd_intel` passes if i change `TPN` to 128 instead if 192 in the test file (forcing run job to use 3 nodes on ursa). @uturuncoglu @DeniseWorthen
> 
> is there some memory issue? Does a TPN of 192 make sense for Ursa's hardware?
 @BrianCurtis-NOAA `scontrol show node` on `nfe91` (the available ursa preTDS log-in node) shows CPUTot=192, so i went with that. it works for most tests, except the four i reported earlier. dropping to 128 for these specific tests to allocate more nodes is just a suggested fix (as done w/ gaea c6).

2025-02-04 22:03 UTC, ulmononian commented
@BrianCurtis-NOAA moving to 128 TPN resolves the issues for all the `lnd` RTs, but not for the `regional_atmaq_debug` test. it is only getting like 0.2 hours into the fcst when i try either TPN=96 (4 nodes) or TPN=128 (3 nodes). i am seeing this in the `err` file, but it is only a warning so i assume it is not causing the slowness

```
175: WARNING: O3TOTCOL:Requested date is beyond available data on OMI file:  <0:00:00   Jan. 8, 2016
```

wallclock time is still at 30mins. times out every time. @chan-hoo mentioned you maintain this test, so wanted to check if you had any insight.

2025-02-10 21:02 UTC, ulmononian commented
just a note (in case anyone knows a fix) that rocoto will hang indefinitely when running rt.sh for multiple tests (i.e., `./rt.sh -a <account> -k -r -c -l rt.conf`) if _any_ tests are failing (in compile/run). it will not exit and just keeps showing: `rt_utils.sh: Running one iteration of rocotorun and rocotostat...`. if ALL tests pass, rocoto will succesfully exit and save the regression test logs. @RatkoVasic-NOAA reported something similar for hera.

2025-02-10 21:11 UTC, ulmononian commented
compile failures in the following using `gcc/12.4.0` & `openmpi/4.1.6`: `compile_datm_cdeps, compile_s2s,  compile_s2swa, compile_s2swa_debug compile_s2sw_pdlib, compile_s2sw_pdlib_debug`. the error for each seems to be the same, i.e.:

```
/collab1/data/Cameron.Book/test_wm_gnu/CMEPS-interface/CMEPS/mediator/med_utils_mod.F90:37:9:

   37 |     use mpi , only : MPI_ERROR_STRING, MPI_MAX_ERROR_STRING, MPI_SUCCESS
      |         1
Fatal Error: Cannot open module file 'mpi.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [CMEPS-interface/CMakeFiles/cmeps.dir/build.make:569: CMEPS-interface/CMakeFiles/cmeps.dir/CMEPS/mediator/med_utils_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

all other gnu configurations & tests turned on for both hera/hercules succeed on ursa, i.e.:

```
[Cameron.Book@nfe91 tests]$ rocotostat -d rocoto_workflow.db -w rocoto_workflow.xml
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
197001010000         compile_atm_gnu                      503697           SUCCEEDED                   0         1         168.0
197001010000         control_c48_gnu                      503708           SUCCEEDED                   0         1         359.0
197001010000      control_stochy_gnu                      503709           SUCCEEDED                   0         1         125.0
197001010000         control_ras_gnu                      503710           SUCCEEDED                   0         1         196.0
197001010000          control_p8_gnu                      503711           SUCCEEDED                   0         1         197.0
197001010000    control_p8_ugwpv1_gnu                      503712           SUCCEEDED                   0         1         192.0
197001010000       control_flake_gnu                      503713           SUCCEEDED                   0         1         250.0
197001010000        compile_rrfs_gnu                      503698           SUCCEEDED                   0         1         166.0
197001010000         rap_control_gnu                      503714           SUCCEEDED                   0         1         384.0
197001010000         rap_sfcdiff_gnu                      503715           SUCCEEDED                   0         1         384.0
197001010000        hrrr_control_gnu                      503716           SUCCEEDED                   0         1         211.0
197001010000         rrfs_v1beta_gnu                      503717           SUCCEEDED                   0         1         382.0
197001010000      compile_csawmg_gnu                      503699           SUCCEEDED                   0         1         158.0
197001010000      control_csawmg_gnu                      503718           SUCCEEDED                   0         1         352.0
197001010000    compile_atm_dyn32_debug_gnu                      503700           SUCCEEDED                   0         1         277.0
197001010000    control_diag_debug_gnu                      503719           SUCCEEDED                   0         1          91.0
197001010000      regional_debug_gnu                      503720           SUCCEEDED                   0         1         336.0
197001010000    rap_control_debug_gnu                      503721           SUCCEEDED                   0         1         113.0
197001010000    hrrr_control_debug_gnu                      503722           SUCCEEDED                   0         1         109.0
197001010000       hrrr_gf_debug_gnu                      503723           SUCCEEDED                   0         1         112.0
197001010000       hrrr_c3_debug_gnu                      503724           SUCCEEDED                   0         1         116.0
197001010000      rap_diag_debug_gnu                      503725           SUCCEEDED                   0         1         128.0
197001010000    rap_noah_sfcdiff_cires_ugwp_debug_gnu                      503726           SUCCEEDED                   0         1         171.0
197001010000    rap_progcld_thompson_debug_gnu                      503727           SUCCEEDED                   0         1         111.0
197001010000    rrfs_v1beta_debug_gnu                      503728           SUCCEEDED                   0         1         114.0
197001010000    control_ras_debug_gnu                      503729           SUCCEEDED                   0         1          70.0
197001010000    control_stochy_debug_gnu                      503730           SUCCEEDED                   0         1          75.0
197001010000    control_debug_p8_gnu                      503731           SUCCEEDED                   0         1          93.0
197001010000     rap_flake_debug_gnu                      503732           SUCCEEDED                   0         1         113.0
197001010000    rap_clm_lake_debug_gnu                      503733           SUCCEEDED                   0         1         112.0
197001010000    gnv1_c96_no_nest_debug_gnu                      503734           SUCCEEDED                   0         1         188.0
197001010000    compile_wam_debug_gnu                      503701           SUCCEEDED                   0         1         100.0
197001010000    compile_atm_debug_dyn32_gnu                      503702           SUCCEEDED                   0         1         167.0
197001010000    control_csawmg_debug_gnu                      503735           SUCCEEDED                   0         1         117.0
197001010000    compile_rrfs_dyn32_phy32_gnu                      503703           SUCCEEDED                   0         1         164.0
197001010000    rap_control_dyn32_phy32_gnu                      503736           SUCCEEDED                   0         1         359.0
197001010000    hrrr_control_dyn32_phy32_gnu                      503737           SUCCEEDED                   0         1         197.0
197001010000    conus13km_control_gnu                      503738           SUCCEEDED                   0         1         149.0
197001010000    conus13km_restart_mismatch_gnu                      503745           SUCCEEDED                   0         1         101.0
197001010000    compile_atm_dyn64_phy32_gnu                      503704           SUCCEEDED                   0         1         383.0
197001010000    rap_control_dyn64_phy32_gnu                      503739           SUCCEEDED                   0         1         228.0
197001010000    compile_atm_dyn32_phy32_debug_gnu                      503705           SUCCEEDED                   0         1         278.0
197001010000    rap_control_debug_dyn32_phy32_gnu                      503740           SUCCEEDED                   0         1         111.0
197001010000    hrrr_control_debug_dyn32_phy32_gnu                      503741           SUCCEEDED                   0         1         111.0
197001010000     conus13km_debug_gnu                      503742           SUCCEEDED                   0         1         294.0
197001010000    conus13km_radar_tten_debug_gnu                      503743           SUCCEEDED                   0         1         289.0
197001010000    compile_atm_dyn64_phy32_debug_gnu                      503706           SUCCEEDED                   0         1         276.0
197001010000    rap_control_dyn64_phy32_debug_gnu                      503744           SUCCEEDED                   0         1         114.0
```

2025-02-10 21:54 UTC, ulmononian commented
the error i reported above seems to be resolved if i include `setenv("FC", "mpifort")` in the `ufs_ursa.gnu.lua` file (replacing gfortran with mpifort to address the mpi.mod problem). however, if i include `setenv("CC", "mpicc")` or `setenv("CXX", "mpic++")`, CMake fails. so the `ufs_ursa.gnu.lua` file contains: 

```
setenv("MPI_CC", "mpicc")
setenv("MPI_CXX", "mpic++")
setenv("MPI_FC", "mpifort")

setenv("FC", "mpifort")
```

2025-02-10 22:38 UTC, ulmononian commented
all compile jobs pass with `FC=mpifort` added to the gnu modulefile. associated tests pass, w/ the exception of `cpld_control_p8_gnu` and `cpld_debug_p8_gnu` (both of these tests are turned OFF for hercules/hera).

```
[Cameron.Book@nfe91 tests]$ rocotostat -d rocoto_workflow.db -w rocoto_workflow.xml
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
197001010000       compile_s2swa_gnu                      503767           SUCCEEDED                   0         1         634.0
197001010000     cpld_control_p8_gnu                      503783                DEAD                   1         3          47.0
197001010000         compile_s2s_gnu                      503768           SUCCEEDED                   0         1         610.0
197001010000    cpld_control_nowave_noaero_p8_gnu                      503776           SUCCEEDED                   0         1         429.0
197001010000    compile_s2swa_debug_gnu                      503769           SUCCEEDED                   0         1         137.0
197001010000       cpld_debug_p8_gnu                      503779                DEAD                   1         3          74.0
197001010000    compile_s2sw_pdlib_gnu                      503770           SUCCEEDED                   0         1         636.0
197001010000    cpld_control_pdlib_p8_gnu                      503780           SUCCEEDED                   0         1         625.0
197001010000    compile_s2sw_pdlib_debug_gnu                      503771           SUCCEEDED                   0         1         127.0
197001010000    cpld_debug_pdlib_p8_gnu                      503774           SUCCEEDED                   0         1         506.0
197001010000    compile_datm_cdeps_gnu                      503772           SUCCEEDED                   0         1         607.0
197001010000    datm_cdeps_control_cfsr_gnu                      503777           SUCCEEDED                   0         1         110.0
```

2025-03-18 18:51 UTC, ulmononian commented
spack-stack/1.9.1 installed on Oso. testing is underway. to load the intel stack:

```
module use /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/modulefiles/Core
module load  stack-oneapi/2024.2.1
module load stack-intel-oneapi-mpi/2021.13
```

and the gcc/openmpi stack:

```
module use /contrib/spack-stack/spack-stack-1.9.1/envs/ue-gcc-11.4.1/install/modulefiles/Core
module load stack-gcc/11.4.1
module load stack-openmpi/4.1.6
```

2025-03-19 20:47 UTC, climbfuji commented on cmake/Intel.cmake
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -qno-opt-dynamic-align -fp-model precise")
We shouldn' commit this to the repo. Pleae have a look at https://github.com/ufs-community/ufs-weather-model/pull/2504 for how this should be done.

2025-03-19 20:49 UTC, ulmononian commented on cmake/Intel.cmake
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -qno-opt-dynamic-align -fp-model precise")
@climbfuji totally agree -- was mostly committing here so i did not forget. wanted to sync up w/ you/dusan/jong/ratko about how to sync up the 1.9.1 WM PR (moving to mixed compilers), your PR here, and the ursa PR, as ratko/my PRs will need your changes.

2025-03-19 20:52 UTC, climbfuji commented on cmake/Intel.cmake
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -qno-opt-dynamic-align -fp-model precise")
Good luck staying on top of all these moving pieces ;-) but sounds good

2025-03-19 21:05 UTC, ulmononian commented
`-DATM` will not compile on ursa w/ spack-stack/1.9.1. (INTEL). error is:

```
[100%] Linking Fortran executable ufs_model
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort: command line warning #10148: option '-fiopenmp' not supported
ld: /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/curl-8.10.1-l525x4o/lib/libcurl.so.4: undefined reference to `SSL_get0_group_name@OPENSSL_3.2.0'
make[2]: *** [CMakeFiles/ufs_model.dir/build.make:127: ufs_model] Error 1
make[1]: *** [CMakeFiles/Makefile2:310: CMakeFiles/ufs_model.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

2025-03-19 21:06 UTC, ulmononian commented
`-DATM` compiles successfully on ursa w/ spack-stack/1.9.1 (GNU).

2025-03-20 00:45 UTC, climbfuji commented
> `-DATM` compiles successfully on ursa w/ spack-stack/1.9.1 (GNU).

That hints to the gcc backend for Intel not being set up correctly in the environment/meta-modules/...

2025-03-20 13:30 UTC, RaghuReddy-NOAA commented
> > `-DATM` compiles successfully on ursa w/ spack-stack/1.9.1 (GNU).
> 
> That hints to the gcc backend for Intel not being set up correctly in the environment/meta-modules/...

Not sure if this information is useful, but for some reason all other references to the OPENSSL library are with OPENSSL_3.0.0 and this is the only with a reference to OPENSSL_3.2..0

```
ofe01.% nm /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/curl-8.10.1-l525x4o/lib/libcurl.so.4 | grep -i SSL_get
000000000008d910 t Curl_ssl_get_channel_binding
000000000008f100 t Curl_ssl_get_internals
000000000008cea0 t Curl_ssl_getsessionid
                 U SSL_get0_alpn_selected@OPENSSL_3.0.0
                 U SSL_get0_group_name@OPENSSL_3.2.0
                 U SSL_get0_verified_chain@OPENSSL_3.0.0
                 U SSL_get1_peer_certificate@OPENSSL_3.0.0
                 U SSL_get_certificate@OPENSSL_3.0.0
                 U SSL_get_current_cipher@OPENSSL_3.0.0
                 U SSL_get_error@OPENSSL_3.0.0
                 U SSL_get_ex_data@OPENSSL_3.0.0
                 U SSL_get_peer_cert_chain@OPENSSL_3.0.0
                 U SSL_get_peer_signature_type_nid@OPENSSL_3.0.0
                 U SSL_get_privatekey@OPENSSL_3.0.0
                 U SSL_get_shutdown@OPENSSL_3.0.0
                 U SSL_get_verify_result@OPENSSL_3.0.0
                 U SSL_get_version@OPENSSL_3.0.0
000000000008fb50 t multissl_get_internals
000000000008b340 t ossl_get_channel_binding
000000000008ab20 t ossl_get_internals
ofe01.%
```

2025-03-20 17:46 UTC, ulmononian commented
@climbfuji @RaghuReddy-NOAA looks like `openssl-3.4.0` was built w/ this spack-stack, but curl is pointing to `3.2.0` or `3.0.0 (as raghu mentioned). spack-stack doesn't have a modulefile for `openssl`. with spack-stack/1.9.1 loaded, this shows for `openssl`:

```
[Cameron.Book@ofe01 ue-oneapi-2024.2.1]$ openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
[Cameron.Book@ofe01 ue-oneapi-2024.2.1]$ openssl version -a
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
built on: Tue Sep  3 00:00:00 2024 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DREDHAT_FIPS_VERSION="\"3.0.7-d9e98a279cbb408d\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-3"
MODULESDIR: "/usr/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7efa320b078bffff:0x415fdef1bf97a9
[Cameron.Book@ofe01 ue-oneapi-2024.2.1]$ which openssl
/usr/bin/openssl
```

2025-03-20 21:04 UTC, ulmononian commented
re-building a test stack w/ system-installed `openssl`. will re-test ATM compile w/ this and report back.

2025-03-31 18:16 UTC, ulmononian commented
1.9.1 intel stack was re-built w/ system openssl, as well as with external qt/ecflow. 

pulled in @lipan-NOAA's changes for gocart that were merged into @RatkoVasic-NOAA's #2650.

running intel test suite today. so far, the ATM model compiles fine.

2025-03-31 18:26 UTC, ulmononian commented
also brought in @AlexanderRichert-NOAA's PR#69 to CMakeModules (via @RatkoVasic-NOAA's ss-191 branch).

2025-03-31 18:41 UTC, ulmononian commented
`s2swa` fails to compile (aborts at 90%) after building `ww3_lib`. perusing the `err` file, i see:

```/tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test2471/GOCART/ESMF/UFS/Aerosol_Cap.F90(171): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [IMPORTSTATE]
    call NUOPC_LogIntro(name, rName, verbosity, rc=rc)
---------^

wondering if a change introduced to `GOCART/ESMF/UFS/Aerosol_Cap.F90` is not working for some reason? @lipan-NOAA  any idea?

2025-03-31 18:46 UTC, ulmononian commented
`s2sw` compiles ok, so thinking it must be an issue with GOCART/aerosols.

2025-03-31 19:12 UTC, lipan-NOAA commented
@ulmononian I will check and get back to you as soon as possible

2025-03-31 22:07 UTC, rickgrubin-noaa commented
> `s2swa` fails to compile (aborts at 90%) after building `ww3_lib`. perusing the `err` file, i see:
> 
> ```
> /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test2471/GOCART/ESMF/UFS/Aerosol_Cap.F90(171): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [IMPORTSTATE]
>     call NUOPC_LogIntro(name, rName, verbosity, rc=rc)
> ---------^
> /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test2471/GOCART/ESMF/UFS/Aerosol_Cap.F90(171): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [EXPORTSTATE]
>     call NUOPC_LogIntro(name, rName, verbosity, rc=rc)
> ---------^
> compilation aborted for /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test2471/GOCART/ESMF/UFS/Aerosol_Cap.F90 (code 1)
> 
> make[2]: *** [GOCART/ESMF/UFS/CMakeFiles/UFS_Aerosols.dir/build.make:75: GOCART/ESMF/UFS/CMakeFiles/UFS_Aerosols.dir/Aerosol_Cap.F90.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1470: GOCART/ESMF/UFS/CMakeFiles/UFS_Aerosols.dir/all] Error 2
> ```
> 
> wondering if a change introduced to `GOCART/ESMF/UFS/Aerosol_Cap.F90` is not working for some reason? @lipan-NOAA any idea?

Identical errors for `s2swa` and `s2swal` on **gaea-c5** / **gaea-c6** with `Intel` "classic" compilers (module `intel/2023.2.0`, compiler versions `v2021.10.0`) -- `oneAPI` compilers not available.

2025-03-31 22:09 UTC, ulmononian commented
@rickgrubin-noaa do any of the configs. w/ aerosols pass on c5/c6? i am seeing all aerosol configurations fail to compile on ursa:

```
s2swa_32bit_intel
s2swa_32bit_pdlib_debug_intel
s2swa_32bit_pdlib_intel
s2swa_32bit_pdlib_sfs_intel
s2swa_debug_intel
s2swa_faster_intel
s2swa_intel
s2swal_intel
```

2025-04-01 02:39 UTC, lipan-NOAA commented
https://github.com/RatkoVasic-NOAA/ufs-weather-model/pull/6

2025-04-01 04:58 UTC, RatkoVasic-NOAA commented
> [RatkoVasic-NOAA#6](https://github.com/RatkoVasic-NOAA/ufs-weather-model/pull/6)

Thanks @lipan-NOAA for quick response. We'll check it as soon as possible.

2025-04-01 12:33 UTC, rickgrubin-noaa commented
> @rickgrubin-noaa do any of the configs. w/ aerosols pass on c5/c6? i am seeing all aerosol configurations fail to compile on ursa:
> 
> ```
> s2swa_32bit_intel
> s2swa_32bit_pdlib_debug_intel
> s2swa_32bit_pdlib_intel
> s2swa_32bit_pdlib_sfs_intel
> s2swa_debug_intel
> s2swa_faster_intel
> s2swa_intel
> s2swal_intel
> ```

@ulmononian  --  failure in each of those tests.

2025-04-01 13:28 UTC, lipan-NOAA commented
nohup: ignoring input
******Regression Testing Script Started******
**alogin01**
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.
**Machine: acorn**
Account: GEFS-DEV
rt.sh: Setting up WCOSS2/Acorn
Linking /lfs/h2/emc/ptmp/li.pan/FV3_RT/rt_3759319 to /lfs/h1/emc/physics/noscrub/li.pan/ufs-weather-model/tests/run_dir
Run regression test in: /lfs/h2/emc/ptmp/li.pan/FV3_RT/rt_3759319
rt.sh: Checking & Updating test configuration...
No update needed to rt.conf
rt.sh: Running compile s2swa_intel
rt.sh: Compile s2swa_intel completed.
rt.sh: Running test cpld_control_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_control_p8_intel completed.
rt.sh: Running test cpld_control_p8.v2.sfc_intel using compile s2swa_intel
rt.sh: Run with test cpld_control_p8.v2.sfc_intel completed.
rt.sh: Running test cpld_restart_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_restart_p8_intel completed.
rt.sh: Running test cpld_control_qr_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_control_qr_p8_intel completed.
rt.sh: Running test cpld_restart_qr_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_restart_qr_p8_intel completed.
rt.sh: Running test cpld_2threads_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_2threads_p8_intel completed.
rt.sh: Running test cpld_decomp_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_decomp_p8_intel completed.
rt.sh: Running test cpld_mpi_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_mpi_p8_intel completed.
rt.sh: Running test cpld_control_ciceC_p8_intel using compile s2swa_intel
rt.sh: Run with test cpld_control_ciceC_p8_intel completed.
rt.sh: Running compile s2swal_intel
rt.sh: Compile s2swal_intel completed.
rt.sh: Running test cpld_control_p8_lnd_intel using compile s2swal_intel
rt.sh: Run with test cpld_control_p8_lnd_intel completed.
rt.sh: Running test cpld_restart_p8_lnd_intel using compile s2swal_intel
rt.sh: Run with test cpld_restart_p8_lnd_intel completed.
rt.sh: Generating Regression Testing Log...

2025-04-01 13:53 UTC, bbakernoaa commented
@rickgrubin-noaa @RatkoVasic-NOAA @lipan-NOAA 

I believe that we may have to update the[ gocart control files](https://github.com/ulmononian/ufs-weather-model/tree/feature/ursa_port/tests/parm/gocart) with the latest update as well.  [The PR #](https://github.com/GEOS-ESM/GOCART/pull/305) has some changes to the inputs that are required.  

See the changes to the RC files here: https://github.com/GEOS-ESM/GOCART/pull/305/files#diff-46a47a66e695710c466d8a292a745b3a239bdd6adc9003a430a3061aa0ce22fe

2025-04-01 23:06 UTC, ulmononian commented
@lipan-NOAA @RatkoVasic-NOAA merging in @lipan-NOAA's PR#6 resolved the issue. `cpld_control_p8` now compiles and the run completes succesfully! thank you @lipan-NOAA for this very quick fix! will re-run the full suite.

one question @lipan-NOAA, can i ask why you commented out

```
#add_library(ESMF::ESMF ALIAS esmf)
```

in https://github.com/ufs-community/ufs-weather-model/blob/ecf0a397333709277ead6290ad0cb4598f6b1817/CMakeLists.txt#L159?

2025-04-01 23:16 UTC, lipan-NOAA commented
Configuration error message points to this line

2025-04-02 15:35 UTC, ulmononian commented
w/ @lipan-NOAA's changes, all configurations compile on ursa. there are only three failing intel tests:

```
fail_test_cpld_debug_gfsv17_intel		
fail_test_cpld_debug_p8_intel
fail_test_hafs_global_multiple_4nests_atm_intel
```

all gnu compiles/tests pass 100%.

2025-04-02 15:43 UTC, DeniseWorthen commented
@ulmononian Can I confirm that when you are testing the cpld+GNU on Ursa, you are not actually enabling the tests which have been disabled? That is, have you added +ursa to all the cpld+GNU tests and tried to run?

2025-04-02 15:47 UTC, ulmononian commented
for `hafs_global_multiple_4nests_atm_intel`, the `out` file shows:

```
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
  0:  Bad temperatures (dimension 1):            0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            1           0           0
  0:  Bad temperatures (dimension 2):            0           0           0
360:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
  0:            0           0           0           0           0           0
360:   0.0000000E+00
  0:            0           0           0           0           0           0
  0:            0           0           0           1           0
  0:
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
  0:
480:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
480:   0.0000000E+00
```

from `err`:  `0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1`


for `cpld_debug_gfsv17_intel`, `out` ends at:  `150:  mesh file for mom6 domain is mesh.mx100.nc` and `err` shows: `200: forrtl: error (65): floating invalid`.

for `cpld_debug_p8_intel`, `out` ends at `  0:    EXTDATA:  ... file processed: ExtData/PIESA/L127/GMI.vmr_HNO3.x144_y91.t12.2006.nc4` and the err shows ` 76: forrtl: error (73): floating divide by zero`.

2025-04-02 15:49 UTC, ulmononian commented
for `hafs_global_multiple_4nests_atm_intel`, the `out` file shows:

```
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
  0:  Bad temperatures (dimension 1):            0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            1           0           0
  0:  Bad temperatures (dimension 2):            0           0           0
360:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
  0:            0           0           0           0           0           0
360:   0.0000000E+00
  0:            0           0           0           0           0           0
  0:            0           0           0           1           0
  0:
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
  0:
480:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
480:   0.0000000E+00
```

from `err`:  `0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1`


for `cpld_debug_gfsv17_intel`, `out` ends at:  `150:  mesh file for mom6 domain is mesh.mx100.nc` and `err` shows: `200: forrtl: error (65): floating invalid`.

for `cpld_debug_p8_intel`, `out` ends at `  0:    EXTDATA:  ... file processed: ExtData/PIESA/L127/GMI.vmr_HNO3.x144_y91.t12.2006.nc4` and the err shows ` 76: forrtl: error (73): floating divide by zero`.

@BinLiu-NOAA do you or any other hafs devs. know what might cause this error in `hafs_global_multiple_4nests_atm_intel`?

@DeniseWorthen did hit divide by zero in `cpld_debug_p8_intel` and floating invalid on 1cpld_debug_gfsv17_intel`, if you have any idea.

2025-04-02 15:51 UTC, ulmononian commented
@deni

> @ulmononian Can I confirm that when you are testing the cpld+GNU on Ursa, you are not actually enabling the tests which have been disabled? That is, have you added +ursa to all the cpld+GNU tests and tried to run?

@DeniseWorthen i did not enable/disable any GNU tests, i.e., i used `rt.conf` exactly as it exists in develop.

2025-04-02 15:54 UTC, DeniseWorthen commented
@ulmononian OK, thanks. So we don't actually know if GNU+cpld is working any better on Ursa than on Hera.

As for the cpld_debug_gfsv17 failure, I don't think I have Ursa access, so it is impossible for me to look at any runs.

2025-04-02 15:56 UTC, ulmononian commented
> @ulmononian OK, thanks. So we don't actually know if GNU+cpld is working any better on Ursa than on Hera.
> 
> As for the cpld_debug_gfsv17 failure, I don't think I have Ursa access, so it is impossible for me to look at any runs.

@DeniseWorthen are there specific tests you'd like me to turn on and run on ursa?

2025-04-02 16:12 UTC, DeniseWorthen commented
@ulmononian Yes...Please run the cpld+GNU part of rt.conf as below. I've substituted ursa for hera, enabled every thing on ursa, and modified the SDF for cpld_control_p8 and cpld_debug_p8.


```
diff --git a/tests/rt.conf b/tests/rt.conf
index d62f0d4e..63aa4797 100644
--- a/tests/rt.conf
+++ b/tests/rt.conf
@@ -478,22 +478,22 @@ COMPILE | atm_dyn64_phy32_debug | gnu | -DAPP=ATM -DCCPP_32BIT=ON -DDEBUG=ON | +
 RUN | rap_control_dyn64_phy32_debug                     | + hera hercules                      | baseline |

 ### S2S tests ###
-COMPILE | s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera hercules | fv3 |
-#RUN | cpld_control_p8                                   | + hercules                           | baseline |
+COMPILE | s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
+RUN | cpld_control_p8                                   | + ursa hercules                         | baseline |

-COMPILE | s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + hera hercules | fv3 |
-RUN | cpld_control_nowave_noaero_p8                     | + hera hercules                      | baseline |
+COMPILE | s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
+RUN | cpld_control_nowave_noaero_p8                     | + ursa hercules                      | baseline |

-COMPILE | s2swa_debug | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera hercules | fv3 |
-#RUN | cpld_debug_p8                                     | + hercules                           | baseline |
+COMPILE | s2swa_debug | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
+RUN | cpld_debug_p8                                     | + ursa hercules                        | baseline |

 # Unstructured WW3
-COMPILE | s2sw_pdlib | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON | + hera hercules | fv3 |
-RUN | cpld_control_pdlib_p8                             | + hera hercules                      | baseline |
+COMPILE | s2sw_pdlib | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON | + ursa hercules | fv3 |
+RUN | cpld_control_pdlib_p8                             | + ursa hercules                      | baseline |

-COMPILE | s2sw_pdlib_debug | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON -DDEBUG=ON | + hera hercules | fv3 |
-RUN | cpld_debug_pdlib_p8                               | + hercules                           | baseline |
+COMPILE | s2sw_pdlib_debug | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON -DDEBUG=ON | + ursa hercules | fv3 |
+RUN | cpld_debug_pdlib_p8                               | + ursa hercules                      | baseline |

 ### CDEPS Data Atmosphere test ###
-COMPILE | datm_cdeps | gnu | -DAPP=NG-GODAS | + hera hercules | fv3 |
-RUN | datm_cdeps_control_cfsr                           | + hera hercules                      | baseline |
+COMPILE | datm_cdeps | gnu | -DAPP=NG-GODAS | + ursa hercules | fv3 |
+RUN | datm_cdeps_control_cfsr                           | + ursa hercules                      | baseline |

```

2025-04-02 17:00 UTC, DeniseWorthen commented
@ulmononian For the ``cpld_debug_gfsv17`` failure you reported above, please grep ERROR in PET*LogFile and report if anything suspicious.

2025-04-02 17:30 UTC, ulmononian commented
@lipan-NOAA just noticed the `cpld_control_gefs_intel` also failed. the `err` file shows:

```
 604: pe=00604 FAIL at line=00197    DU2G_GridCompMod.F90                     <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=01338    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=01313    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=00188    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=00051    Aerosol_GridComp.F90                     <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=00487    MAPL_CapGridComp.F90                     <status=41>
 604: pe=00604 FAIL at line=00856    MAPL_CapGridComp.F90                     <status=41>
```

looking at `PET0604.ESMF_LogFile`, it shows:

```
20250402 005221.167 ERROR            PET0604 Aerosol_Cap.F90:303 Not found  - Passing error in return code
20250402 005221.167 ERROR            PET0604 CHM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:1631 Not found  - Passing error in return code
20250402 005221.167 ERROR            PET0604 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2918 Not found  - Phase 'IPDv05p8' Initialize for modelComp 3: CHM did not return ESMF_SUCCESS
20250402 005221.167 ERROR            PET0604 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2727 Not found  - Passing error in return code
20250402 005221.167 ERROR            PET0604 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2473 Not found  - Passing error in return code
20250402 005221.167 ERROR            PET0604 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:492 Not found  - Passing error in return code
20250402 005221.167 ERROR            PET0604 UFS.F90:397 Not found  - Aborting UFS
```

the same error is reported for a significant number other PEs.

2025-04-02 17:34 UTC, ulmononian commented
> @ulmononian For the `cpld_debug_gfsv17` failure you reported above, please grep ERROR in PET*LogFile and report if anything suspicious.

`grep "ERROR" PET*LogFile` in `cpld_debug_gfsv17_intel` yielded no results :/

2025-04-02 17:44 UTC, DeniseWorthen commented
@lipan-NOAA I believe I saw the same error in my SS19/Hercules for the cpld_control_gefs_intel test.

2025-04-02 18:03 UTC, ulmononian commented
> @ulmononian Yes...Please run the cpld+GNU part of rt.conf as below. I've substituted ursa for hera, enabled every thing on ursa, and modified the SDF for cpld_control_p8 and cpld_debug_p8.
> 
> ```
> diff --git a/tests/rt.conf b/tests/rt.conf
> index d62f0d4e..63aa4797 100644
> --- a/tests/rt.conf
> +++ b/tests/rt.conf
> @@ -478,22 +478,22 @@ COMPILE | atm_dyn64_phy32_debug | gnu | -DAPP=ATM -DCCPP_32BIT=ON -DDEBUG=ON | +
>  RUN | rap_control_dyn64_phy32_debug                     | + hera hercules                      | baseline |
> 
>  ### S2S tests ###
> -COMPILE | s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera hercules | fv3 |
> -#RUN | cpld_control_p8                                   | + hercules                           | baseline |
> +COMPILE | s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
> +RUN | cpld_control_p8                                   | + ursa hercules                         | baseline |
> 
> -COMPILE | s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + hera hercules | fv3 |
> -RUN | cpld_control_nowave_noaero_p8                     | + hera hercules                      | baseline |
> +COMPILE | s2s | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
> +RUN | cpld_control_nowave_noaero_p8                     | + ursa hercules                      | baseline |
> 
> -COMPILE | s2swa_debug | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera hercules | fv3 |
> -#RUN | cpld_debug_p8                                     | + hercules                           | baseline |
> +COMPILE | s2swa_debug | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 | + ursa hercules | fv3 |
> +RUN | cpld_debug_p8                                     | + ursa hercules                        | baseline |
> 
>  # Unstructured WW3
> -COMPILE | s2sw_pdlib | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON | + hera hercules | fv3 |
> -RUN | cpld_control_pdlib_p8                             | + hera hercules                      | baseline |
> +COMPILE | s2sw_pdlib | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON | + ursa hercules | fv3 |
> +RUN | cpld_control_pdlib_p8                             | + ursa hercules                      | baseline |
> 
> -COMPILE | s2sw_pdlib_debug | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON -DDEBUG=ON | + hera hercules | fv3 |
> -RUN | cpld_debug_pdlib_p8                               | + hercules                           | baseline |
> +COMPILE | s2sw_pdlib_debug | gnu | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON -DDEBUG=ON | + ursa hercules | fv3 |
> +RUN | cpld_debug_pdlib_p8                               | + ursa hercules                      | baseline |
> 
>  ### CDEPS Data Atmosphere test ###
> -COMPILE | datm_cdeps | gnu | -DAPP=NG-GODAS | + hera hercules | fv3 |
> -RUN | datm_cdeps_control_cfsr                           | + hera hercules                      | baseline |
> +COMPILE | datm_cdeps | gnu | -DAPP=NG-GODAS | + ursa hercules | fv3 |
> +RUN | datm_cdeps_control_cfsr                           | + ursa hercules                      | baseline |
> ```

@DeniseWorthen i misspoke earlier. i did modify rt.conf to add `ursa` anywhere that there exists a `+ hera` in rt.conf. please see the diff between my rt.conf and develop rt.conf here: https://github.com/ufs-community/ufs-weather-model/pull/2471/files#diff-bca3e2e0c761ae3b013409651b01bd531fce420c95ce064b7253f677f81b787a. after that, please let me know if there were any tests that were not run that you'd like me to run (`cpld_control_p8` and `cpld_control_debug` were commented out in my rt.conf, so i can definitely do those two).

2025-04-02 18:09 UTC, NickSzapiro-NOAA commented
fyi, in addition to the edits for gocart .rc files in tests/parm/gocart/ , relevant additions would also be needed to those in tests/parm/gocart/gefs/ . Those are the ones used for the cpld_*gefs RTs

2025-04-02 18:14 UTC, DeniseWorthen commented
@ulmononian OK, please do run those two tests on Ursa (but fix the SDF).

Also, Raghu just let me know I have access to log in and look at files, but can't run jobs on my own. So I'll take a look at the cpld_debug_gfsv17_intel failure. Can you give me the directory location?

2025-04-02 18:28 UTC, ulmononian commented
from the tests you requested, all of these gnu tests passed have already passed on ursa:

```
rap_control_dyn64_phy32_gnu
cpld_control_nowave_noaero_p8_gnu
cpld_control_pdlib_p8_gnu
datm_cdeps_control_cfsr_gnu
```

additionally, every gnu test in my rt.conf was run and passed (save for those that were commented out; i can run `cpld_debug_pdlib_p8`, `cpld_control_p8` and `cpld_control_debug').

2025-04-02 18:28 UTC, ulmononian commented
> fyi, in addition to the edits for gocart .rc files in tests/parm/gocart/ , relevant additions would also be needed to those in tests/parm/gocart/gefs/ . Those are the ones used for the cpld_*gefs RTs

@lipan-NOAA is this something you would be able to do or should we contact someone else?

2025-04-02 18:30 UTC, ulmononian commented
> @ulmononian OK, please do run those two tests on Ursa (but fix the SDF).
> 
> Also, Raghu just let me know I have access to log in and look at files, but can't run jobs on my own. So I'll take a look at the cpld_debug_gfsv17_intel failure. Can you give me the directory location?

`/tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/fixgocart/tests` for tests with aerosols that needed to tested w/ lipan's updates. 

all other tests were in `/tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test2471/tests`.

2025-04-02 18:38 UTC, ulmononian commented
> @ulmononian OK, please do run those two tests on Ursa (but fix the SDF).
> 
> Also, Raghu just let me know I have access to log in and look at files, but can't run jobs on my own. So I'll take a look at the cpld_debug_gfsv17_intel failure. Can you give me the directory location?

what do you mean "fix the SDF"?

2025-04-02 18:43 UTC, DeniseWorthen commented
There are two compile jobs which do not have the correct suite definition file (SDF)

COMPILE | s2swa | gnu | -DAPP=S2SWA -DCCPP_SUITES=**FV3_GFS_v17_coupled_p8** | + hera hercules | fv3 |

This needs to be **FV3_GFS_v17_coupled_p8_ugwpv1**

This is for the compile jobs of cpld_control_p8 and the cpld_debug_p8 tests.

2025-04-02 19:05 UTC, DeniseWorthen commented
@ulmononian The failure of the ``cpld_debug_gfsv17_intel`` test points to the same problem Dusan found when testing on Hera (not sure what stack version). I'm trying to find out if there was an issue created. The failure occurs in the SCOTCH library. 

```
200: forrtl: error (65): floating invalid
200: Image              PC                Routine            Line        Source
200: libc.so.6          0000152BA294C6F0  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D7570E  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D7511B  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D75276  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D74D9C  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D718A8  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D7120E  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D71336  Unknown               Unknown  Unknown
200: fv3.exe            0000000002D705C7  Unknown               Unknown  Unknown
200: fv3.exe            00000000028C24F2  yowpdlibmain_mp_r         632  yowpdlibmain.F90
```

@MatthewMasarik-NOAA @JessicaMeixner-NOAA

2025-04-02 19:09 UTC, DeniseWorthen commented
@ulmononian The failure in the ``cpld_debug_p8`` test is in GOCART:

```
 76: forrtl: error (73): floating divide by zero
 76: Image              PC                Routine            Line        Source
 76: libc.so.6          000014CD27A8A6F0  Unknown               Unknown  Unknown
 76: fv3.exe            0000000003100B28  gocart2g_process_        1927  GOCART2G_Process.F90
 76: fv3.exe            00000000030E66EB  gocart2g_process_        1580  GOCART2G_Process.F90
 76: fv3.exe            0000000002E0D4A5  ss2g_gridcompmod_         796  SS2G_GridCompMod.F90
```

This is the same error I reported [here](https://github.com/ufs-community/ufs-weather-model/pull/2650#issuecomment-2772490246).

In that case, I compiled the current atmaero test in debug mode (there is no existing debug test). @lipan-NOAA

2025-04-02 19:11 UTC, lipan-NOAA commented
604: pe=00604 FAIL at line=00197    DU2G_GridCompMod.F90                     <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=01338    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=01313    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=00188    GOCART2G_GridCompMod.F90                 <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=00051    Aerosol_GridComp.F90                     <status=41>
 604: pe=00604 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 604: pe=00604 FAIL at line=00487    MAPL_CapGridComp.F90                     <status=41>
 604: pe=00604 FAIL at line=00856    MAPL_CapGridComp.F90                     <status=41>

**For such errors in running, see this update** https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22

2025-04-02 19:20 UTC, MatthewMasarik-NOAA commented
> @ulmononian The failure of the `cpld_debug_gfsv17_intel` test points to the same problem Dusan found when testing on Hera (not sure what stack version). I'm trying to find out if there was an issue created. The failure occurs in the SCOTCH library.
> 
> ```
> 200: forrtl: error (65): floating invalid
> 200: Image              PC                Routine            Line        Source
> 200: libc.so.6          0000152BA294C6F0  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7570E  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7511B  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D75276  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D74D9C  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D718A8  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7120E  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D71336  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D705C7  Unknown               Unknown  Unknown
> 200: fv3.exe            00000000028C24F2  yowpdlibmain_mp_r         632  yowpdlibmain.F90
> ```
> 
> @MatthewMasarik-NOAA @JessicaMeixner-NOAA

I'm tied up currently, but I could look at this SCOTCH failure Friday morning if that's helpful.

2025-04-02 19:21 UTC, DeniseWorthen commented
@MatthewMasarik-NOAA Sure. We just won't be able to run any PDLIB RTs once we go to SS 19 until this is resolved.

2025-04-02 19:24 UTC, lipan-NOAA commented
@DeniseWorthen @ulmononian 
 **"@lipan-NOAA I believe I saw the same error in my SS19/Hercules for the cpld_control_gefs_intel test."**

I can run this test on Acorn and the output is /lfs/h1/emc/ptmp/li.pan/FV3_RT/rt_2723139/cpld_debug_gfsv17_intel

2025-04-02 19:24 UTC, ulmononian commented
> 604: pe=00604 FAIL at line=00197 DU2G_GridCompMod.F90 <status=41> 604: pe=00604 FAIL at line=04772 MAPL_Generic.F90 <status=41> 604: pe=00604 FAIL at line=04959 MAPL_Generic.F90 <status=41> 604: pe=00604 FAIL at line=01338 GOCART2G_GridCompMod.F90 <status=41> 604: pe=00604 FAIL at line=01313 GOCART2G_GridCompMod.F90 <status=41> 604: pe=00604 FAIL at line=00188 GOCART2G_GridCompMod.F90 <status=41> 604: pe=00604 FAIL at line=04772 MAPL_Generic.F90 <status=41> 604: pe=00604 FAIL at line=04959 MAPL_Generic.F90 <status=41> 604: pe=00604 FAIL at line=00051 Aerosol_GridComp.F90 <status=41> 604: pe=00604 FAIL at line=04772 MAPL_Generic.F90 <status=41> 604: pe=00604 FAIL at line=00487 MAPL_CapGridComp.F90 <status=41> 604: pe=00604 FAIL at line=00856 MAPL_CapGridComp.F90 <status=41>
> 
> **For such errors in running, see this update** [c7aa2b0](https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22)

@lipan-NOAA is this the proposed solution to resolve the gefs issue (and is it the same as what @NickSzapiro-NOAA mentioned here https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773339424)?

2025-04-02 19:25 UTC, MatthewMasarik-NOAA commented
> @MatthewMasarik-NOAA Sure. We just won't be able to run any PDLIB RTs once we go to SS 19 until this is resolved.

@DeniseWorthen Got it.  I'll look at it first thing Friday.

2025-04-02 19:26 UTC, DusanJovic-NOAA commented
> @ulmononian The failure of the `cpld_debug_gfsv17_intel` test points to the same problem Dusan found when testing on Hera (not sure what stack version). I'm trying to find out if there was an issue created. The failure occurs in the SCOTCH library.
> 
> ```
> 200: forrtl: error (65): floating invalid
> 200: Image              PC                Routine            Line        Source
> 200: libc.so.6          0000152BA294C6F0  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7570E  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7511B  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D75276  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D74D9C  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D718A8  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D7120E  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D71336  Unknown               Unknown  Unknown
> 200: fv3.exe            0000000002D705C7  Unknown               Unknown  Unknown
> 200: fv3.exe            00000000028C24F2  yowpdlibmain_mp_r         632  yowpdlibmain.F90
> ```
> 
> @MatthewMasarik-NOAA @JessicaMeixner-NOAA

Here: https://github.com/ufs-community/ufs-weather-model/issues/2619#issuecomment-2698351577

2025-04-02 19:34 UTC, DeniseWorthen commented
@DusanJovic-NOAA Thanks for the link back to when the issue w/ SCOTCH was first reported. I also note this will probably also stop GW from going to SS19, as mentioned in that issue comment.

2025-04-02 19:50 UTC, DeniseWorthen commented
> @DeniseWorthen @ulmononian **"@lipan-NOAA I believe I saw the same error in my SS19/Hercules for the cpld_control_gefs_intel test."**
> 
> I can run this test on Acorn and the output is /lfs/h1/emc/ptmp/li.pan/FV3_RT/rt_2723139/cpld_debug_gfsv17_intel

I don't think the gefs test and the gfsv17 test are comparable. The gfsv17 test does not use aerosols. The gefs test also uses it's own aerosol files as @NickSzapiro-NOAA points out. Those are in ``tests/parm/gocart/gefs/ ``

2025-04-02 20:31 UTC, ulmononian commented
> fyi, in addition to the edits for gocart .rc files in tests/parm/gocart/ , relevant additions would also be needed to those in tests/parm/gocart/gefs/ . Those are the ones used for the cpld_*gefs RTs

do you know the specific changes needed for the files in tests/parm/gocart/gefs?

2025-04-02 20:34 UTC, NickSzapiro-NOAA commented
The same changes as these [c7aa2b0](https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22)

2025-04-02 20:38 UTC, ulmononian commented
@DeniseWorthen for the additional gnu tests that you requested, all passed except `cpld_debug_p8_gnu`:

```
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
197001010000       compile_s2swa_gnu                       95861           SUCCEEDED                   0         1         607.0
197001010000     cpld_control_p8_gnu                       95867           SUCCEEDED                   0         1         481.0
197001010000    compile_s2swa_debug_gnu                       95862           SUCCEEDED                   0         1         115.0
197001010000       cpld_debug_p8_gnu                       95866                DEAD                   1         3         147.0
197001010000    compile_s2sw_pdlib_debug_gnu                       95860           SUCCEEDED                   0         1         108.0
197001010000    cpld_debug_pdlib_p8_gnu                       95863           SUCCEEDED                   0         1         436.0
```

for `cpld_debug_p8_gnu`, the `out` file ends at 

```
 UFS Aerosols: Advancing from 2021-03-22T06:00:00 to 2021-03-22T06:12:00
...
  0:    EXTDATA:  ... file processed: ExtData/PIESA/L127/GMI.vmr_HNO3.x144_y91.t12.2006.nc4
```

and in the `err` file there are a variety of different divide by zero errors (`122: [o01c04:2344374:0:2344374] Caught signal 8 (Floating point exception: floating-point divide by zero`), and after a bunch of of that,

```
 66: #86  0x422fc1 in ufs
 66:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/fixgocart/driver/UFS.F90:405
 66: #87  0x42372d in main
 66:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/fixgocart/driver/UFS.F90:37
 54: #48  0x1d68893 in __mapl_capgridcompmod_MOD_step
 54:    at /contrib/spack-stack/spack-stack-1.9.1/cache/build_stage/role.epic/spack-stage-mapl-2.53.0-jrpaobdejh4xax2xar5nonajepziq2bo/spack-src/gridcomps/Cap/MAPL_CapGridComp.F90:1075
 54: #49  0x1d69549 in run_mapl_gridcomp
 54:    at /contrib/spack-stack/spack-stack-1.9.1/cache/build_stage/role.epic/spack-stage-mapl-2.53.0-jrpaobdejh4xax2xar5nonajepziq2bo/spack-src/gridcomps/Cap/MAPL_CapGridComp.F90:1056
 54: #50  0x1d69549 in run_gc
 54:    at /contrib/spack-stack/spack-stack-1.9.1/cache/build_stage/role.epic/spack-stage-mapl-2.53.0-jrpaobdejh4xax2xar5nonajepziq2bo/spack-src/gridcomps/Cap/MAPL_CapGridComp.F90:723
 54: #51  0x8786aa in ???
 54: #52  0x878a1e in ???
 54: #53  0xc56cb7 in ???
 54: #54  0x74b345 in ???
 54: #55  0x877519 in ???
 54: #56  0x7d4fb0 in ???
 54: #57  0xa94d36 in ???
 54: #58  0x1d66a26 in __mapl_capgridcompmod_MOD_run
 54:    at /contrib/spack-stack/spack-stack-1.9.1/cache/build_stage/role.epic/spack-stage-mapl-2.53.0-jrpaobdejh4xax2xar5nonajepziq2bo/spack-src/gridcomps/Cap/MAPL_CapGridComp.F90:861
 54: #59  0x18bc8b6 in modeladvance
 54:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/fixgocart/GOCART/ESMF/UFS/Aerosol_Cap.F90:415
```

2025-04-02 20:45 UTC, ulmononian commented
> @MatthewMasarik-NOAA Sure. We just won't be able to run any PDLIB RTs once we go to SS 19 until this is resolved.

@DeniseWorthen i believe all RTs using pdlib have passed on ursa, unless i am misunderstanding something.

2025-04-02 20:52 UTC, DeniseWorthen commented
@ulmononian You reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773020343) that two tests failed and you wanted me to look at them. I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189) the the gfsv17 test failed in calling the SCOTCH library. And I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773462956) that the debug test failed in the in GOCART.

2025-04-02 20:55 UTC, ulmononian commented
> @ulmononian You reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773020343) that two tests failed and you wanted me to look at them. I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189) the the gfsv17 test failed in calling the SCOTCH library. And I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773462956) that the debug test failed in the in GOCART.

indeed...just meant any of the compiles/RTs containing *pdlib* in the title.

2025-04-02 20:57 UTC, ulmononian commented
> The same changes as these [c7aa2b0](https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22)

i believe i have these changes merged into my branch already (https://github.com/ufs-community/ufs-weather-model/pull/2471/files#diff-7eafa9d0b8312bf5724fbb3ecc3d4e825ce33301b6868a0c141e2b7ecd17f125), unless i missed something?

2025-04-02 20:58 UTC, ulmononian commented
> The same changes as these [c7aa2b0](https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22)

@lipan-NOAA @NickSzapiro-NOAA i believe i have these changes merged into my branch already (https://github.com/ufs-community/ufs-weather-model/pull/2471/files#diff-7eafa9d0b8312bf5724fbb3ecc3d4e825ce33301b6868a0c141e2b7ecd17f125), unless i missed something?

2025-04-02 21:01 UTC, DeniseWorthen commented
> > @ulmononian You reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773020343) that two tests failed and you wanted me to look at them. I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189) the the gfsv17 test failed in calling the SCOTCH library. And I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773462956) that the debug test failed in the in GOCART.
> 
> indeed...just meant any of the compiles/RTs containing _pdlib_ in the title.

? But the test clearly uses PDLIB. The executable for gfsv17 debug test is named ``s2swa_32bit_pdlib_debug`` and the COMPILE includes ``-DPDLIB=ON``. I'm not trying to be picky, but I don't want it to get lost that there is an issue w/ SS19 and this test in debug mode, either on Hera or now Ursa.

2025-04-02 21:04 UTC, DeniseWorthen commented
> > The same changes as these [c7aa2b0](https://github.com/ufs-community/ufs-weather-model/commit/c7aa2b031e1b738d373c46f48e43e4b3d5dd2e22)
> 
> @lipan-NOAA @NickSzapiro-NOAA i believe i have these changes merged into my branch already (https://github.com/ufs-community/ufs-weather-model/pull/2471/files#diff-7eafa9d0b8312bf5724fbb3ecc3d4e825ce33301b6868a0c141e2b7ecd17f125), unless i missed something?

The changes need to be made in parm/gocart/**gefs**. But I think we need lipan or someone else to clarify what changes are needed for the GEFS configuration exactly. They may not be the same as in the standard RT.

2025-04-02 21:04 UTC, ulmononian commented
> > > @ulmononian You reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773020343) that two tests failed and you wanted me to look at them. I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189) the the gfsv17 test failed in calling the SCOTCH library. And I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773462956) that the debug test failed in the in GOCART.
> > 
> > 
> > indeed...just meant any of the compiles/RTs containing _pdlib_ in the title.
> 
> ? But the test clearly uses PDLIB. The executable for gfsv17 debug test is named `s2swa_32bit_pdlib_debug` and the COMPILE includes `-DPDLIB=ON`. I'm not trying to be picky, but I don't want it to get lost that there is an issue w/ SS19 and this test in debug mode, either on Hera or now Ursa.

got it. i just got confused when you said we can't run any tests with PDLIB.

2025-04-02 21:07 UTC, ulmononian commented
just going to summarize here quickly. all intel/gnu tests enabled for ursa (see my rt.conf) passing except for:
 
 ```
cpld_debug_gfsv17_intel
cpld_debug_p8_intel
hafs_global_multiple_4nests_atm_intel
cpld_control_gefs_intel
cpld_debug_p8_gnu
```

2025-04-02 21:08 UTC, DeniseWorthen commented
> > > > @ulmononian You reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773020343) that two tests failed and you wanted me to look at them. I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189) the the gfsv17 test failed in calling the SCOTCH library. And I reported in this [comment](https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773462956) that the debug test failed in the in GOCART.
> > > 
> > > 
> > > indeed...just meant any of the compiles/RTs containing _pdlib_ in the title.
> > 
> > 
> > ? But the test clearly uses PDLIB. The executable for gfsv17 debug test is named `s2swa_32bit_pdlib_debug` and the COMPILE includes `-DPDLIB=ON`. I'm not trying to be picky, but I don't want it to get lost that there is an issue w/ SS19 and this test in debug mode, either on Hera or now Ursa.
> 
> got it. i just got confused when you said we can't run any tests with PDLIB.

OK--just one final comment! Since this test is for an opn configuration, it *must* pass in debug mode. So that's a real stopper in terms of updating to SS19.

2025-04-03 18:43 UTC, ulmononian commented
> > @ulmononian The failure of the `cpld_debug_gfsv17_intel` test points to the same problem Dusan found when testing on Hera (not sure what stack version). I'm trying to find out if there was an issue created. The failure occurs in the SCOTCH library.
> > ```
> > 200: forrtl: error (65): floating invalid
> > 200: Image              PC                Routine            Line        Source
> > 200: libc.so.6          0000152BA294C6F0  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D7570E  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D7511B  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D75276  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D74D9C  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D718A8  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D7120E  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D71336  Unknown               Unknown  Unknown
> > 200: fv3.exe            0000000002D705C7  Unknown               Unknown  Unknown
> > 200: fv3.exe            00000000028C24F2  yowpdlibmain_mp_r         632  yowpdlibmain.F90
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @MatthewMasarik-NOAA @JessicaMeixner-NOAA
> 
> I'm tied up currently, but I could look at this SCOTCH failure Friday morning if that's helpful.

thank you @MatthewMasarik-NOAA! please let me know if i can provide any details once you are able to take a look. this PR is obviously for ursa (if you have access there i can provide the rundirs), but sounds like @DusanJovic-NOAA (and maybe @DeniseWorthen) have hit the same error on hera w/ spack-stack/1.9.1 for `cpld_debug_gfsv17_intel`. that said, i went ahead and ran the test on hera (still in queue) and orion with @RatkoVasic-NOAA's spack-stack/1.9.1 branch (same stack as on ursa); those rundirs are below:

orion:  /work/noaa/stmp/cbook/stmp/cbook/FV3_RT/rt_2414643 (source: /work/noaa/epic/cbook/191/tests)
hera [has not run yet]: /scratch1/NCEPDEV/stmp2/Cameron.Book/FV3_RT/rt_935341 (source: /scratch4/NCEPDEV/stmp/Cameron.Book/191/tests)

the test failed on orion in the exact same place as on ursa, namely:

```
180: forrtl: error (65): floating invalid
180: Image              PC                Routine            Line        Source
180: libc.so.6          000014F867FC5D90  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D7574E  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D7515B  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D752B6  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D74DDC  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D718E8  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D7124E  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D71376  Unknown               Unknown  Unknown
180: fv3.exe            0000000002D70607  Unknown               Unknown  Unknown
180: fv3.exe            00000000028C2532  yowpdlibmain_mp_r         632  yowpdlibmain.F90
180: fv3.exe            00000000028AFC2C  yowpdlibmain_mp_i         127  yowpdlibmain.F90
180: fv3.exe            00000000026F62A3  pdlib_w3profsmd_m         263  w3profsmd_pdlib.F90
180: fv3.exe            000000000198DDDD  w3initmd_mp_w3ini         764  w3initmd.F90
180: fv3.exe            000000000143D90B  wav_comp_nuopc_mp        1741  wav_comp_nuopc.F90
180: fv3.exe            000000000141E4B8  wav_comp_nuopc_mp         785  wav_comp_nuopc.F90
```

2025-04-03 19:10 UTC, MatthewMasarik-NOAA commented
Thanks for your post @ulmononian.  I will be looking into it first thing tomorrow morning.  I don't have access to Ursa currently, so the paths you gave for orion and hera are helpful.  I'll keep you posted.

2025-04-04 18:57 UTC, MatthewMasarik-NOAA commented
> thank you @MatthewMasarik-NOAA! please let me know if i can provide any details once you are able to take a look.

@ulmononian would you be able to point me to where the spack-stack SCOTCH build recipe is?  I've looked around through the JCSDA spack and spack-stack repos but haven't had any luck so far

2025-04-04 19:25 UTC, ulmononian commented
> > thank you @MatthewMasarik-NOAA! please let me know if i can provide any details once you are able to take a look.
> 
> @ulmononian would you be able to point me to where the spack-stack SCOTCH build recipe is? I've looked around through the JCSDA spack and spack-stack repos but haven't had any luck so far

here it is for spack-stack/1.9.1: https://github.com/JCSDA/spack/tree/ab2da2468530a580a8100faedf79f66f2cf178fd/var/spack/repos/builtin/packages/scotch

the standard scotch package variants for this release are here: https://github.com/JCSDA/spack-stack/blob/6a7e4d21114990d747fb6cded0ca5863b0bc3402/configs/common/packages.yaml#L269-L270

it was built with the following variants (on orion at least, but should be similar on all machines):

```
scotch@7.0.4%oneapi@2024.2.1+compression+esmumps~int64~ipo+metis+mpi~mpi_thread+noarch~shared~threads build_system=cmake build_type=Release generator=make arch=linux-rocky9-skylake_avx512
```

hope this helps. let me know if you need more info.

2025-04-04 19:51 UTC, MatthewMasarik-NOAA commented
That's really helpful, thanks @ulmononian.   I'm not sure if this would manifest in a `floating point exception`, but I was curious about this reported issue

```
The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
Workarounds are to run on a single node, or to use a system with an RDMA
capable network such as Infiniband.
```

with respect to https://github.com/JCSDA/spack/blob/ab2da2468530a580a8100faedf79f66f2cf178fd/var/spack/repos/builtin/packages/scotch/package.py#L133 and https://github.com/JCSDA/spack-stack/blob/6a7e4d21114990d747fb6cded0ca5863b0bc3402/configs/common/packages.yaml#L269-L270.  

I'll keep investigating, happy to hear any thoughts on that though

2025-04-04 20:23 UTC, MatthewMasarik-NOAA commented
> That's really helpful, thanks @ulmononian. I'm not sure if this would manifest in a `floating point exception`, but I was curious about this reported issue
> 
> ```
> The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
> Workarounds are to run on a single node, or to use a system with an RDMA
> capable network such as Infiniband.
> ```
> 
> with respect to https://github.com/JCSDA/spack/blob/ab2da2468530a580a8100faedf79f66f2cf178fd/var/spack/repos/builtin/packages/scotch/package.py#L133 and https://github.com/JCSDA/spack-stack/blob/6a7e4d21114990d747fb6cded0ca5863b0bc3402/configs/common/packages.yaml#L269-L270.
> 
> I'll keep investigating, happy to hear any thoughts on that though

My last post could be a red herring.  @JessicaMeixner-NOAA pointed out there few new bug fix releases.  This commit from v7.0.7 deals with the functions in the stack trace (`SCOTCH_ParMETIS_V3_PartKway()`, `SCOTCH_dgraphMapCompute()`):  

https://gitlab.inria.fr/scotch/scotch/-/commit/386cb05dcef9f08f1e2f82e307e9926cbe085f4a

2025-04-07 23:26 UTC, lipan-NOAA commented
> @ulmononian The failure in the `cpld_debug_p8` test is in GOCART:
> 
> ```
>  76: forrtl: error (73): floating divide by zero
>  76: Image              PC                Routine            Line        Source
>  76: libc.so.6          000014CD27A8A6F0  Unknown               Unknown  Unknown
>  76: fv3.exe            0000000003100B28  gocart2g_process_        1927  GOCART2G_Process.F90
>  76: fv3.exe            00000000030E66EB  gocart2g_process_        1580  GOCART2G_Process.F90
>  76: fv3.exe            0000000002E0D4A5  ss2g_gridcompmod_         796  SS2G_GridCompMod.F90
> ```
> 
> This is the same error I reported [here](https://github.com/ufs-community/ufs-weather-model/pull/2650#issuecomment-2772490246).
> 
> In that case, I compiled the current atmaero test in debug mode (there is no existing debug test). @lipan-NOAA

@DeniseWorthen @junwang-noaa  This issue can be resolved with this fix (https://github.com/GEOS-ESM/GOCART/pull/314), as I have proven after testing on Acron

2025-04-08 19:53 UTC, ulmononian commented
> > @ulmononian The failure in the `cpld_debug_p8` test is in GOCART:
> > ```
> >  76: forrtl: error (73): floating divide by zero
> >  76: Image              PC                Routine            Line        Source
> >  76: libc.so.6          000014CD27A8A6F0  Unknown               Unknown  Unknown
> >  76: fv3.exe            0000000003100B28  gocart2g_process_        1927  GOCART2G_Process.F90
> >  76: fv3.exe            00000000030E66EB  gocart2g_process_        1580  GOCART2G_Process.F90
> >  76: fv3.exe            0000000002E0D4A5  ss2g_gridcompmod_         796  SS2G_GridCompMod.F90
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the same error I reported [here](https://github.com/ufs-community/ufs-weather-model/pull/2650#issuecomment-2772490246).
> > In that case, I compiled the current atmaero test in debug mode (there is no existing debug test). @lipan-NOAA
> 
> @DeniseWorthen @junwang-noaa This issue can be resolved with this fix ([GEOS-ESM/GOCART#314](https://github.com/GEOS-ESM/GOCART/pull/314)), as I have proven after testing on Acron

can these changes be brought into the ufs-wm? either as a PR to my branch or @RatkoVasic-NOAA's #2650?

2025-04-09 13:19 UTC, lipan-NOAA commented
@ulmononian Yes, but not yet. It may take a while because NASA is reviewing it.

2025-04-09 17:42 UTC, ulmononian commented
@DeniseWorthen @lipan-NOAA @RatkoVasic-NOAA `cpld_debug_p8_intel` passes on ursa with changes to gocart from @lipan-NOAA's https://github.com/GEOS-ESM/GOCART/pull/314.

2025-04-09 17:48 UTC, bbakernoaa commented
> @ulmononian Yes, but not yet. It may take a while because NASA is reviewing it.

@lipan-NOAA @junwang-noaa Lets notify Tom at nasa to get a faster action in the review

2025-04-09 18:04 UTC, ulmononian commented
> > @ulmononian Yes, but not yet. It may take a while because NASA is reviewing it.
> 
> @lipan-NOAA @junwang-noaa Lets notify Tom at nasa to get a faster action in the review

that would be great because i can't seem to properly cherry-pick this without making my gocart hash break lol.

2025-04-11 15:06 UTC, bbakernoaa commented
> > @ulmononian The failure in the `cpld_debug_p8` test is in GOCART:
> > ```
> >  76: forrtl: error (73): floating divide by zero
> >  76: Image              PC                Routine            Line        Source
> >  76: libc.so.6          000014CD27A8A6F0  Unknown               Unknown  Unknown
> >  76: fv3.exe            0000000003100B28  gocart2g_process_        1927  GOCART2G_Process.F90
> >  76: fv3.exe            00000000030E66EB  gocart2g_process_        1580  GOCART2G_Process.F90
> >  76: fv3.exe            0000000002E0D4A5  ss2g_gridcompmod_         796  SS2G_GridCompMod.F90
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the same error I reported [here](https://github.com/ufs-community/ufs-weather-model/pull/2650#issuecomment-2772490246).
> > In that case, I compiled the current atmaero test in debug mode (there is no existing debug test). @lipan-NOAA
> 
> @DeniseWorthen @junwang-noaa This issue can be resolved with this fix ([GEOS-ESM/GOCART#314](https://github.com/GEOS-ESM/GOCART/pull/314)), as I have proven after testing on Acron

This has now been merged in the authoritative gocart repository into the develop branch 

https://github.com/GEOS-ESM/GOCART/tree/develop

2025-04-11 16:37 UTC, lipan-NOAA approved these changes

2025-04-12 03:14 UTC, ulmononian commented
> > > @ulmononian The failure in the `cpld_debug_p8` test is in GOCART:
> > > ```
> > >  76: forrtl: error (73): floating divide by zero
> > >  76: Image              PC                Routine            Line        Source
> > >  76: libc.so.6          000014CD27A8A6F0  Unknown               Unknown  Unknown
> > >  76: fv3.exe            0000000003100B28  gocart2g_process_        1927  GOCART2G_Process.F90
> > >  76: fv3.exe            00000000030E66EB  gocart2g_process_        1580  GOCART2G_Process.F90
> > >  76: fv3.exe            0000000002E0D4A5  ss2g_gridcompmod_         796  SS2G_GridCompMod.F90
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This is the same error I reported [here](https://github.com/ufs-community/ufs-weather-model/pull/2650#issuecomment-2772490246).
> > > In that case, I compiled the current atmaero test in debug mode (there is no existing debug test). @lipan-NOAA
> > 
> > 
> > @DeniseWorthen @junwang-noaa This issue can be resolved with this fix ([GEOS-ESM/GOCART#314](https://github.com/GEOS-ESM/GOCART/pull/314)), as I have proven after testing on Acron
> 
> This has now been merged in the authoritative gocart repository into the develop branch
> 
> https://github.com/GEOS-ESM/GOCART/tree/develop

@bbakernoaa and @lipan-NOAA thank you for this!!!

2025-04-16 18:55 UTC, ulmononian commented
@bbakernoaa @lipan-NOAA is there a plan to update the gocart hash of the ufs wm so that all of these fixes are in develop? they will be needed for the spack-stack/1.9.1 and ursa PRs.

2025-04-16 19:24 UTC, lipan-NOAA commented
@ulmononian Yes, once the ESMF and MAPL updates are installed on WCOSS2

2025-04-16 20:49 UTC, ulmononian commented
@DeniseWorthen testing @natalie-perlin and your fixes for `cpld_debug_p8` that allowed the test to pass on hera. should i use `FV3_GFS_v17_coupled_p8` or `FV3_GFS_v17_coupled_p8_ugwpv1`? i am currently using `FV3_GFS_v17_coupled_p8_ugwpv1` and even w/ the ww3 changes, i am getting 

```
o01c01:369259:0:369259] Caught signal 8 (Floating point exception: floating-point invalid operation)
```

2025-04-16 21:07 UTC, DeniseWorthen commented
You need to use FV3_GFS_v17_coupled_p8_ugwpv1. 

What is location of the error? It should be reporting a line number.

2025-04-16 21:48 UTC, ulmononian commented
> You need to use FV3_GFS_v17_coupled_p8_ugwpv1.
> 
> What is location of the error? It should be reporting a line number.

thanks. here is more error (starts at line 184)

```
150: WARNING from PE     0: Unused line in INPUT/MOM_input : ODA_INCUPD_NHOURS = 6
150:
184: [o01c01:373046:0:373046] Caught signal 8 (Floating point exception: floating-point invalid operation)
184: ==== backtrace (tid: 373046) ====
184:  0  /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/ucx-1.17.0-twv5hpal4zp2mzraquagyifvwmjfik6y/lib/libucs.so.0(ucs_handle_error+0x294) [0x14c544e2dc44]
184:  1  /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/ucx-1.17.0-twv5hpal4zp2mzraquagyifvwmjfik6y/lib/libucs.so.0(+0x31dff) [0x14c544e2ddff]
184:  2  /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/ucx-1.17.0-twv5hpal4zp2mzraquagyifvwmjfik6y/lib/libucs.so.0(+0x3220a) [0x14c544e2e20a]
184:  3  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x18aa32a]
184:  4  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x17de46f]
184:  5  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x15d5044]
184:  6  /lib64/libgomp.so.1(GOMP_parallel+0x46) [0x14c54743d576]
184:  7  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x15c6bee]
184:  8  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x126ed83]
184:  9  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd7f53c]
184: 10  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd7f84d]
184: 11  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd80f57]
184: 12  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x86db4e]
184: 13  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x92e1915]
184: 14  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x8786ab]
184: 15  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x878a1f]
184: 16  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xc53f45]
184: 17  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xc56dfe]
184: 18  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x74b346]
184: 19  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x87751a]
184: 20  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x7d4fb1]
184: 21  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xa94d37]
184: 22  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x7718de]
184: 23  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd7f53c]
184: 24  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd7f84d]
184: 25  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xd80f57]
184: 26  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x86db4e]
184: 27  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x7673e1]
184: 28  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x8786ab]
184: 29  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x878a1f]
184: 30  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xc56cb8]
184: 31  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x74b346]
184: 32  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x87751a]
184: 33  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x7d4fb1]
184: 34  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0xa94d37]
184: 35  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x422fc2]
184: 36  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x42372e]
184: 37  /lib64/libc.so.6(+0x295d0) [0x14c5470c45d0]
184: 38  /lib64/libc.so.6(__libc_start_main+0x80) [0x14c5470c4680]
184: 39  /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3307463/cpld_debug_p8_gnu/./fv3.exe() [0x420b05]
184: =================================
184:
184: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
184:
184: Backtrace for this error:
184: #0  0x14c54794a880 in ???
184: #1  0x14c547949a25 in ???
184: #2  0x14c5470d972f in ???
184: #3  0x18aa32a in __w3sdb1md_MOD_w3sdb1
184:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test_np/WW3/model/src/w3sdb1md.F90:262
184: #4  0x17de46e in __w3srcemd_MOD_w3srce
184:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test_np/WW3/model/src/w3srcemd.F90:1174
184: #5  0x15d5043 in __w3wavemd_MOD_w3wave._omp_fn.3
184:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test_np/WW3/model/src/w3wavemd.F90:2266
184: #6  0x14c54743d575 in ???
184: #7  0x15c6bed in __w3wavemd_MOD_w3wave
184:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test_np/WW3/model/src/w3wavemd.F90:2172
184: #8  0x126ed82 in modeladvance
184:    at /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/test_np/WW3/model/src/wav_comp_nuopc.F90:1247
```

2025-04-16 22:11 UTC, DeniseWorthen commented
Have you checked out the right branch?

https://github.com/DeniseWorthen/WW3/tree/bugfix/w3sdb1_typeconversions

hash 5ce8b54

2025-04-16 23:06 UTC, ulmononian commented
> Have you checked out the right branch?
> 
> https://github.com/DeniseWorthen/WW3/tree/bugfix/w3sdb1_typeconversions
> 
> hash 5ce8b54

nope...i was not on the right branch. cpld_debug_p8_gnu passes on ursa w/ your changes!

2025-04-24 14:49 UTC, ulmononian commented
@DeniseWorthen @jkbk2004 @junwang-noaa: thanks to @natalie-perlin's debugging efforts and ww3 fixes from @DeniseWorthen, the following GNU tests, which will soon be re-enabled on hera/hercules (via #2694), also all pass on ursa:

```
cpld_control_p8
cpld_debug_p8
control_wam_debug
cpld_control_pdlib_p8
cpld_debug_pdlib_p8 
```

runs are in ` /tds_scratch2/SYSADMIN/pilot-users/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_1868791`.

2025-04-28 20:55 UTC, ulmononian commented
@DusanJovic-NOAA spack-stack/1.9.1 is built with icx/icpx/ifort on ursa. do we need to run the LLVM tests or have an ursa llvm modulefile?

2025-04-29 13:30 UTC, DusanJovic-NOAA commented
> @DusanJovic-NOAA spack-stack/1.9.1 is built with icx/icpx/ifort on ursa. do we need to run the LLVM tests or have an ursa llvm modulefile? right now, cmake recognizes the compilers as mixed mode and so the flags from dom's PR are used.

If ifx works as expected on ursa then yes, we should have at least few tests, if not more, run with it. Because eventually we'll need to switch all tests to ifx, so we should make sure we do not introduce code change that does not work with ifx.

2025-04-29 18:05 UTC, ulmononian commented
> > @DusanJovic-NOAA spack-stack/1.9.1 is built with icx/icpx/ifort on ursa. do we need to run the LLVM tests or have an ursa llvm modulefile? right now, cmake recognizes the compilers as mixed mode and so the flags from dom's PR are used.
> 
> If ifx works as expected on ursa then yes, we should have at least few tests, if not more, run with it. Because eventually we'll need to switch all tests to ifx, so we should make sure we do not introduce code change that does not work with ifx.

i added an intelllvm modulefile for ursa: https://github.com/ulmononian/ufs-weather-model/blob/feature/ursa_port/modulefiles/ufs_ursa.intelllvm.lua. this look ok?

i ran all of the LLVM tests currently in rt.conf from develop on ursa ufe03. the following tests passed:

```
cpld_control_gfsv17_intelllvm
cpld_control_sfs_intelllvm
cpld_control_p8_intelllvm
rap_control_dyn32_phy32_intelllvm
rap_control_dyn64_phy32_intelllvm
hafs_regional_storm_following_1nest_atm_ocn_intelllvm
hafs_regional_storm_following_1nest_atm_ocn_debug_intelllvm
```

the only test that failed was `cpld_debug_gfsv17_intelllvm`, which was expected due to the ongoing scotch/WW3 issue for this test reported on hera/hercules/orion and oso.

2025-04-30 06:06 UTC, ulmononian commented
ran the full RT suite (intel, intel LLVM, gnu) on the official ursa nodes/system (using `-c` arg to `rt.sh`). all tests passed except for

```
cpld_control_gefs_intel
cpld_debug_gfsv17_intel
cpld_debug_pdlib_p8_intel
hafs_global_multiple_4nests_atm_intel
cpld_debug_gfsv17_intelllvm
cpld_debug_p8_gnu
```

`cpld_debug_gfsv17_intel`, `cpld_debug_pdlib_p8_intel`, `cpld_debug_gfsv17_intelllvm` failed due to the known issues with scotch/7.0.4 and WW3 (https://github.com/ufs-community/ufs-weather-model/pull/2471#issuecomment-2773456189, [spack-stack #1608](https://github.com/JCSDA/spack-stack/issues/1608). this error also occurs on hercules/orion/hera, though using `scotch/7.0.7` and ww3 changes from @MatthewMasarik-NOAA resolves it on hera.

`cpld_debug_p8_gnu` failed due to the known issue that will be resolved via #2694. 

`cpld_control_gefs_intel` failed in the same place as on oso (@lipan-NOAA @bbakernoaa):

```
 16: pe=00016 FAIL at line=00197    DU2G_GridCompMod.F90                     <status=41>
  16: pe=00016 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
  16: pe=00016 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
  16: pe=00016 FAIL at line=01338    GOCART2G_GridCompMod.F90                 <status=41>
  16: pe=00016 FAIL at line=01313    GOCART2G_GridCompMod.F90                 <status=41>
  16: pe=00016 FAIL at line=00188    GOCART2G_GridCompMod.F90                 <status=41>
  16: pe=00016 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
  16: pe=00016 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
  16: pe=00016 FAIL at line=00051    Aerosol_GridComp.F90                     <status=41>
  16: pe=00016 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
  16: pe=00016 FAIL at line=00487    MAPL_CapGridComp.F90                     <status=41>
  16: pe=00016 FAIL at line=00856    MAPL_CapGridComp.F90                     <status=41>
```

`hafs_global_multiple_4nests_atm_intel` failed at the same place as on oso (@BinLiu-NOAA @ZhanZhang-NOAA @BijuThomas-NOAA):

```
(err)
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
  0:
  0: Image              PC                Routine            Line        Source
  0: fv3.exe            000000000278C9D7  mpp_mod_mp_mpp_er          80  mpp_util_mpi.inc
  0: fv3.exe            000000000278BD09  mpp_mod_mp_mpp_er         178  mpp_util.inc
  0: fv3.exe            0000000002630D97  fms_mod_mp_fms_er         536  fms.F90
  0: fv3.exe            0000000002AA6F99  sat_vapor_pres_mo        1459  sat_vapor_pres.inc
  0: fv3.exe            00000000020A15F1  fv_diagnostics_mo        5634  fv_diagnostics.F90
  0: fv3.exe            0000000002039729  fv_diagnostics_mo        2164  fv_diagnostics.F90
  0: fv3.exe            0000000002287679  atmosphere_mod_mp        1772  atmosphere.F90
  0: fv3.exe            0000000001CFC3AD  atmos_model_mod_m         985  atmos_model.F90
  0: fv3.exe            0000000001B4C614  module_fcst_grid_        1393  module_fcst_grid_comp.F90

(out)
  0:  Bad temperatures (dimension 1):            0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            1           0           0
  0:  Bad temperatures (dimension 2):            0           0           0
360:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
  0:            0           0           0           0           0           0
360:   0.0000000E+00
  0:            0           0           0           0           0           0
  0:            0           0           0           1           0
  0:
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
```

the rocoto log is here:  [rocoto_results.log](https://github.com/user-attachments/files/19971809/rocoto_results.log)

run directories here: `/scratch4/NAGAPE/epic/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3890989`

2025-04-30 17:16 UTC, bbakernoaa commented
@ulmononian as I mentioned earlier.  With the updated gocart we need to update the control files.  I submitted a PR to your branch.  Checking for one additional piece but will let you know when to try it again.  I cannot test on Ursa to test it 

https://github.com/ulmononian/ufs-weather-model/pull/21

2025-04-30 17:19 UTC, ulmononian commented
> @ulmononian as I mentioned earlier. With the updated gocart we need to update the control files. I submitted a PR to your branch. Checking for one additional piece but will let you know when to try it again. I cannot test on Ursa to test it
> 
> [ulmononian#21](https://github.com/ulmononian/ufs-weather-model/pull/21)

@bbakernoaa thanks so much! sorry -- i didn't see your PR to the branch and must have missed your comment. i'll wait until you confirm about the "one additional piece" before merging your PR into my branch and re-running the RT.

2025-04-30 17:38 UTC, bbakernoaa commented
@ulmononian we should be good to go.  I'm not sure if all the tests point to the parm/gocart/gefs/*.rc files for gocart or not.  But we may need to modify the ones in the previous directory as well (parm/gocart/gefs). 

I rolled back the drag_partition_option to 1 so we can use the same input right now.

2025-04-30 17:40 UTC, ulmononian commented
> @ulmononian we should be good to go. I'm not sure if all the tests point to the parm/gocart/gefs/*.rc files for gocart or not. But we may need to modify the ones in the previous directory as well (parm/gocart/gefs).
> 
> I rolled back the drag_partition_option to 1 so we can use the same input right now.

thanks @bbakernoaa! i merged your pr into my branch and will re-run this test on ursa.

2025-04-30 18:09 UTC, ulmononian commented
@bbakernoaa i re-ran `cpld_control_gets_intel` with your pr merged, but unfortunately it failed with

```
232: pe=00232 FAIL at line=00170    CA2G_GridCompMod.F90                     <status=41>
 232: pe=00232 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 232: pe=00232 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 232: pe=00232 FAIL at line=01338    GOCART2G_GridCompMod.F90                 <status=41>
 232: pe=00232 FAIL at line=01315    GOCART2G_GridCompMod.F90                 <status=41>
 232: pe=00232 FAIL at line=00188    GOCART2G_GridCompMod.F90                 <status=41>
 232: pe=00232 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 232: pe=00232 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 232: pe=00232 FAIL at line=00051    Aerosol_GridComp.F90                     <status=41>
 232: pe=00232 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 232: pe=00232 FAIL at line=00487    MAPL_CapGridComp.F90                     <status=41>
 232: pe=00232 FAIL at line=00856    MAPL_CapGridComp.F90                     <status=41>
 256: pe=00256 FAIL at line=00170    CA2G_GridCompMod.F90                     <status=41>
 354: pe=00354 FAIL at line=00170    CA2G_GridCompMod.F90                     <status=41>
 354: pe=00354 FAIL at line=04772    MAPL_Generic.F90                         <status=41>
 354: pe=00354 FAIL at line=04959    MAPL_Generic.F90                         <status=41>
 354: pe=00354 FAIL at line=01338    GOCART2G_GridCompMod.F90                 <status=41>
```

the last section of the `out` file reads:

```
1128: WW3 log written to /scratch4/NAGAPE/epic/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_108101/cpld_control_gefs_intel/log.ww3
   0:       MAPL: No configure file specified for logging layer.  Using defaults.
   0:  Starting pFIO input server on Clients
   0:  Starting pFIO output server on Clients
   0:      SHMEM: NumCores per Node = 96
   0:      SHMEM: NumNodes in use   = 4
   0:      SHMEM: Total PEs         = 384
   0:      SHMEM: NumNodes in use  = 4
   0:  Character Resource Parameter: ROOT_CF:AERO.rc
   0:  Character Resource Parameter: ROOT_NAME:AERO
   0:  Character Resource Parameter: HIST_CF:AERO_HISTORY.rc
   0:  Character Resource Parameter: EXTDATA_CF:AERO_ExtData.rc
   0:  DU::SetServices: Dust emission scheme is fengsha
   0:  FENGSHA: config: alpha:   0.1000000
   0:  FENGSHA: config: gamma:    1.000000
   0:  FENGSHA: config: soil_moisture_factor:    1.000000
   0:  FENGSHA: config: soil_drylimit_factor:    1.000000
   0:  FENGSHA: config: vertical_to_horizontal_flux_ratio_limit:   1.9999999E-04
   0:  FENGSHA: config: drag_partition_option:            1
   0:  DU::SetServices: Wet removal scheme is ufs
   0:  SS::SetServices: Wet removal scheme is ufs
```

2025-04-30 19:15 UTC, NickSzapiro-NOAA commented
The changes to tests/parm/gocart/AERO_ExtData.rc may be needed in tests/parm/gocart/gefs/AERO_ExtData.rc too

Edit: + same changes to tests/parm/gocart/SU2G_instance_SU.rc

Only the cpld_*gefs tests use the files in tests/parm/gocart/gefs/

2025-04-30 19:23 UTC, lipan-NOAA commented
@ulmononian Could you please check CA2G_instance_CA.bc.rc and CA2G_instance_CA.oc.rc to see if these lines are included in your updated CA2G files?

"# Rate of conversion of hydrophobic to hydrophilic [days]
time_days_hydrophobic_to_hydrophilic: 2.5"

"# Rate of chemical destruction of carbon species [days]
time_days_chemical_destruction: -1.  -1."

2025-04-30 19:58 UTC, ulmononian commented
@NickSzapiro-NOAA @lipan-NOAA i just tested with the updates you suggested but it failed in the same place. i committed the changes i made to my branch just so you could see what i did (and if i messed it up). please take a look and let me know: https://github.com/ulmononian/ufs-weather-model/commit/bd9a0569aa289f50bee7651593be9c193065fc9c

2025-04-30 20:14 UTC, NickSzapiro-NOAA commented
Still missing SU2G_instance_SU.rc changes to volcano_srcfilen_{explosive,degassing} on gefs side

Otherwise, I was able to run `drag_partition_option: 2` but without `wet_removal_scheme` options on hera around a week ago

2025-04-30 20:22 UTC, lipan-NOAA commented
@ulmononian In AERO_ExtData.rc
DU_SSM            '1'  Y E           -           none none sep         ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc

DU_SSM            '1'  Y E           -           none none **ssm**         ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc

2025-04-30 20:45 UTC, ulmononian commented
> Still missing SU2G_instance_SU.rc changes to volcano_srcfilen_{explosive,degassing} on gefs side
> 
> Otherwise, I was able to run `drag_partition_option: 2` but without `wet_removal_scheme` options on hera around a week ago

should i also change `DU2G_instance_DU.rc` in parm/gocart/gefs to include 

> @ulmononian In AERO_ExtData.rc DU_SSM '1' Y E - none none sep ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
> 
> DU_SSM '1' Y E - none none **ssm** ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc

@NickSzapiro-NOAA i made the change to `SU2G_instance_SU.rc`. @lipan-NOAA i also made the change to the gocart/gefs `AERO_ExtData.rc` to change `sep` to `ssm`. when i ran, i get:

` 426: pe=00426 FAIL at line=00037    NetCDF4_get_var.H                        <Variable not found: ssm in file: ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc>`.

2025-04-30 21:17 UTC, lipan-NOAA commented
DU_CLAY           '1'  Y E           -           none none clayfrac    ExtData/dust/FENGSHA_p81_10km_inputs.nc
DU_SAND           '1'  Y E           -           none none sandfrac    ExtData/dust/FENGSHA_p81_10km_inputs.nc
DU_SILT           '1'  Y E           -           none none siltfrac    /dev/null
DU_SSM            '1'  Y E %y4-%m2-%d2T12:00:00  none none ssm         /dev/null:1.0
DU_RDRAG          NA   Y N %y4-%m2-%d2t12:00:00  none none albedo_drag ExtData/dust/FENGSHA_p81_10km_inputs.nc
DU_UTHRES         '1'  Y E           -           none none uthres      ExtData/dust/FENGSHA_p81_10km_inputs.nc
DU_GVF            '1'  Y E %y4-%m2-%d2T12:00:00  none none GVF         /dev/null:1.0
DU_LAI            '1'  Y E %y4-%m2-%d2T12:00:00  none none LAI         /dev/null:1.0

@ulmononian commit bd9a0569aa289f50bee7651593be9c193065fc9c I can run it on Acorn

2025-05-01 19:22 UTC, ulmononian commented
> DU_CLAY '1' Y E - none none clayfrac ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_SAND '1' Y E - none none sandfrac ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_SILT '1' Y E - none none siltfrac /dev/null DU_SSM '1' Y E %y4-%m2-%d2T12:00:00 none none ssm /dev/null:1.0 DU_RDRAG NA Y N %y4-%m2-%d2t12:00:00 none none albedo_drag ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_UTHRES '1' Y E - none none uthres ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_GVF '1' Y E %y4-%m2-%d2T12:00:00 none none GVF /dev/null:1.0 DU_LAI '1' Y E %y4-%m2-%d2T12:00:00 none none LAI /dev/null:1.0
> 
> @ulmononian commit [bd9a056](https://github.com/ufs-community/ufs-weather-model/commit/bd9a0569aa289f50bee7651593be9c193065fc9c) I can run it on Acorn

is this different from what i 

> DU_CLAY '1' Y E - none none clayfrac ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_SAND '1' Y E - none none sandfrac ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_SILT '1' Y E - none none siltfrac /dev/null DU_SSM '1' Y E %y4-%m2-%d2T12:00:00 none none ssm /dev/null:1.0 DU_RDRAG NA Y N %y4-%m2-%d2t12:00:00 none none albedo_drag ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_UTHRES '1' Y E - none none uthres ExtData/dust/FENGSHA_p81_10km_inputs.nc DU_GVF '1' Y E %y4-%m2-%d2T12:00:00 none none GVF /dev/null:1.0 DU_LAI '1' Y E %y4-%m2-%d2T12:00:00 none none LAI /dev/null:1.0
> 
> @ulmononian commit [bd9a056](https://github.com/ufs-community/ufs-weather-model/commit/bd9a0569aa289f50bee7651593be9c193065fc9c) I can run it on Acorn

what you show above differs from what i have in my `AERO_ExtData.rc` file. i have:

```
#====== Dust Imports =================================================
# FENGSHA input files. Note: regridding should be N or E - Use files with _FillValue != NaN
DU_CLAY           '1'  Y E           -           none none clayfrac    ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
DU_SAND           '1'  Y E           -           none none sandfrac    ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
DU_SILT           '1'  Y E           -           none none siltfrac    /dev/null
DU_SSM            '1'  Y E           -           none none ssm         ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
DU_RDRAG          '1'  Y E %y4-%m2-%d2t12:00:00  none none albedo_drag ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
DU_UTHRES         '1'  Y E           -           none none uthres      ExtData/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc
DU_GVF            '1'  Y E %y4-%m2-%d2T12:00:00  none none GVF         /dev/null:1.0
DU_LAI            '1'  Y E %y4-%m2-%d2T12:00:00  none none LAI         /dev/null:1.0
```

should i use what you pasted?

2025-05-02 00:44 UTC, lipan-NOAA commented
@ulmononian ulmononian:feature/ursa_port/: tests/parm/gocart/AERO_ExtData.rc

This is what I use in RT

2025-05-02 21:24 UTC, ulmononian commented
@NickSzapiro-NOAA @lipan-NOAA changing just SU2G_instance_SU.rc allowed `cpld_control_gefs` to pass! i had to undo the sep to ssm change...

2025-05-05 16:00 UTC, BrianCurtis-NOAA commented
@ulmononian Do you know if Ursa will have a separate ecflow node like Hera (hecflow01) ? If so, make sure that rt.sh is updated accordingly.

2025-05-05 16:02 UTC, RatkoVasic-NOAA commented
@BrianCurtis-NOAA it is already there:
```
Hostname            Description
ofe01               Oso test front-end node (restricted)
ofe02               Oso test front-end node (restricted)
uecflow01           Ursa Ecflow Node
ufe01               Ursa Front End Node
ufe02               Ursa Front End Node
ufe03               Ursa Front End Node
ufe04               Ursa Front End Node
```

2025-05-05 18:02 UTC, ulmononian commented
@SamuelTrahanNOAA do you maintain `https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/hafs_global_multiple_4nests_atm`? it is failing on ursa (and derecho) with spack-stack/1.91. the failure in the `out` file looks like:

```
480:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.200000
480:   0.0000000E+00
  0: PASS: fcstRUN phase 1, n_atmsteps =              208 time is         0.199302
  0:  Range_check Warning:PT UPDATE max =    393.2270      min =    179.0175
  0:  Range violation on: 2020/ 8/25 17:13:30
  0: Warn_K=  48 (i,j)=   22   19 (lon,lat)=302.832 -34.062 PT UPDATE = 393.22699
  0:      K=  47    280.84009
  0:      K=  49    282.75595
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
  0:  PT UPDATE:    79.84667              22          19          48   5.285411
  0:  -0.5944861
240:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
240:   0.0000000E+00
600:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
600:   0.0000000E+00
  0:  Range_check Warning:TA update max =    393.2270      min =    179.0175
  0:  Range violation on: 2020/ 8/25 17:12: 0
  0: Warn_K=  48 (i,j)=   22   19 (lon,lat)=302.832 -34.062 TA update = 393.22699
  0:      K=  47    280.84009
  0:      K=  49    282.75595
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
  0:  Range_check Warning:TA max =    393.2270      min =    179.0175
  0:  Range violation on: 2020/ 8/25 17:13:30
  0: Warn_K=  48 (i,j)=   22   19 (lon,lat)=302.832 -34.062 TA = 393.22699
  0:      K=  47    280.84009
  0:      K=  49    282.75595
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
  0:  Bad temperatures (dimension 1):            0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            0           0           0           0           0           0
  0:            1           0           0
  0:  Bad temperatures (dimension 2):            0           0           0
360:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
  0:            0           0           0           0           0           0
360:   0.0000000E+00
  0:            0           0           0           0           0           0
  0:            0           0           0           1           0
  0:
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
  0:
480:  in atmos_model update, fhzero=   3.00000000000000      fhour=   5.225000
```

and the `err` file shows:

```
  0: FATAL from PE     0: compute_qs: saturation vapor pressure table overflow, nbad=      1
  0:
  0: Image              PC                Routine            Line        Source
  0: fv3.exe            000000000278C9D7  mpp_mod_mp_mpp_er          80  mpp_util_mpi.inc
  0: fv3.exe            000000000278BD09  mpp_mod_mp_mpp_er         178  mpp_util.inc
  0: fv3.exe            0000000002630D97  fms_mod_mp_fms_er         536  fms.F90
  0: fv3.exe            0000000002AA6F99  sat_vapor_pres_mo        1459  sat_vapor_pres.inc
  0: fv3.exe            00000000020A15F1  fv_diagnostics_mo        5634  fv_diagnostics.F90
  0: fv3.exe            0000000002039729  fv_diagnostics_mo        2164  fv_diagnostics.F90
  0: fv3.exe            0000000002287679  atmosphere_mod_mp        1772  atmosphere.F90
  0: fv3.exe            0000000001CFC3AD  atmos_model_mod_m         985  atmos_model.F90
  0: fv3.exe            0000000001B4C614  module_fcst_grid_        1393  module_fcst_grid_comp.F90
```

we would like this test to pass on ursa and derecho, but not sure how to resolve this. if you do not maintain this anymore/have time to check the issue, do you know anyone who might? thanks!

2025-05-14 19:48 UTC, ulmononian commented
just to provide an update to those following this work. the remaining test failures are:

```
cpld_debug_gfsv17_intel
cpld_debug_pdlib_p8_intel
cpld_debug_gfsv17_intelllvm

hafs_global_multiple_4nests_atm_intel
```

@RatkoVasic-NOAA and myself continue to work with @JessicaMeixner-NOAA on the ww3/scotch failure causing `cpld_debug_gfsv17_intel`, `cpld_debug_pdlib_p8_intel`, and `cpld_debug_gfsv17_intelllvm` to fail, but no luck yet. @jkbk2004 fyi.

2025-05-27 16:39 UTC, NickSzapiro-NOAA commented
I see some differences in the gocart rc configs `tests/parm/gocart/gefs/*rc` between https://github.com/ufs-community/ufs-weather-model/pull/2471 and https://github.com/ufs-community/ufs-weather-model/pull/2650 . Can we agree on these here or there @ulmononian @RatkoVasic-NOAA ?

2025-05-27 18:46 UTC, BrianCurtis-NOAA commented
Is there a reason such an old GNU version is being tested here? Can we use one of the newer GNU versions (like something in 14.x, or matching 13 used on other systems?)

2025-05-27 19:04 UTC, ulmononian commented
> Is there a reason such an old GNU version is being tested here? Can we use one of the newer GNU versions (like something in 14.x, or matching 13 used on other systems?)

11.4.1 is the default gcc on ursa. looks like 12.4.0 is available as a module, but we have not built the stack with the version.

2025-05-27 19:14 UTC, RatkoVasic-NOAA commented
> I see some differences in the gocart rc configs `tests/parm/gocart/gefs/*rc` between #2471 and #2650 . Can we agree on these here or there @ulmononian @RatkoVasic-NOAA ?

@NickSzapiro-NOAA , the only change I have is this line: https://github.com/RatkoVasic-NOAA/ufs-weather-model/blob/fc09d090103c5da23a5169d6dfed8d9ad06a67b5/tests/parm/gocart/CAP.rc#L4
And that line should be included.
Are there any other changes?

2025-05-27 19:17 UTC, ulmononian commented
> > I see some differences in the gocart rc configs `tests/parm/gocart/gefs/*rc` between #2471 and #2650 . Can we agree on these here or there @ulmononian @RatkoVasic-NOAA ?
> 
> @NickSzapiro-NOAA , the only change I have is this line: https://github.com/RatkoVasic-NOAA/ufs-weather-model/blob/fc09d090103c5da23a5169d6dfed8d9ad06a67b5/tests/parm/gocart/CAP.rc#L4 And that line should be included. Are there any other changes?

i would prefer to go with what we have in this PR because the changes resolved gefs test failures.

2025-05-27 19:28 UTC, NickSzapiro-NOAA commented
In https://github.com/RatkoVasic-NOAA/ufs-weather-model/compare/ss-191...ulmononian:ufs-weather-model:feature/ursa_port there are diffs wrt wet_removal_scheme, fwet_{ice,snow,rain}, and drag_partition_scheme options

I asked as were debugging some test issue somewhere in gocart but it doesn't seem as related on second try

fwiw, I think it's ok to choose options that work as GEFS RT will turn off aerosols soon to match GEFS.v13 configuration

2025-05-27 19:51 UTC, bbakernoaa commented
@NickSzapiro-NOAA I'll try to grab this tomorrow and test.  If we are updating to the latest GOCART there will need to be changes to the other `.rc` files as well.

2025-05-28 14:00 UTC, DusanJovic-NOAA commented
I am getting the module load error when I try to run on of the gnu tests:

```
++ pwd
+ BUILD_DIR=/scratch3/NCEPDEV/stmp/Dusan.Jovic/RT_RUNDIRS/Dusan.Jovic/FV3_RT/rt_2877015/compile_s2sw_pdlib_debug_gnu/build_fv3_s2sw_pdlib_debug_gnu
+ [[ ursa == derecho ]]
+ BUILD_JOBS=8
+ set +x
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "mapl/2.53.3-esmf-8.8.0"
   Try: "module spider mapl/2.53.3-esmf-8.8.0" to see how to load the
module(s).

Executing this command requires loading "mapl/2.53.3-esmf-8.8.0" which failed
while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    ufs_common       /scratch3/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/ufs-weather-model/modulefiles/ufs_common.lua
    ufs_ursa.gnu     /scratch3/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/ufs-weather-model/modulefiles/ufs_ursa.gnu.lua

```

2025-05-28 14:09 UTC, bbakernoaa commented
@ulmononian  there are indeed missing values in the gocart `.rc` files these will be needed for other tests than GEFS so even if you take them out these changes will be needed.  You can see the changes necessary here: 
```bash
/scratch4/NCEPDEV/naqfc/Barry.Baker/models/ufswm/tests/parm/gocart/gefs
/scratch4/NCEPDEV/naqfc/Barry.Baker/models/ufswm/tests/parm/gocart/
```

I tried running the control_atmaero_p8 to test but the input data hasn't been stored in `/scratch4/NAGAPE/epic/role-epic/UFS-WM_RT/NEMSfv3gfs` yet

2025-05-28 18:17 UTC, ulmononian commented
> I am getting the module load error when I try to run on of the gnu tests:
> 
> ```
> ++ pwd
> + BUILD_DIR=/scratch3/NCEPDEV/stmp/Dusan.Jovic/RT_RUNDIRS/Dusan.Jovic/FV3_RT/rt_2877015/compile_s2sw_pdlib_debug_gnu/build_fv3_s2sw_pdlib_debug_gnu
> + [[ ursa == derecho ]]
> + BUILD_JOBS=8
> + set +x
> Lmod has detected the following error: These module(s) or extension(s) exist
> but cannot be loaded as requested: "mapl/2.53.3-esmf-8.8.0"
>    Try: "module spider mapl/2.53.3-esmf-8.8.0" to see how to load the
> module(s).
> 
> Executing this command requires loading "mapl/2.53.3-esmf-8.8.0" which failed
> while processing the following module(s):
> 
>     Module fullname  Module Filename
>     ---------------  ---------------
>     ufs_common       /scratch3/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/ufs-weather-model/modulefiles/ufs_common.lua
>     ufs_ursa.gnu     /scratch3/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/ufs-weather-model/modulefiles/ufs_ursa.gnu.lua
> ```

sorry about that @DusanJovic-NOAA. i installed mapl 2.53.3 with intel but forgot to do gcc. i built a gcc 12.4.0 stack and will add it there for testing.

2025-05-28 20:15 UTC, ulmononian commented
@DusanJovic-NOAA i just ran the gnu section of rt.conf on ursa with gnu/12.4.0 and mapl/2.53.4. all tests that ran passed. i used `-c` so some tests just didn't run because they don't generate baselines.

```
[1:12 PM](https://epic-slack-chan.slack.com/archives/D061P7GA0LD/p1748463128566409)
i ran with all gnu tests in conf file on ursa using -c. this is what log shows:

SYNOPSIS:
Starting Date/Time: 20250528 19:15:57
Ending Date/Time: 20250528 19:55:16
Total Time: 00h:39m:23s
Compiles Completed: 15/15
Tests Completed: 44/62

NOTES:
A file 'test_changes.list' was generated but is empty.
If you are using this log as a pull request verification, please commit 'test_changes.list'.

Result: SUCCESS

====END OF URSA REGRESSION TESTING LOG====
```

run dir: `/scratch4/NAGAPE/epic/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_3290258`

i will push changes for the gnu stack (@BrianCurtis-NOAA) and mapl version.

2025-05-29 14:47 UTC, JessicaMeixner-NOAA commented on modulefiles/ufs_common.lua
>    {["scotch"]          = "7.0.4"},
On Ursa are we planning to use 7.0.7 or 7.0.4 for SCOTCH? 

If i want to run on ursa and look at the wave failures, is this branch up to date? Should I be switching this to 7.0.7 or are there other updates needed and I should wait?

2025-05-29 16:05 UTC, RatkoVasic-NOAA commented on modulefiles/ufs_common.lua
>    {["scotch"]          = "7.0.4"},
@JessicaMeixner-NOAA , Cam is installing scotch@7.0.7 there. We are going to use 707 everywhere.

2025-05-29 16:33 UTC, JessicaMeixner-NOAA commented on modulefiles/ufs_common.lua
>    {["scotch"]          = "7.0.4"},
Thanks for letting me know.  Please let me know if there are any issues with SCOTCH on Ursa that need to be addressed after the new modules are installed.

2025-05-30 17:12 UTC, ulmononian commented on modulefiles/ufs_common.lua
>    {["scotch"]          = "7.0.4"},
@JessicaMeixner-NOAA i just updated ursa modulefiles for intel and gnu to use manual installs of scotch 707. you will need to manually make the code change from your pr (https://github.com/NOAA-EMC/WW3/pull/1425/files#diff-1a8086a966c850a21a149841c481cf914e993a0ac9409d289f73900ce4d2497d) for 707 to run on ursa (i dont have these changes in my remote branch).

2025-05-30 17:15 UTC, ulmononian commented
> @ulmononian there are indeed missing values in the gocart `.rc` files these will be needed for other tests than GEFS so even if you take them out these changes will be needed. You can see the changes necessary here:
> 
> ```shell
> /scratch4/NCEPDEV/naqfc/Barry.Baker/models/ufswm/tests/parm/gocart/gefs
> /scratch4/NCEPDEV/naqfc/Barry.Baker/models/ufswm/tests/parm/gocart/
> ```
> 
> I tried running the control_atmaero_p8 to test but the input data hasn't been stored in `/scratch4/NAGAPE/epic/role-epic/UFS-WM_RT/NEMSfv3gfs` yet

@bbakernoaa which .rc files need updated? there are a bunch...

@jkbk2004 @FernandoAndrade-NOAA can you sync up input data for ufs wm on ursa in /scratch4/NAGAPE/epic/role-epic/UFS-WM_RT/NEMSfv3gfs?

2025-05-30 17:48 UTC, bbakernoaa commented
namely the DU2G*.rc SS2G*.rc and CA2G*.rc files

2025-05-30 22:44 UTC, ulmononian commented
> namely the DU2G*.rc SS2G*.rc and CA2G*.rc files

i updated them. many were the same as what you have in your directories. everything look correct now?

2025-06-02 12:54 UTC, JessicaMeixner-NOAA commented on modulefiles/ufs_common.lua
>    {["scotch"]          = "7.0.4"},
Thanks @ulmononian  -  What code changes exactly are needed on my branch for that to run?  I'll test things out on my end, but I wasn't expecting my WW3 branch to require any changes for this.

2025-06-02 15:41 UTC, JessicaMeixner-NOAA commented on tests/rt.sh
> +    dprefix="/scratch4/NAGAPE/epic/${USER}"
FYI - I could not write to this directory, so I changed it for my testing to somewhere i can write.

2025-06-02 15:42 UTC, JessicaMeixner-NOAA commented
Is ecflow expected to work on ursa? Is there something I'm supposed to do on my end?  I just tried to use ecflow (and not even sure which ecflow node if it exists i should log into).  But the other platforms seem to do that for you if necessary for me, so I wasn't expecting to need to for Ursa, however perhaps there is some prep work I have forgotten about?

2025-06-02 15:47 UTC, BrianCurtis-NOAA commented
Might be missing logic here: https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt_utils.sh#L659 that will load ecflow.

for here, if ursa loads the hostname/port in when loading ecflow it might be overkill and cause issue: https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt.sh#L805-L806

2025-06-02 15:49 UTC, BrianCurtis-NOAA commented
As yes, also add ursa here: https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt_utils.sh#L685

2025-06-02 18:36 UTC, ulmononian commented
> As yes, also add ursa here: https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt_utils.sh#L685

@BrianCurtis-NOAA @JessicaMeixner-NOAA i made the two changes @BrianCurtis-NOAA suggested. does this look right? https://github.com/ufs-community/ufs-weather-model/pull/2471/commits/a12dc1e2c4b9be9e0d5c77432864721c1c6f827d

i did _not_ remove the ecflow lines in https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt.sh#L805-L806.

btw there is an ecflow node for ursa: `uecflow01           Ursa Ecflow Node`

2025-06-02 18:41 UTC, BrianCurtis-NOAA commented
> > As yes, also add ursa here: https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt_utils.sh#L685
> 
> @BrianCurtis-NOAA @JessicaMeixner-NOAA i made the two changes @BrianCurtis-NOAA suggested. does this look right? [a12dc1e](https://github.com/ufs-community/ufs-weather-model/commit/a12dc1e2c4b9be9e0d5c77432864721c1c6f827d)
> 
> i did _not_ remove the ecflow lines in https://github.com/ulmononian/ufs-weather-model/blob/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf/tests/rt.sh#L805-L806.
> 
> btw there is an ecflow node for ursa: `uecflow01 Ursa Ecflow Node`

This should be OK.

```
[Brian.Curtis@ufe04 ~]$ module load ecflow
ECF_HOST = uecflow01, ECF_PORT = 22097
ECF_HOST = uecflow01, ECF_PORT = 22097
[Brian.Curtis@ufe04 ~]$ id -u
20597
```
seems just loading ecflow does the same thing. It's redundant code, though.

2025-06-02 19:50 UTC, JessicaMeixner-NOAA commented
@ulmononian I was able to use ecflow on ursa after your updates. Thank you!

2025-06-02 20:46 UTC, ulmononian commented
update on ursa tests below. this was with scotch/7.0.7 (intel tests run with intel built scotch, gnu tests run with gnu built scotch.  @DeniseWorthen fyi)

```
Failing tests:

cpld_debug_gfsv17_intel
cpld_debug_pdlib_p8_intel
cpld_debug_gfsv17_intelllvm

hafs_global_multiple_4nests_atm_intel
```

@JessicaMeixner-NOAA this was with the changes from your ww3 pr included in my branch.

2025-06-02 20:49 UTC, JessicaMeixner-NOAA commented
Thanks @ulmononian  - I have replicated your cpld_debug_gfsv17_intel failure on Ursa, its the same as hercules/orion errors.  I'll look into the compile error of compile_s2swa_32bit_pdlib_debug_intelllvm -  I haven't seen that error to look for next steps yet.

2025-06-02 20:54 UTC, ulmononian commented
> Thanks @ulmononian - I have replicated your cpld_debug_gfsv17_intel failure on Ursa, its the same as hercules/orion errors. I'll look into the compile error of compile_s2swa_32bit_pdlib_debug_intelllvm - I haven't seen that error to look for next steps yet.

stand by...i forgot up update my ursa llvm lua file...

2025-06-02 21:01 UTC, ulmononian commented
> > Thanks @ulmononian - I have replicated your cpld_debug_gfsv17_intel failure on Ursa, its the same as hercules/orion errors. I'll look into the compile error of compile_s2swa_32bit_pdlib_debug_intelllvm - I haven't seen that error to look for next steps yet.
> 
> stand by...i forgot up update my ursa llvm lua file...

@JessicaMeixner-NOAA ok it compiles but `cpld_debug_gfsv17_intelllvm` still fails w/
```
forrtl: error (65): floating invalid
```

`/scratch4/NAGAPE/epic/Cameron.Book/RT_RUNDIRS/Cameron.Book/FV3_RT/rt_1140863`

2025-06-02 21:03 UTC, JessicaMeixner-NOAA commented
Thanks @ulmononian

2025-06-04 00:21 UTC, SamuelTrahanNOAA commented on modulefiles/ufs_ursa.intelllvm.lua
> +setenv("I_MPI_FC", "ifx")
You need to set all three fortran mpi compiler environment variables to ifx or it'll use the ifort compiler. At least, that's what I'm discovering in my project to port UPP to ursa.

```suggestion
setenv("I_MPI_FC", "ifx")
setenv("I_MPI_F90", "ifx")
setenv("I_MPI_F77", "ifx")
```

2025-06-05 19:39 UTC, ulmononian commented on modulefiles/ufs_ursa.intelllvm.lua
> +setenv("I_MPI_FC", "ifx")
thanks @SamuelTrahanNOAA. will make that change!

2025-06-06 00:31 UTC, ulmononian commented
@bbakernoaa @DeniseWorthen (@RatkoVasic-NOAA fyi) i am noticing a bunch of tests failing that were not failing before:

```
cpld_control_p8_mixedmode_intel
cpld_control_gefs_intel
cpld_control_p8_intel
cpld_control_p8.v2.sfc_intel
cpld_control_ciceC_p8_intel
cpld_control_c192_p8_intel
cpld_control_p8_lnd_intel
cpld_s2sa_p8_intel
cpld_debug_p8_intel
cpld_control_p8_faster_intel
```
i was wondering if the changes i made to the parm/gocart and parm/gocart/gefs files in commits https://github.com/ulmononian/ufs-weather-model/commit/38817d855fc4f4f8cd0729d5afab8b1e73dd08bf and https://github.com/ulmononian/ufs-weather-model/commit/6ecb98fc9b814e30659c783ac397935b2ca7d98f might be causing these failures? the `out` files for each quits here:

```
   0:  WARNING: falling back on MAPL NUM_BANDS
   0:  GOCART2G::Initialize: Starting...
   0:
   0:  Integer*4 Resource Parameter: RUN_DT:300
   0:  CA.oc::Initialize: Wet removal scheme is ufs
   0:  CA.bc::CA.oc::Initialize: Wet removal scheme is ufs
   0:  ===================>
   0:  MAPL_StateCreateFromSpecNew: var SU_NO3 already exists. Skipping ...
   0:  ===================>
   0:  MAPL_StateCreateFromSpecNew: var SU_OH already exists. Skipping ...
   0:  ===================>
   0:  MAPL_StateCreateFromSpecNew: var SU_H2O2 already exists. Skipping ...
   0:   oserver is not split
   0:
   0:  EXPSRC:GEOSgcm-v10.16.0
   0:  EXPID: gocart
   0:  Descr: GOCART2g_diagnostics_at_c360
   0:  DisableSubVmChecks: F
   0:
   0:  Reading HISTORY RC Files:
   0:  -------------------------
   0:  NOT using buffer I/O for file: AERO_HISTORY.rc
   0:  NOT using buffer I/O for file: inst_aod.rcx
   0:  NOT using buffer I/O for file: AERO_HISTORY.rc
   0:
   0:  Freq: 00060000  Dur: 00010000  TM:   -1  Collection: inst_aod
   0:
   0:  Independent Output Export States:
   0:  ---------------------------------
   0:            1 CA.bc
   0:            2 CA.oc
   0:            3 DU
   0:            4 SS
   0:            5 SU
   0:            6 GOCART2G
   0:
   0:  Initializing Output Stream: inst_aod
   0:  ---------------------------
   0:        Format: CFIO
   0:          Mode: instantaneous
   0:        Slices:           24
   0:       Deflate:            0
   0:     Frequency:        60000
   0:      Ref_Date:     20210325
   0:      Ref_Time:            0
   0:      Duration:        10000
   0:   Regrid Mthd: bilinear
   0:   Output RSLV:          720         361
   0:     XY-offset:            0   (DcPc: Dateline Center, Pole Center)
   0:       Fields: AOD_BC AOD_OC AOD_DU AOD_SS AOD_SU AOD
   0:
   0:
   0:    EXTDATA: EXTDATA::Initialize_: ACTIVE
   0:
   0:    EXTDATA: ExtData could not satisfy import DU_SRC
```

and most `err` files show the failure at

```
  2: pe=00002 FAIL at line=00786    ExtDataGridCompMod.F90                   <Found   1 unfulfilled imports in extdata>
 11: pe=00011 FAIL at line=00786    ExtDataGridCompMod.F90                   <Found   1 unfulfilled imports in extdata>
 11: pe=00011 FAIL at line=01862    MAPL_Generic.F90                         <status=1>
 11: pe=00011 FAIL at line=00716    MAPL_CapGridComp.F90                     <status=1>
 94: pe=00094 FAIL at line=00786    ExtDataGridCompMod.F90                   <Found   1 unfulfilled imports in extdata>
 94: pe=00094 FAIL at line=01862    MAPL_Generic.F90                         <status=1>
```

2025-06-09 18:21 UTC, bbakernoaa commented
@ulmononian did you resolve this or is the gocart .rc files still an issue?

2025-06-09 18:24 UTC, ulmononian commented
> @ulmononian did you resolve this or is the gocart .rc files still an issue?

i reverted some changes and the tests seem ok now.

2025-06-11 20:54 UTC, rickgrubin-noaa commented
@ulmononian 

`spack-stack@1.9.2rc2` 

- `oneAPI`
  - `/contrib/spack-stack/spack-stack-1.9.2rc2/envs/ue-oneapi-2024.2.1/install/modulefiles/Core`
  - will also need the following for `GCC`-built packages in the `oneAPI` env:
    - `/contrib/spack-stack/spack-stack-1.9.2rc2/envs/ue-oneapi-2024.2.1/install/modulefiles/intel-oneapi-mpi/2021.13-haww6b3/gcc/11.4.1`
- `GCC`
  - `/contrib/spack-stack/spack-stack-1.9.2rc2/envs/ue-gcc-11.4.1/install/modulefiles/Core`

2025-06-11 23:04 UTC, ulmononian commented
@DeniseWorthen @BrianCurtis-NOAA @jkbk2004 is there a reason why `control_csawmg_debug` is inside the Intel section of `rt.conf` and not in the GNU section (i.e.: https://github.com/ufs-community/ufs-weather-model/blob/9193010aa52f17a7b3618fd75b4e3c03a79c3c59/tests/rt.conf#L211-L213C1)? the "### DEBUG ATM tests ###" section is duplicated right after the intel section and just contains this one gnu test. there's probably a reason i am unaware of, but wanted to correct this if needed in this PR.

2025-06-12 00:14 UTC, DeniseWorthen commented
@ulmononian I know of no reason it should be in the intel section. We used to have a separate gnu rt.conf but they got merged; certainly it is easier if all the GNU tests are located in one section. 

We have the same issue for one of the cpld tests (although the test is currently commented out). It should also be moved to the GNU section

https://github.com/ufs-community/ufs-weather-model/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fufs-community%2Fufs-weather-model%2Fblob%2F9193010aa52f17a7b3618fd75b4e3c03a79c3c59%2Ftests%2Frt.conf%23L37-L38

2025-06-12 18:16 UTC, ulmononian commented
@jkbk2004 @RatkoVasic-NOAA @rickgrubin-noaa all intel/gnu tests pass with the 1.9.2rc2 updates (except for `hafs_global_multiple_4nests_atm_intel`)

2025-06-12 19:47 UTC, ulmononian commented
> @ulmononian I know of no reason it should be in the intel section. We used to have a separate gnu rt.conf but they got merged; certainly it is easier if all the GNU tests are located in one section.
> 
> We have the same issue for one of the cpld tests (although the test is currently commented out). It should also be moved to the GNU section
> 
> https://github.com/ufs-community/ufs-weather-model/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fufs-community%2Fufs-weather-model%2Fblob%2F9193010aa52f17a7b3618fd75b4e3c03a79c3c59%2Ftests%2Frt.conf%23L37-L38

i moved both of these back to the GNU section.

2025-06-17 19:26 UTC, BrianCurtis-NOAA commented
I ran a test using ecflow from this PR and there was an issue getting ecflow started.

The crux of the issue is that on Hera, the ECF_PORT and ECF_HOST were set when loading the ecflow module. This is not the case (yet, at least) for Ursa.

Since, for Ursa, the rt_utils.sh script uses the ecflow_start.sh script from ecflow but doesn't have an ECF_HOST set, the script automatically fails and you can't continue with the rt.sh script.

Here is a temporary fix for rt_utils.sh around line 684 in case Ursa SA's don't get that adjustment made:
```
    case ${MACHINE_ID} in
      wcoss2|acorn|hera|jet)
        #shellcheck disable=SC2029
        ssh "${ECF_HOST}" "bash -l -c \"module load ecflow && ${ECFLOW_START} -p ${ECF_PORT}\""
        ;;
      ursa)
        #shellcheck disable=SC2029
        ssh "${ECF_HOST}" "bash -l -c \"module load ecflow && export ECF_HOST=${ECF_HOST} && ${ECFLOW_START} -p ${ECF_PORT}\""
        ;;
      *)
        ${ECFLOW_START} -p "${ECF_PORT}" -d "${RUNDIR_ROOT}/ecflow_server"
        ;;
    esac
```

2025-06-17 22:39 UTC, ulmononian commented
> ursa)
>         #shellcheck disable=SC2029
>         ssh "${ECF_HOST}" "bash -l -c \"module load ecflow && export ECF_HOST=${ECF_HOST} && ${ECFLOW_START} -p ${ECF_PORT}\""
>         ;;

@BrianCurtis-NOAA awesome -- thanks for this fix! i updated `rt_utils.sh`. @FernandoAndrade-NOAA please try ecflow again on ursa and let me know if this resolves the issue you were seeing.

2025-06-18 17:33 UTC, ulmononian commented
FYI to those tracking this PR:

i installed spack-stack/1.9.2 (Intel & GCC). all tests that generate baselines (using `-c`) pass. this includes the resolution of `hafs_global_multiple_4nests_atm_intel` (thanks to @BinLiu-NOAA).

the new stack locations are in the updated modulefiles for this branch. 

@jkbk2004 this PR is basically ready to go once 192 is ready on other machines.

2025-07-03 16:50 UTC, jkbk2004 commented
@ulmononian can you sync up branch?

2025-07-03 20:33 UTC, DavidHuber-NOAA commented
Any chance that the FV3/upp submodule could be updated for this PR?  It has been updated to add Ursa/spack-stack 1.9.2 support.

2025-07-03 20:37 UTC, ulmononian commented
> @ulmononian can you sync up branch?

NSYNC

2025-07-03 20:38 UTC, ulmononian commented
> Any chance that the FV3/upp submodule could be updated for this PR? It has been updated to add Ursa/spack-stack 1.9.2 support.

@DavidHuber-NOAA i would be ok updating the submodule in this pr. @jkbk2004 what do you think?

2025-07-07 11:14 UTC, BrianCurtis-NOAA commented
As long as this runs OK on Ursa, I don't see the need to re-run on multiple machines as all changes are Ursa specific. Did you re-test the timed out tests?

2025-07-07 12:16 UTC, jkbk2004 commented
> As long as this runs OK on Ursa, I don't see the need to re-run on multiple machines as all changes are Ursa specific. Did you re-test the timed out tests?

I agree: no need to test across machines and sanity check was done ok on hercules. We can merge with final reviews.

2025-07-07 12:17 UTC, jkbk2004 approved these changes, later dismissed

2025-07-07 12:20 UTC, BrianCurtis-NOAA requested changes
@jkbk2004 the Ursa log did not pass (contrary to the commit message). Have those been re-tested?

2025-07-07 12:29 UTC, jkbk2004 commented
> @jkbk2004 the Ursa log did not pass (contrary to the commit message). Have those been re-tested?

@BrianCurtis-NOAA let me re-submit jobs for those timed-out cases.

2025-07-07 12:49 UTC, DeniseWorthen commented
Are we really approving PRs with failed logs?

2025-07-07 14:14 UTC, jkbk2004 commented
@FernandoAndrade-NOAA can you try these two cases for time-out issue?
```
cpld_dcp_gefs intel
regional_2threads intel
```

2025-07-07 14:22 UTC, DeniseWorthen commented
Why were these time-outs not see during testing by @ulmononian ? What changed?

2025-07-07 15:40 UTC, jkbk2004 commented
```
PASS -- COMPILE 's2swa_32bit_intel' [15:11, 13:38] ( 1 warnings 1038 remarks )
PASS -- TEST 'cpld_dcp_gefs_intel' [54:03, 34:37](3443 MB)

PASS -- COMPILE 'atm_dyn32_intel' [12:11, 10:21] ( 1 warnings 476 remarks )
PASS -- TEST 'regional_2threads_intel' [23:35, 20:12](1556 MB)
```
Certainly, over the current wlkclk time limits.

2025-07-07 15:48 UTC, ulmononian commented
> Why were these time-outs not see during testing by @ulmononian ? What changed?

unknown. i think we need to monitor ursa's performance over the coming months. not sure if it is stable yet. but i would not hold back an entire machine for two tests.

2025-07-07 15:57 UTC, BrianCurtis-NOAA commented
> > Why were these time-outs not see during testing by @ulmononian ? What changed?
> 
> unknown. i think we need to monitor ursa's performance over the coming months. not sure if it is stable yet. but i would not hold back an entire machine for two tests.

If the increase in wallclock and memory is seen across the board in testing, then it might benefit reviewing the job cards to see if there are tweaks that can be made based on Ursa's configuration, might need to talk to the SA's.

In our tag-up we decided to increase the WLCLK for those two tests to allow them to run to completion until the issue can be addressed.

Please make room in your sprints to address this soon.

2025-07-07 16:21 UTC, DeniseWorthen commented
@BrianCurtis-NOAA Agreed. It was one of the motivations in #2527. Maybe someone from EPIC provide a time-line for this to be implemented?

2025-07-07 17:00 UTC, jkbk2004 commented
https://github.com/ufs-community/ufs-weather-model/issues/2792

2025-07-07 17:26 UTC, jkbk2004 approved these changes, later dismissed

2025-07-07 17:46 UTC, BrianCurtis-NOAA commented
@jkbk2004 one last adjustment, can you edit the pull_request template to add Ursa (and remove Jet) ?

2025-07-07 17:55 UTC, jkbk2004 approved these changes

2025-07-07 17:57 UTC, FernandoAndrade-NOAA approved these changes

2025-07-07 18:05 UTC, BrianCurtis-NOAA approved these changes

2025-07-07 18:12 UTC, FernandoAndrade-NOAA commented on modulefiles/ufs_ursa.intelllvm.lua
> +setenv("I_MPI_FC", "ifx")
@ulmononian please verify and mark as resolved, thank you.

2025-07-07 18:15 UTC, FernandoAndrade-NOAA commented on tests/rt.sh
> +    dprefix="/scratch4/NAGAPE/epic/${USER}"
Marking as resolved, dprefix now defaults to /scratch4/NCEPDEV/stmp/${USER}

2025-07-07 19:07 UTC, merged

2025-07-08 17:40 UTC, dustinswales commented on tests/tests/cpld_dcp_gefs
> +if
@jkbk2004 @BrianCurtis-NOAA This is incorrect and the RTs fail on Hera. Should be `fi`, no `if`

2025-07-08 17:40 UTC, dustinswales commented on tests/tests/regional_2threads
> +if
@jkbk2004 @BrianCurtis-NOAA This is incorrect and the RTs fail on Hera. Should be `fi`, not `if`

2025-07-08 17:49 UTC, jkbk2004 commented on tests/tests/regional_2threads
> +if
Fix is coming with https://github.com/ufs-community/ufs-weather-model/pull/2795. Hopefully, by late this afternoon or tomorrow morning first thing.