DRAFT: UGWP v0 v1 combined
ufs-community/ufs-weather-model pull request #396
Opened 2021-01-26 22:32 UTC by climbfuji

# PLACEHOLDER FOR @mdtoy to work with me on resolving some issues

## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.
What bug does it fix, or what feature does it add?
Is a change of answers expected from this PR?
Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?
What compilers / HPCs was it tested with?
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

2021-02-12 14:52 UTC, DeniseWorthen commented
The wamstart test is not set up for or intended to be a restart test, right?

2021-02-12 14:54 UTC, climbfuji commented
> The wamstart test is not set up for or intended to be a restart test, right?

No, it's just warmstart files as input.

2021-02-12 20:45 UTC, climbfuji commented
@MinsukJi-NOAA CI tests passed after I pulled in your changes, thanks!

2021-02-16 15:05 UTC, DusanJovic-NOAA approved these changes

2021-02-16 15:09 UTC, BrianCurtis-NOAA requested changes
try to use `raise` instead of `sys.exit`. There's some default exception types that cover some of these like `TypeError` or `KeyError`. Simplest is just `raise Exception('explanation here')`

2021-02-16 15:09 UTC, BrianCurtis-NOAA commented on tests/compare_ncfile.py
> +      sys.exit(2)
raise

2021-02-16 15:09 UTC, BrianCurtis-NOAA commented on tests/compare_ncfile.py
> +        sys.exit(2)
raise

2021-02-16 15:09 UTC, BrianCurtis-NOAA commented on tests/compare_ncfile.py
> +    sys.exit(2)
should use raise instead of sys.exit()

2021-02-16 15:14 UTC, climbfuji commented
> try to use `raise` instead of `sys.exit`. There's some default exception types that cover some of these like `TypeError` or `KeyError`. Simplest is just `raise Exception('explanation here')`

@MinsukJi-NOAA FYI

I would prefer to make this change in a future PR, because it will require rerunning the regression tests.

2021-02-16 15:22 UTC, BrianCurtis-NOAA commented
> > try to use `raise` instead of `sys.exit`. There's some default exception types that cover some of these like `TypeError` or `KeyError`. Simplest is just `raise Exception('explanation here')`
> 
> @MinsukJi-NOAA FYI
> 
> I would prefer to make this change in a future PR, because it will require rerunning the regression tests.

This is fine with me.

2021-02-16 15:23 UTC, MinsukJi-NOAA commented
> > try to use `raise` instead of `sys.exit`. There's some default exception types that cover some of these like `TypeError` or `KeyError`. Simplest is just `raise Exception('explanation here')`
> 
> @MinsukJi-NOAA FYI
> 
> I would prefer to make this change in a future PR, because it will require rerunning the regression tests.

OK. I will note this for future improvements.

2021-02-16 15:23 UTC, BrianCurtis-NOAA approved these changes

2021-02-16 15:25 UTC, climbfuji commented
> > > try to use `raise` instead of `sys.exit`. There's some default exception types that cover some of these like `TypeError` or `KeyError`. Simplest is just `raise Exception('explanation here')`
> > 
> > 
> > @MinsukJi-NOAA FYI
> > I would prefer to make this change in a future PR, because it will require rerunning the regression tests.
> 
> This is fine with me.

Thanks, Brian and Minsuk.

2021-02-16 17:49 UTC, climbfuji commented
PR is ready for merging, CI tests have just been kicked off.

2021-02-16 17:51 UTC, junwang-noaa approved these changes

2021-02-16 17:55 UTC, MinsukJi-NOAA approved these changes

2021-02-16 20:34 UTC, climbfuji commented
@junwang-noaa @DusanJovic-NOAA CI tests passed, please merge when you are ready. Thanks!

2021-02-16 20:41 UTC, merged