Add 'netcdf' and 'grib2' to IC input source options in regional IC/LBC routines (re-opened)
ufs-community/ufs-weather-model pull request #567
Opened 2021-05-10 19:17 UTC by chan-hoo

## Description
- Add 'netcdf' and 'grib2' to the IC input source options in the regional IC/LBC routines of 'atmos_cubed_sphere'.
- Re-opend PR of https://github.com/ufs-community/ufs-weather-model/pull/526.

### Issue(s) addressed
- Fixes #523 
- Fixes https://github.com/NOAA-EMC/fv3atm/issues/281
- Fixes https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/97

## Testing
- Passed the regression test of the ufs weather model on WCOSS (dell/cray) and Hera with intel compiler.
- Completed a LAMDA test successfully with 'netcdf' input files from GFS.

Regression tests:
- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies
- https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/96
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/297

## Contributors
@JamesAbeles-NOAA, @EricRogers-NOAA

2021-05-10 19:33 UTC, MinsukJi-NOAA commented
This is a new PR for #526

2021-05-10 21:11 UTC, DusanJovic-NOAA approved these changes

2021-05-11 01:57 UTC, BrianCurtis-NOAA commented
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/638266410/20210510210015/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_261147
Test cpld_bmarkfrac_wave_v16 025 failed failed 
Test cpld_bmarkfrac_wave_v16 025 failed in run_test failed 
Test cpld_bmarkfrac_v16_nsst 021 failed in run_test failed 
Test cpld_bmarkfrac 018 failed in run_test failed 
Test cpld_bmarkfrac_v16 020 failed in run_test failed 
Test compile 013 failed failed 
Test compile 016 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 076 failed in run_test failed 
Test fv3_gfsv16_csawmgt 072 failed in run_test failed 
Test fv3_gfsv16_csawmg 071 failed in run_test failed 
Test datm_debug_cfsr 102 failed in run_test failed 
Test datm_mx025_cfsr 100 failed in run_test failed 
Test datm_mx025_gefs 101 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

2021-05-11 06:17 UTC, BrianCurtis-NOAA commented
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/638266410/20210511023009/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_12752
Test fv3_wrtGauss_netcdf_esmf 033 failed in run_test failed 
Test cpld_control_c384 012 failed in run_test failed 
Test fv3_regional_quilt 050 failed in run_test failed 
Test fv3_gfs_v16_stochy 069 failed failed 
Test fv3_gfs_v16_stochy 069 failed in run_test failed 
Test fv3_gsd_diag3d_debug 086 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

2021-05-11 11:40 UTC, MinsukJi-NOAA commented
The following Orion tests failed due to being timed out:
fv3_gfsv16_csawmg 076 failed in run_test
cpld_bmark 017 failed in run_test
cpld_control_c384 013 failed in run_test
cpld_controlfrac_c384 015 failed in run_test
cpld_control_c192 009 failed in run_test

The failed tests on jet above also seem mostly time out issue.

2021-05-11 13:51 UTC, BrianCurtis-NOAA commented
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/638266410/20210511071508/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_20636
Test cpld_ca 008 failed in run_test failed 
Test cpld_decomp 006 failed in run_test failed 
Test cpld_debug 028 failed in run_test failed 
Test cpld_controlfrac 003 failed in run_test failed 
Test cpld_control_c384 013 failed in run_test failed 
Test cpld_control_wave 027 failed in run_test failed 
Test cpld_2threads 005 failed in run_test failed 
Test cpld_satmedmf 007 failed in run_test failed 
Test cpld_debugfrac 029 failed in run_test failed 
Test cpld_control 001 failed in run_test failed 
Test cpld_controlfrac_c192 011 failed in run_test failed 
Test cpld_controlfrac_c384 015 failed in run_test failed 
Test fv3_lndp 043 failed in run_test failed 
Test fv3_stochy 041 failed in run_test failed 
Test fv3_wrtGauss_nemsio_c192 040 failed in run_test failed 
Test fv3_iau 044 failed in run_test failed 
Test fv3_restart 033 failed in run_test failed 
Test fv3_read_inc 034 failed in run_test failed 
Test fv3_lheatstrg 045 failed in run_test failed 
Test cpld_control_c192 009 failed in run_test failed 
Test fv3_ca 042 failed in run_test failed 
Test cpld_bmarkfrac_v16_nsst 022 failed in run_test failed 
Test cpld_bmarkfrac_wave_v16 026 failed in run_test failed 
Test cpld_bmark_wave 024 failed in run_test failed 
Test cpld_bmark 017 failed in run_test failed 
Test cpld_bmarkfrac_wave 025 failed in run_test failed 
Test cpld_bmarkfrac_v16 021 failed in run_test failed 
Test cpld_bmarkfrac 019 failed in run_test failed 
Test fv3_wrtGauss_nemsio 039 failed in run_test failed 
Test fv3_2threads 032 failed in run_test failed 
Test fv3_gfdlmprad_noahmp 058 failed in run_test failed 
Test fv3_gfdlmprad_gwd 057 failed in run_test failed 
Test fv3_gfdlmp 056 failed in run_test failed 
Test fv3_satmedmfq 061 failed in run_test failed 
Test fv3_satmedmf 060 failed in run_test failed 
Test fv3_csawmg 059 failed in run_test failed 
Test fv3_regional_quilt_netcdf_parallel 054 failed in run_test failed 
Test fv3_regional_quilt 052 failed in run_test failed 
Test fv3_regional_quilt_hafs 053 failed in run_test failed 
Test fv3_regional_quilt_RRTMGP 055 failed in run_test failed 
Test fv3_regional_control 050 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

2021-05-11 14:17 UTC, DeniseWorthen commented
These all show " CANCELLED by 8555" when they tried to run. But I don't see any real clue what that means. 

```
Slurm unknown status -. Check sacct ...
2004946         CANCELLED by 8555         rt_20636_001
32 min. TEST 001 cpld_control is CANCELLED,  status: - jobid 2004946
```

2021-05-11 14:19 UTC, MinsukJi-NOAA commented
> These all show " CANCELLED by 8555" when they tried to run. But I don't see any real clue what that means.
> 
> ```
> Slurm unknown status -. Check sacct ...
> 2004946         CANCELLED by 8555         rt_20636_001
> 32 min. TEST 001 cpld_control is CANCELLED,  status: - jobid 2004946
> ```

@BrianCurtis-NOAA canceled all jobs I submitted this morning at my request. I identified 10 failed tests from yesterday on Orion, and just submitted rt jobs.

2021-05-11 14:20 UTC, DeniseWorthen commented
Oh, I understand now. I thought these were more failing jobs.

2021-05-12 02:41 UTC, junwang-noaa approved these changes

2021-05-12 12:51 UTC, MinsukJi-NOAA commented
@chan-hoo, once the related fv3 PR (https://github.com/NOAA-EMC/fv3atm/pull/297) is committed, you can change the fv3 pointer in gitmodules.

2021-05-12 13:24 UTC, junwang-noaa commented
fv3 PR is committed

On Wed, May 12, 2021 at 8:52 AM Minsuk Ji ***@***.***> wrote:

> @chan-hoo <https://github.com/chan-hoo>, once the related fv3 PR (
> NOAA-EMC/fv3atm#297 <https://github.com/NOAA-EMC/fv3atm/pull/297>) is
> committed, you can change the fv3 pointer in gitmodules.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/567#issuecomment-839746528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI7D6TLJ2OF5S7ACQNUPGLTTNJ2X5ANCNFSM44SA47NQ>
> .
>

2021-05-12 13:36 UTC, MinsukJi-NOAA commented
We are good to go.

2021-05-12 13:37 UTC, climbfuji requested changes
I don't see the fv3atm submodule pointer update. Must point to hash 345915a

2021-05-12 13:39 UTC, MinsukJi-NOAA commented
> I don't see the fv3atm submodule pointer update. Must point to hash 345915a

Good catch, Dom. @chan-hoo, did you submodule sync?

2021-05-12 13:43 UTC, climbfuji approved these changes
I approve with the understanding that the submodule pointer will be fixed as requested before merging.

2021-05-12 13:50 UTC, MinsukJi-NOAA commented
> I approve with the understanding that the submodule pointer will be fixed as requested before merging.

It's been done. Kindly check one more time @DomHeinzeller

2021-05-12 14:06 UTC, junwang-noaa commented
The revision looks good now.

2021-05-12 14:18 UTC, merged