Feature/truefalse
ufs-community/ufs-weather-model pull request #733
Opened 2021-08-04 19:59 UTC by DeniseWorthen

# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

Tested on gaea.intel; all baselines b4b

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies

None

2021-08-12 19:47 UTC, climbfuji requested changes
Thanks for making these changes, tedious job.

I noted that the choice of using quotes around the values ini expressions like
```
export WARM_START='.false.'
```
are all over the place. No quotes, single quotes `'`, double quotes `"` are used. This is not a result of this PR, but something that could be cleaned up in a future PR.

2021-08-12 19:47 UTC, climbfuji commented on tests/default_vars.sh
> +export LNDP_VAR_LIST=XXX
This is a list of strings, why no quotes around `XXX`? Seems that many other strings in `default_vars.sh` have quotes around them, but many not (ATMRES, for example). Should this be made consistent, too?

2021-08-12 19:47 UTC, climbfuji commented on tests/parm/c96_HAFS_v0_hwrf.nml.IN
> +  hurr_pbl       = .true.           ! HWRF moninedmf
Please adjust whitespaces

2021-08-12 19:47 UTC, climbfuji commented on tests/parm/esg_HAFS_v0_hwrf.nml.IN
> +  hurr_pbl       = .true.           ! HWRF moninedmf
Please adjust whitespaces

2021-08-12 20:18 UTC, SMoorthi-emc commented
Quotes are unnecessary 

Sent from my iPhone

> On Aug 12, 2021, at 3:47 PM, Dom Heinzeller ***@***.***> wrote:
> 
> @climbfuji requested changes on this pull request.
> 
> Thanks for making these changes, tedious job.
> 
> I noted that the choice of using quotes around the values ini expressions like
> 
> export WARM_START='.false.'
> are all over the place. No quotes, single quotes ', double quotes " are used. This is not a result of this PR, but something that could be cleaned up in a future PR.
> 
> In tests/default_vars.sh:
> 
> >  export SKEB=-999.
>  export SPPT=-999.
>  export SHUM=-999.
> -export LNDP_VAR_LIST='XXX'
> +export LNDP_VAR_LIST=XXX
> This is a list of strings, why no quotes around XXX? Seems that many other strings in default_vars.sh have quotes around them, but many not (ATMRES, for example). Should this be made consistent, too?
> 
> In tests/parm/c96_HAFS_v0_hwrf.nml.IN:
> 
> > @@ -122,7 +122,7 @@
>    hwrf_samfshal  = .true.        ! HWRF SASshal
>    asolfac_deep   = 0.89          ! HWRF SASdeep; GFS SAS:0.958
>    asolfac_shal   = 0.89          ! HWRF SASdeep; GFS SAS:0.958
> -  hurr_pbl       = .T.           ! HWRF moninedmf
> +  hurr_pbl       = .true.           ! HWRF moninedmf
> Please adjust whitespaces
> 
> In tests/parm/esg_HAFS_v0_hwrf.nml.IN:
> 
> > @@ -131,7 +131,7 @@
>    hwrf_samfshal  = .true.        ! HWRF SASshal
>    asolfac_deep   = 0.89          ! HWRF SASdeep; GFS SAS:0.958
>    asolfac_shal   = 0.89          ! HWRF SASdeep; GFS SAS:0.958
> -  hurr_pbl       = .T.           ! HWRF moninedmf
> +  hurr_pbl       = .true.           ! HWRF moninedmf
> Please adjust whitespaces
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-12 20:24 UTC, DeniseWorthen commented on tests/parm/esg_HAFS_v0_hwrf.nml.IN
> +  hurr_pbl       = .true.           ! HWRF moninedmf
@climbfuji I don't understand the issue you pointed out about quotes in default_vars. Are you saying that there should be quotes? I tried to clean up default_vars for quotes, leaving only those where quotes separated values ("'atm' 'sfc'"). I didn't tackle quotes inside the tests yet.

I will fix the whitespaces

2021-08-12 20:26 UTC, climbfuji commented on tests/parm/esg_HAFS_v0_hwrf.nml.IN
> +  hurr_pbl       = .true.           ! HWRF moninedmf
Sorry if my comments weren't clear, let's ignore the quotes for now. Thanks for fixing the whitespaces.

2021-08-12 20:30 UTC, climbfuji approved these changes

2021-08-13 15:28 UTC, BrianCurtis-NOAA approved these changes
Good to start RT

2021-08-13 15:30 UTC, DeniseWorthen commented
@jiandewang can you start the wcoss dell and cray RTs? Thanks.

2021-08-13 15:39 UTC, jiandewang commented
> @jiandewang can you start the wcoss dell and cray RTs? Thanks.

@DeniseWorthen will do right away

2021-08-13 16:04 UTC, jiandewang commented
@DeniseWorthen jobs are running on Cray but I am having trouble to compile on P3.
Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "yafyaml/v0.5.1", "mapl/v2.7.3"
   Try: "module spider yafyaml/v0.5.1 mapl/v2.7.3" to see how to load the
module(s).

Executing this command requires loading "yafyaml/v0.5.1" which failed while
processing the following module(s):

or you can see at /gpfs/dell2/ptmp/Jiande.Wang/FV3_RT/rt_39159/compile_001

2021-08-13 16:24 UTC, jiandewang commented
@DeniseWorthen cray job done, I scp log to HERA at
/scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/UFS-PR-log/RegressionTests_wcoss_cray.log

2021-08-13 16:37 UTC, BrianCurtis-NOAA commented
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/703937343/20210813153018/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_31643
Test hafs_regional_docn 086 failed failed 
Test hafs_regional_docn 086 failed in run_test failed 
Test hafs_regional_docn_oisst 087 failed failed 
Test hafs_regional_docn_oisst 087 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

2021-08-13 16:43 UTC, DeniseWorthen commented
@jiandewang We're killing all the auto-RT jobs because MOM6 is actually not pointing to your PR branch. That shouldn't explain your module load errors on Dell though.

2021-08-13 16:43 UTC, BrianCurtis-NOAA commented
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/703937343/20210813103013/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_252220
Test cpld_restart_bmark_v16 011 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

2021-08-13 16:46 UTC, BrianCurtis-NOAA commented
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/703937343/20210813094509/ufs-weather-model
Please make changes and add the following label back:
cheyenne-gnu-RT

2021-08-13 16:47 UTC, BrianCurtis-NOAA commented
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/703937343/20210813093009/ufs-weather-model
Please make changes and add the following label back:
cheyenne-intel-RT

2021-08-13 16:47 UTC, BrianCurtis-NOAA commented
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/703937343/20210813153015/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_19974
Test compile 014 failed failed 
Test compile 019 failed failed 
Please make changes and add the following label back:
hera-intel-RT

2021-08-13 16:48 UTC, BrianCurtis-NOAA commented
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/703937343/20210813153012/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_168959
Test control_c192 024 failed failed 
Test control_2threads 018 failed failed 
Test control_c192 024 failed in run_test failed 
Test control_2threads 018 failed in run_test failed 
Test datm_bulk_cfsr 091 failed in run_test failed 
Test datm_bulk_gefs 092 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 081 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 079 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 078 failed in run_test failed 
Test cpld_control_wave 014 failed in run_test failed 
Test datm_mx025_cfsr 093 failed in run_test failed 
Test datm_mx025_gefs 094 failed in run_test failed 
Test datm_control_gefs 089 failed in run_test failed 
Test datm_control_cfsr 087 failed in run_test failed 
Test control_thompson_debug 072 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 080 failed in run_test failed 
Test datm_control_iau_gefs 090 failed in run_test failed 
Test control_thompson_extdiag_debug 074 failed in run_test failed 
Test fv3_gsd_debug 076 failed in run_test failed 
Test fv3_gsd_diag_debug 077 failed in run_test failed 
Test regional_control_debug 075 failed in run_test failed 
Test cpld_bmark_wave_v16_p7b 013 failed in run_test failed 
Test cpld_bmark_wave_v16 012 failed in run_test failed 
Test cpld_bmark_v16_nsst 011 failed in run_test failed 
Test cpld_restart_c384 008 failed in run_test failed 
Test cpld_restart_bmark_v16 010 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

2021-08-13 16:51 UTC, jiandewang commented
@DeniseWorthen it is pointing to the right MOM branch
https://github.com/DeniseWorthen/ufs-weather-model/blob/feature/truefalse/.gitmodules#L33-L34
or did you just changed that ?

2021-08-13 16:52 UTC, DeniseWorthen commented
The branch name is correct, but the has points to the top of develop.

2021-08-13 16:55 UTC, jiandewang commented
@DeniseWorthen now I see the problem, let me know when it's updated and I will re-do my wcoss run

2021-08-13 17:08 UTC, DeniseWorthen commented
The hafs tests on gaea failed because they use ``WLCLK_dflt`` which is set to 15mins. Both runs timed out. The hafs DATM tests use WLCLK=30 explicitly.

2021-08-13 17:10 UTC, DeniseWorthen commented
@DusanJovic-NOAA There seems to be a module load error on dell-p3, saying that netcdf-4.7.4 is not found.

2021-08-13 17:17 UTC, DeniseWorthen commented
@jiandewang Please confirm MOM6 now points to the correct feature branch

2021-08-13 17:21 UTC, jiandewang commented
@DeniseWorthen checked one minute ago, it is correct one now. Thanks.
So is it the right time for me to rerun on CRAY now ?

2021-08-13 17:23 UTC, DeniseWorthen commented
@jiandewang Not yet. We are trying to get to the bottom of the module issue on Dell.

2021-08-13 17:34 UTC, MinsukJi-NOAA approved these changes

2021-08-13 17:34 UTC, MinsukJi-NOAA commented on tests/default_vars.sh
> +export LNDP_VAR_LIST=XXX
Looks to me the single quotes may need to stay. For example:
```
control_ca:50:export LNDP_VAR_LIST="'XXX'"
control_ca_debug:44:export LNDP_VAR_LIST="'XXX'"
control_lndp:51:export LNDP_VAR_LIST="'smc' , 'vgf',"
control_lndp_debug:46:export LNDP_VAR_LIST="'smc' , 'vgf',"
```

2021-08-13 17:52 UTC, DeniseWorthen commented
@MinsukJi-NOAA Thanks, I can re-enable quotes on the LNDP_VAR_LIST. I see now it does specifically call it a "list", which does imply it might have multiple items separated by spaces.

2021-08-13 19:08 UTC, DeniseWorthen commented
@jiandewang could you please try on dell again? Since I updated MOM and changed one thing in default_vars, please be sure you try the updated PR.

2021-08-13 19:14 UTC, jiandewang commented
> @jiandewang could you please try on dell again? Since I updated MOM and changed one thing in default_vars, please be sure you try the updated PR.

OK will try

2021-08-13 19:29 UTC, jiandewang commented
> > @jiandewang could you please try on dell again? Since I updated MOM and changed one thing in default_vars, please be sure you try the updated PR.
> 
> OK will try

I think this fixed the issue, some of the compiling jobs have been done

2021-08-13 19:29 UTC, jiandewang commented
@DeniseWorthen shall I start the full RT now ?

2021-08-13 19:31 UTC, DeniseWorthen commented
@jiandewang Yes please. Thanks.

2021-08-13 20:31 UTC, jiandewang commented
@DeniseWorthen  rerun on cray, see RT log on HERA at /scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/UFS-PR-log
  dell is still running at this moment

2021-08-13 21:31 UTC, jiandewang commented
got disk quota issue on P3, re-running now

2021-08-13 23:47 UTC, BrianCurtis-NOAA commented
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/703937343/20210813210012/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_141404
Test hafs_regional_atm 082 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

2021-08-14 00:56 UTC, jiandewang commented
RT jobs on dell P3 have failed 4 times due to disk quota

2021-08-14 00:57 UTC, BrianCurtis-NOAA commented
@jiandewang what ACCNR are you using?

2021-08-14 00:59 UTC, jiandewang commented
> @jiandewang what ACCNR are you using?

CFS-DEV

2021-08-14 01:00 UTC, jiandewang commented
let me try to use stmp, ptmp is almost full

2021-08-14 01:13 UTC, BrianCurtis-NOAA commented
@DeniseWorthen Jet was a slurm failure, i'll add the label for the RT again. Cheyenne was jobs sitting again, so i moved them to the premium queue and they finished. I didn't want them to get removed early AM tomorrow.
@jiandewang I will try with my ACCNR as well to see if it will finish OK. Will update in the AM if i don't hear from you beforehand

2021-08-14 03:30 UTC, jiandewang commented
@DeniseWorthen  finally finished on dell, see RT log on HERA at /scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/UFS-PR-log

2021-08-16 13:00 UTC, climbfuji commented
ufs-weather-model now points to hash f8a8e4c of MOM6, which is the head of the default branch. Seems ok.

2021-08-16 13:01 UTC, merged