RRTMGP updates and bugfixes
ufs-community/ufs-weather-model pull request #820
Opened 2021-09-21 19:15 UTC by dustinswales

## Description
This PR contains changes to RRTMGP in FV3/ccpp-physics. No changes are needed above fv3atm.

## Testing
These changes were tested on Hera using the Intel compilers.
Not all of the errors addressed here were uncovered by the standard RTs, but rather showed up when running in the EMC workflow. I was able to replicate these errors by extending the RTs and running the tests for longer forecast times.
Updates to the RT baselines are needed.

## Dependencies
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/392
- waiting on https://github.com/NCAR/ccpp-physics/pull/733

2021-09-21 19:21 UTC, climbfuji requested changes
CICE and MOM6 submodule pointers need updating.

2021-10-06 14:39 UTC, climbfuji reviewed
Please clarify if additional input data is needed, and which regression tests will change results.

2021-10-06 14:39 UTC, climbfuji commented on tests/parm/control_rrtmgp.nml.IN
> +  lw_file_gas        = 'rrtmgp-data-lw-g128-210809.nc'
@dustinswales Do we need to add these files to our input data directories? Or are they already present?

2021-10-06 15:05 UTC, dustinswales commented on tests/parm/control_rrtmgp.nml.IN
> +  lw_file_gas        = 'rrtmgp-data-lw-g128-210809.nc'
@climbfuji Yes. There 2 new files, in rte-rrtmgp/rrtmgp/data, need to go into the input data directory.

2021-10-06 18:50 UTC, climbfuji commented on tests/rt.sh
> +  QUEUE=debug
You need to revert lines 245, 246, 248 before I can start regresssion testing, please.

2021-10-06 18:51 UTC, climbfuji commented on tests/rt.sh
> +  QUEUE=debug
And line 252. The only difference in `rt.sh` can be line 448 (`BL_DATE`).

2021-10-06 19:37 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/739437060/20211006193015/ufs-weather-model
Please make changes and add the following label back:
hera-gnu-BL

2021-10-06 19:50 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/739437060/20211006193006/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_3807
Test compile 004 failed failed 
Test compile 001 failed failed 
Test compile 002 failed failed 
Test compile 006 failed failed 
Test compile 003 failed failed 
Test compile 005 failed failed 
Test compile 007 failed failed 
Please make changes and add the following label back:
gaea-intel-BL

2021-10-06 19:57 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/739437060/20211006143010/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_355684
Test compile 001 failed failed 
Test compile 006 failed failed 
Test compile 004 failed failed 
Test compile 002 failed failed 
Test compile 005 failed failed 
Test compile 003 failed failed 
Test compile 007 failed failed 
Please make changes and add the following label back:
orion-intel-BL

2021-10-06 19:58 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/739437060/20211006193008/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_30997
Test compile 005 failed failed 
Test compile 002 failed failed 
Test compile 001 failed failed 
Test compile 004 failed failed 
Test compile 003 failed failed 
Test compile 007 failed failed 
Test compile 006 failed failed 
Please make changes and add the following label back:
jet-intel-BL

2021-10-06 21:31 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/739437060/20211006201511/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_20820
Test control_c192 011 failed failed 
Test control_c192 011 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

2021-10-06 21:44 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/739437060/20211006193729/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_10080
Baseline creation and move successful
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/739437060/20211006205422/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_11208
Test cpld_control_p7 001 failed in check_result failed 
Test cpld_control_p7 001 failed in run_test failed 
Test cpld_debug_p7 011 failed in check_result failed 
Test cpld_debug_p7 011 failed in run_test failed 
Test cpld_decomp_p7 004 failed in check_result failed 
Test cpld_decomp_p7 004 failed in run_test failed 
Test control_c48 019 failed in check_result failed 
Test control_c48 019 failed in run_test failed 
Test regional_control 030 failed in check_result failed 
Test regional_control 030 failed in run_test failed 
Test regional_quilt 032 failed in check_result failed 
Test regional_quilt 032 failed in run_test failed 
Test cpld_control_wave_p7 005 failed in check_result failed 
Test cpld_control_wave_p7 005 failed in run_test failed 
Test regional_quilt_netcdf_parallel 035 failed in check_result failed 
Test regional_quilt_netcdf_parallel 035 failed in run_test failed 
Test regional_quilt_hafs 034 failed in check_result failed 
Test regional_quilt_hafs 034 failed in run_test failed 
Test control_c192 020 failed in check_result failed 
Test control_c192 020 failed in run_test failed 
Test regional_quilt_RRTMGP 036 failed in check_result failed 
Test regional_quilt_RRTMGP 036 failed in run_test failed 
Test cpld_2threads_p7 003 failed in check_result failed 
Test cpld_2threads_p7 003 failed in run_test failed 
Test control_rrtmgp 042 failed in check_result failed 
Test control_rrtmgp 042 failed in run_test failed 
Test regional_quilt_2threads 033 failed in check_result failed 
Test regional_quilt_2threads 033 failed in run_test failed 
Test control_csawmg 044 failed in check_result failed 
Test control_csawmg 044 failed in run_test failed 
Test control_ras 047 failed in check_result failed 
Test control_ras 047 failed in run_test failed 
Test control_flake 046 failed in check_result failed 
Test control_flake 046 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 050 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson 050 failed in run_test failed 
Test control_thompson 048 failed in check_result failed 
Test control_thompson 048 failed in run_test failed 
Test control_thompson_no_aero 049 failed in check_result failed 
Test control_thompson_no_aero 049 failed in run_test failed 
Test control_csawmgt 045 failed in check_result failed 
Test control_csawmgt 045 failed in run_test failed 
Test control_c384 021 failed in check_result failed 
Test control_c384 021 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 051 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 051 failed in run_test failed 
Test hafs_regional_atm 075 failed in check_result failed 
Test hafs_regional_atm 075 failed in run_test failed 
Test control_rrtmgp_c192 043 failed in check_result failed 
Test control_rrtmgp_c192 043 failed in run_test failed 
Test control_atm_aerosols 092 failed in check_result failed 
Test control_atm_aerosols 092 failed in run_test failed 
Test datm_cdeps_mx025_gefs 087 failed in check_result failed 
Test datm_cdeps_mx025_gefs 087 failed in run_test failed 
Test hafs_regional_docn 077 failed in check_result failed 
Test hafs_regional_docn 077 failed in run_test failed 
Test hafs_regional_atm_ocn 076 failed in check_result failed 
Test hafs_regional_atm_ocn 076 failed in run_test failed 
Test hafs_regional_docn_oisst 078 failed in check_result failed 
Test hafs_regional_docn_oisst 078 failed in run_test failed 
Test control_c384gdas 022 failed in check_result failed 
Test control_c384gdas 022 failed in run_test failed 
Test cpld_control_c192_p7 006 failed in check_result failed 
Test cpld_control_c192_p7 006 failed in run_test failed 
Test cpld_bmark_p7 010 failed in check_result failed 
Test cpld_bmark_p7 010 failed in run_test failed 
Test cpld_control_c384_p7 008 failed in check_result failed 
Test cpld_control_c384_p7 008 failed in run_test failed 
Test control_decomp 013 failed failed 
Test control_decomp 013 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

2021-10-06 22:20 UTC, BrianCurtis-NOAA commented
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/739437060/20211006150016/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_209948
Baseline creation and move successful
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/739437060/20211006161653/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_94577
Test control_c384gdas 022 failed failed 
Test control_c384gdas 022 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

2021-10-07 14:00 UTC, MinsukJi-NOAA approved these changes

2021-10-07 15:35 UTC, junwang-noaa approved these changes

2021-10-07 15:36 UTC, DusanJovic-NOAA approved these changes

2021-10-07 16:49 UTC, climbfuji commented
@dustinswales fv3atm was merged, new hash is f7ed0e0.

2021-10-07 17:09 UTC, climbfuji approved these changes

2021-10-07 17:10 UTC, merged