Mr2memL
ufs-community/ufs-weather-model pull request #903
Opened 2021-11-09 15:27 UTC by AnningCheng-NOAA

# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<902>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel regression tests has been successful in hera
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? No, it is independent of other PRs
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

2021-11-10 13:33 UTC, DeniseWorthen commented
Please fill out the required information in the PR template, including the relevant PRs that you've made in FV3 or CCPP relating to this change.

2021-11-10 14:53 UTC, AnningCheng-NOAA commented
Denise, I have just updated the template. Please let me know that I missed
anything.

On Wed, Nov 10, 2021 at 8:33 AM Denise Worthen ***@***.***>
wrote:

> Please fill out the required information in the PR template, including the
> relevant PRs that you've made in FV3 or CCPP relating to this change.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/903#issuecomment-965146891>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQPMIIEEFEUDF4Q2TLMTOTULJYBZANCNFSM5HVSQDSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 18:58 UTC, DeniseWorthen commented
Anning, it looks like this also makes a change in ccpp/physics but I don't see it listed here. 

It's also really helpful to have the actual link to the issue or PR in the template. You can do that by using the 'insert link' button and then copying the url from the other repo. Or, within the same repo (for example, in FV3), you can just start typing the words "fixes #" and a list of possible issues and PRs will pop-up for you to chose from. 

Also, can you edit the title of your FV3 PR? It needs to be descriptive of your change and you have "changes made in gitmodules"

2021-11-10 19:16 UTC, AnningCheng-NOAA commented
Denise, I do not know how to edit the title of my FV3 PR. Could you give
some instructions?

On Wed, Nov 10, 2021 at 1:58 PM Denise Worthen ***@***.***>
wrote:

> Anning, it looks like this also makes a change in ccpp/physics but I don't
> see it listed here.
>
> It's also really helpful to have the actual link to the issue or PR in the
> template. You can do that by using the 'insert link' button and then
> copying the url from the other repo. Or, within the same repo (for example,
> in FV3), you can just start typing the words "fixes #" and a list of
> possible issues and PRs will pop-up for you to chose from.
>
> Also, can you edit the title of your FV3 PR? It needs to be descriptive of
> your change and you have "changes made in gitmodules"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/903#issuecomment-965645734>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQPMIMZQIL273YL7RNTMS3ULK6FNANCNFSM5HVSQDSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 19:18 UTC, DeniseWorthen commented
On the far right side next to the title is a button that says "edit". You can change the title there.

2021-11-10 19:34 UTC, AnningCheng-NOAA commented
Denise, Thank you! I have just changed the title of my PRs.

On Wed, Nov 10, 2021 at 2:18 PM Denise Worthen ***@***.***>
wrote:

> On the far right side next to the title is a button that says "edit". You
> can change the title there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-weather-model/pull/903#issuecomment-965662345>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQPMINDOH3UQ2ERAWHN4DLULLARPANCNFSM5HVSQDSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-18 14:46 UTC, junwang-noaa commented
Please fix the revision of your fv3 branch.

2021-11-18 16:43 UTC, climbfuji reviewed
Looks good to me. Will approve after regression testing is complete and the submodule pointer was updated.

2021-11-18 19:56 UTC, junwang-noaa commented
@climbfuji All the RT passed. Would you please commit CCPP PR#774? Thanks

2021-11-18 19:58 UTC, climbfuji commented
> @climbfuji All the RT passed. Would you please commit CCPP PR#774? Thanks

Done - new ccpp-physics hash is 27a312c

2021-11-18 20:57 UTC, climbfuji commented on .gitmodules
> -  url = https://github.com/AnningCheng-NOAA/fv3atm
This still needs to be reverted.

2021-11-18 20:58 UTC, climbfuji requested changes
`.gitmodules` needs to be reverted

2021-11-18 21:00 UTC, junwang-noaa approved these changes

2021-11-18 21:01 UTC, climbfuji approved these changes

2021-11-18 21:02 UTC, merged